export const subSpecialWeaponMarkdownCodes = {
  "curling_bomb": "Wsb_Bomb_Curling",
  "fizzy_bomb": "Wsb_Bomb_Piyo",
  "burst_bomb": "Wsb_Bomb_Quick",
  "autobomb": "Wsb_Bomb_Robo",
  "splat_bomb": "Wsb_Bomb_Splash",
  "suction_bomb": "Wsb_Bomb_Suction",
  "torpedo": "Wsb_Bomb_Tako",
  "squid_beacon": "Wsb_Flag",
  "point_sensor": "Wsb_PointSensor",
  "splash_wall": "Wsb_Shield",
  "toxic_mist": "Wsb_PoisonFog",
  "sprinkler": "Wsb_Sprinkler",
  "ink_mine": "Wsb_TimerTrap",

  "baller": "Wsp_AquaBall",
  "inkjet": "Wsp_Jetpack",
  "launcher_curling": "Wsp_LauncherCurling",
  "launcher_burst": "Wsp_LauncherQuick",
  "launcher_auto": "Wsp_LauncherRobo",
  "launcher_splat": "Wsp_LauncherSplash",
  "launcher_suction": "Wsp_LauncherSuction",
  "ink_storm": "Wsp_RainCloud",
  "ink_armor": "Wsp_SuperArmor",
  "booyah_bomb": "Wsp_SuperBall",
  "bubble_blower": "Wsp_SuperBubble",
  "splashdown": "Wsp_SuperLanding",
  "tenta_missiles": "Wsp_SuperMissile",
  "ultra_stamp": "Wsp_SuperStamp",
  "sting_ray": "Wsp_WaterCutter",
};