import { t } from "@lingui/macro";

export const gear = [
  {
    brand: t`amiibo`,
    clothing: [
      t`Enchanted Robe`,
      t`Fresh Fish Gloves`,
      t`Marinated Top`,
      t`Pearlescent Hoodie`,
      t`Power Armor`,
      t`Power Armor Mk I`,
      t`Samurai Jacket`,
      t`School Cardigan`,
      t`School Uniform`,
      t`Squinja Suit`,
      t`Steel Platemail`,
    ],
    head: [
      t`Enchanted Hat`,
      t`Fresh Fish Head`,
      t`Marinated Headphones`,
      t`Pearlescent Crown`,
      t`Power Mask`,
      t`Power Mask Mk I`,
      t`Samurai Helmet`,
      t`Squid Clip-Ons`,
      t`Squid Hairclip`,
      t`Squinja Mask`,
      t`Steel Helm`,
    ],
    shoes: [
      t`Enchanted Boots`,
      t`Fresh Fish Feet`,
      t`Fringed Loafers`,
      t`Marinated Slip-Ons`,
      t`Pearlescent Kicks`,
      t`Power Boots`,
      t`Power Boots Mk I`,
      t`Samurai Shoes`,
      t`School Shoes`,
      t`Squinja Boots`,
      t`Steel Greaves`,
    ],
  },
  {
    brand: t`Annaki`,
    clothing: [
      t`Annaki Blue Cuff`,
      t`Annaki Drive Tee`,
      t`Annaki Evolution Tee`,
      t`Annaki Flannel Hoodie`,
      t`Annaki Polpo-Pic Tee`,
      t`Annaki Red Cuff`,
      t`Annaki Yellow Cuff`,
      t`Crimson Parashooter`,
      t`Hula Punk Shirt`,
      t`Prune Parashooter`,
      t`Red Hula Punk with Tie`,
      t`Rockin' Leather Jacket`,
    ],
    head: [t`Annaki Beret`, t`Annaki Beret & Glasses`, t`Annaki Mask`],
    shoes: [t`Annaki Arachno Boots`, t`Annaki Habaneros`, t`Annaki Tigers`],
  },
  {
    brand: t`Cuttlegear`,
    clothing: [
      t`Armor Jacket Replica`,
      t`Black Cuttlegear LS`,
      t`Fresh Octo Tee`,
      t`Hero Hoodie Replica`,
      t`Hero Jacket Replica`,
      t`Neo Octoling Armor`,
      t`Null Armor Replica`,
      t`Octarian Retro`,
      t`Octo Layered LS`,
      t`Octo Tee`,
      t`Old-Timey Clothes`,
      t`Red Cuttlegear LS`,
      t`Sennyu Suit`,
    ],
    head: [
      t`Armor Helmet Replica`,
      t`Conductor Cap`,
      t`Golden Toothpick`,
      t`Hero Headphones Replica`,
      t`Hero Headset Replica`,
      t`Null Visor Replica`,
      t`Octoling Shades`,
      t`Old-Timey Hat`,
      t`Studio Octophones`,
    ],
    shoes: [
      t`Armor Boot Replicas`,
      t`Hero Runner Replicas`,
      t`Hero Snowboots Replicas`,
      t`Neo Octoling Boots`,
      t`Null Boots Replica`,
      t`Old-Timey Shoes`,
    ],
  },
  {
    brand: t`Enperry`,
    clothing: [
      t`Black Velour Octoking Tee`,
      t`Grape Hoodie`,
      t`Green Velour Octoking Tee`,
      t`King Jersey`,
      t`Milky Eminence Jacket`,
      t`N-Pacer Sweat`,
      t`Navy Eminence Jacket`,
      t`Navy King Tank`,
      t`Octoking HK Jersey`,
      t`Slash King Tank`,
      t`White King Tank`,
    ],
    head: [
      t`Eminence Cuff`,
      t`King Facemask`,
      t`King Flip Mesh`,
      t`Octoking Facemask`,
    ],
    shoes: [
      t`Black & Blue Squidkid V`,
      t`Blue & Black Squidkid IV`,
      t`Honey & Orange Squidkid V`,
      t`Milky Enperrials`,
      t`N-Pacer Ag`,
      t`N-Pacer Au`,
      t`N-Pacer CaO`,
      t`Navy Enperrials`,
      t`Online Squidkid V`,
      t`Pearlescent Squidkid IV`,
      t`Red & Black Squidkid IV`,
      t`Red & White Squidkid V`,
      t`Rina Squidkid IV`,
      t`Sun & Shade Squidkid IV`,
    ],
  },
  {
    brand: t`Firefin`,
    clothing: [
      t`Baseball Jersey`,
      t`Black 8-Bit FishFry`,
      t`Blue 16-Bit FishFry`,
      t`Camo Zip Hoodie`,
      t`Carnivore Tee`,
      t`Dark Urban Vest`,
      t`Firefin Navy Sweat`,
      t`Fugu Tee`,
      t`Gray 8-Bit FishFry`,
      t`Green Zip Hoodie`,
      t`Herbivore Tee`,
      t`Khaki 16-Bit FishFry`,
      t`White 8-Bit FishFry`,
      t`Yellow Urban Vest`,
      t`ω-3 Tee`,
    ],
    head: [
      t`Black FishFry Bandana`,
      t`Blowfish Bell Hat`,
      t`Blowfish Newsie`,
      t`Camo Mesh`,
      t`Firefin Facemask`,
      t`FishFry Biscuit Bandana`,
      t`FishFry Visor`,
      t`Fugu Bell Hat`,
      t`Jet Cap`,
      t`Jungle Hat`,
      t`Knitted Hat`,
      t`Octoglasses`,
    ],
    shoes: [t`Red FishFry Sandals`, t`Yellow FishFry Sandals`],
  },
  {
    brand: t`Forge`,
    clothing: [
      t`Aloha Shirt`,
      t`Blue Sailor Suit`,
      t`Brown FA-11 Bomber`,
      t`Custom Painted F-3`,
      t`FA-01 Jacket`,
      t`FA-01 Reversed`,
      t`Forge Inkling Parka`,
      t`Forge Octarian Jacket`,
      t`Gray FA-11 Bomber`,
      t`Green Tee`,
      t`Moist Ghillie Suit`,
      t`White Leather F-3`,
      t`White Sailor Suit`,
    ],
    head: [
      t`Deca Tackle Visor Helmet`,
      t`Designer Headphones`,
      t`Digi-Camo Forge Mask`,
      t`Forge Mask`,
      t`Gas Mask`,
      t`Hockey Helmet`,
      t`Moist Ghillie Helmet`,
      t`Motocross Nose Guard`,
      t`Noise Cancelers`,
      t`Octo Tackle Helmet Deco`,
      t`Paintball Mask`,
      t`Pilot Goggles`,
      t`Safari Hat`,
      t`Sennyu Goggles`,
      t`Sennyu Headphones`,
      t`Skull Bandana`,
      t`Snorkel Mask`,
      t`Special Forces Beret`,
      t`Splash Goggles`,
      t`Squidfin Hook Cans`,
      t`Squidlife Headphones`,
      t`Stealth Goggles`,
      t`Studio Headphones`,
      t`Treasure Hunter`,
    ],
    shoes: [t`Moist Ghillie Boots`],
  },
  {
    brand: t`Grizzco`,
    clothing: [
      t`Anchor Life Vest`,
      t`Crustwear XXL`,
      t`Dev Uniform`,
      t`Garden Gear`,
      t`Juice Parka`,
      t`North-Country Parka`,
      t`Octoleet Armor`,
      t`Office Attire`,
      t`Online Jersey`,
      t`Record Shop Look EP`,
      t`Squiddor Polo`,
      t`SRL Coat`,
    ],
    head: [
      t`Beekeeper Hat`,
      t`Cap of Legend`,
      t`Dust Blocker 2000`,
      t`Headlamp Helmet`,
      t`Oceanic Hard Hat`,
      t`Octoleet Goggles`,
      t`Sailor Cap`,
      t`Welding Mask`,
      t`Worker's Cap`,
      t`Worker's Head Towel`,
    ],
    shoes: [
      t`Angry Rain Boots`,
      t`Flipper Floppers`,
      t`Friendship Bracelet`,
      t`Non-slip Senseis`,
      t`Octoleet Boots`,
      t`Wooden Sandals`,
    ],
  },
  {
    brand: t`Inkline`,
    clothing: [
      t`Berry Ski Jacket`,
      t`Blue Peaks Tee`,
      t`Chili-Pepper Ski Jacket`,
      t`Chilly Mountain Coat`,
      t`Eggplant Mountain Coat`,
      t`Fishing Vest`,
      t`Forest Vest`,
      t`Green Striped LS`,
      t`Ivory Peaks Tee`,
      t`Matcha Down Jacket`,
      t`Mountain Vest`,
      t`Olive Ski Jacket`,
      t`Striped Peaks LS`,
    ],
    head: [
      t`Bamboo Hat`,
      t`Camping Hat`,
      t`Lightweight Cap`,
      t`Mountie Hat`,
      t`Seashell Bamboo Hat`,
      t`Short Beanie`,
      t`Tulip Parasol`,
      t`Yamagiri Beanie`,
    ],
    shoes: [
      t`Acerola Rain Boots`,
      t`Birch Climbing Shoes`,
      t`Bubble Rain Boots`,
      t`Custom Trail Boots`,
      t`Green Rain Boots`,
      t`Luminous Delta Straps`,
      t`Musselforge Flip-Flops`,
      t`Neon Delta Straps`,
      t`Pro Trail Boots`,
      t`Snow Delta Straps`,
      t`Sunny Climbing Shoes`,
      t`Trail Boots`,
    ],
  },
  {
    brand: t`Krak-On`,
    clothing: [
      t`Chili Octo Aloha`,
      t`Krak-On 528`,
      t`Missus Shrug Tee`,
      t`Mister Shrug Tee`,
      t`Octobowler Shirt`,
      t`Rainy-Day Tee`,
      t`Rodeo Shirt`,
      t`Squid-Pattern Waistcoat`,
      t`Squidstar Waistcoat`,
      t`Sunny-Day Tee`,
    ],
    head: [
      t`Full Moon Glasses`,
      t`Hickory Work Cap`,
      t`Long-Billed Cap`,
      t`Paisley Bandana`,
      t`Two-Stripe Mesh`,
      t`Woolly Urchins Classic`,
    ],
    shoes: [
      t`Banana Basics`,
      t`Blue Slip-Ons`,
      t`Blueberry Casuals`,
      t`Choco Clogs`,
      t`Clownfish Basics`,
      t`Cream Basics`,
      t`Cream Hi-Tops`,
      t`Hunter Hi-Tops`,
      t`Midnight Slip-Ons`,
      t`Oyster Clogs`,
      t`Plum Casuals`,
      t`Polka-dot Slip-Ons`,
      t`Red Hi-Tops`,
      t`Red Slip-Ons`,
      t`Squid-Stitch Slip-Ons`,
      t`Truffle Canvas Hi-Tops`,
    ],
  },
  {
    brand: t`Rockenberg`,
    clothing: [
      t`Black Baseball LS`,
      t`Black Inky Rider`,
      t`Black Urchin Rock Tee`,
      t`Chirpy Chips Band Tee`,
      t`Hightide Era Band Tee`,
      t`Lumberjack Shirt`,
      t`Rockenberg Black`,
      t`Rockenberg White`,
      t`Round-Collar Shirt`,
      t`Squid Squad Band Tee`,
      t`Vintage Check Shirt`,
      t`Wet Floor Band Tee`,
      t`White Baseball LS`,
      t`White Inky Rider`,
      t`White Urchin Rock Tee`,
    ],
    head: [t`18K Aviators`, t`SV925 Circle Shades`],
    shoes: [
      t`Blue Moto Boots`,
      t`Cherry Kicks`,
      t`Deepsea Leather Boots`,
      t`Gray Yellow-Soled Wingtips`,
      t`Inky Kid Clams`,
      t`Kid Clams`,
      t`Moto Boots`,
      t`Navy Red-Soled Wingtips`,
      t`New-Leaf Leather Boots`,
      t`Pearl Punk Crowns`,
      t`Punk Blacks`,
      t`Punk Cherries`,
      t`Punk Whites`,
      t`Punk Yellows`,
      t`Red Work Boots`,
      t`Roasted Brogues`,
      t`Sennyu Inksoles`,
      t`Smoky Wingtips`,
      t`Squink Wingtips`,
      t`Tan Work Boots`,
      t`Turquoise Kicks`,
      t`White Kicks`,
    ],
  },
  {
    brand: t`Skalop`,
    clothing: [
      t`Black Hoodie`,
      t`Dots-On-Dots Shirt`,
      t`Firewave Tee`,
      t`Grape Tee`,
      t`Gray Hoodie`,
      t`Hothouse Hoodie`,
      t`Icewave Tee`,
      t`Mint Tee`,
      t`Pearl Tee`,
      t`Reggae Tee`,
      t`Squid-Stitch Tee`,
    ],
    head: [
      t`Bike Helmet`,
      t`Classic Straw Boater`,
      t`Do-Rag, Cap, & Glasses`,
      t`Hothouse Hat`,
      t`Jellyvader Cap`,
      t`Patched Hat`,
      t`Skate Helmet`,
      t`Sneaky Beanie`,
      t`Sporty Bobble Hat`,
      t`Squid Nordic`,
      t`Squid-Stitch Cap`,
      t`Squidvader Cap`,
      t`Straw Boater`,
      t`Streetstyle Cap`,
      t`Urchins Cap`,
      t`Visor Skate Helmet`,
    ],
    shoes: [],
  },
  {
    brand: t`Splash Mob`,
    clothing: [
      t`Baby-Jelly Shirt`,
      t`Baby-Jelly Shirt & Tie`,
      t`Gray College Sweat`,
      t`Green Cardigan`,
      t`Lime Easy-Stripe Shirt`,
      t`Linen Shirt`,
      t`Navy College Sweat`,
      t`Navy Striped LS`,
      t`Orange Cardigan`,
      t`Pink Easy-Stripe Shirt`,
      t`Pink Hoodie`,
      t`Pirate-Stripe Tee`,
      t`Sage Polo`,
      t`Sailor-Stripe Tee`,
      t`Shirt & Tie`,
      t`Shirt with Blue Hoodie`,
      t`Shrimp-Pink Polo`,
      t`Striped Shirt`,
      t`Varsity Baseball LS`,
      t`Whale-Knit Sweater`,
      t`White Shirt`,
      t`White Striped LS`,
    ],
    head: [
      t`Bobble Hat`,
      t`Half-Rim Glasses`,
      t`House-Tag Denim Cap`,
      t`Pilot Hat`,
      t`Retro Specs`,
      t`Sennyu Bon Bon Beanie`,
      t`Sennyu Specs`,
      t`Striped Beanie`,
    ],
    shoes: [
      t`Green Laceups`,
      t`Hunting Boots`,
      t`Mawcasins`,
      t`Piranha Moccasins`,
      t`Shark Moccasins`,
      t`Strapping Reds`,
      t`Strapping Whites`,
      t`Tea-Green Hunting Boots`,
    ],
  },
  {
    brand: t`SquidForce`,
    clothing: [
      t`Anchor Sweat`,
      t`Basic Tee`,
      t`Black Anchor Tee`,
      t`Black Layered LS`,
      t`Black Tee`,
      t`Black V-Neck Tee`,
      t`Camo Layered LS`,
      t`Friend Tee`,
      t`Green V-Neck Limited Tee`,
      t`Layered Anchor LS`,
      t`League Tee`,
      t`Mecha Body - AKM`,
      t`Octo Support Hoodie`,
      t`Red V-Neck Limited Tee`,
      t`Retro Sweat`,
      t`Splatfest Tee`,
      t`Squid Yellow Layered LS`,
      t`Squidmark LS`,
      t`Squidmark Sweat`,
      t`SWC Logo Tee`,
      t`White Anchor Tee`,
      t`White Layered LS`,
      t`White LS`,
      t`White Tee`,
      t`White V-Neck Tee`,
      t`Yellow Layered LS`,
    ],
    head: [
      t`Anglerfish Mask`,
      t`Bucket Hat`,
      t`Eel-Cake Hat`,
      t`Festive Party Cone`,
      t`Hockey Mask`,
      t`Koshien Bandana`,
      t`Kyonshi Hat`,
      t`Li'l Devil Horns`,
      t`Mecha Head - HTR`,
      t`New Year's Glasses DX`,
      t`Painter's Mask`,
      t`Squid Facemask`,
      t`Twisty Headband`,
      t`White Headband`,
      t`Jetflame Crest`,
      t`Fierce Fishskull`,
      t`Hivemind Antenna`,
      t`Eye of Justice`,
    ],
    shoes: [t`Mecha Legs - LBS`],
  },
  {
    brand: t`Takoroka`,
    clothing: [
      t`Choco Layered LS`,
      t`FC Albacore`,
      t`Gray Vector Tee`,
      t`Layered Vector LS`,
      t`Purple Camo LS`,
      t`Red Vector Tee`,
      t`Slipstream United`,
      t`Striped Rugby`,
      t`Takoroka Crazy Baseball LS`,
      t`Takoroka Galactic Tie Dye`,
      t`Takoroka Jersey`,
      t`Takoroka Nylon Vintage`,
      t`Takoroka Rainbow Tie Dye`,
      t`Takoroka Windcrusher`,
      t`Tricolor Rugby`,
    ],
    head: [t`Takoroka Mesh`, t`Takoroka Visor`],
    shoes: [
      t`Athletic Arrows`,
      t`Blue Power Stripes`,
      t`Crazy Arrows`,
      t`LE Soccer Shoes`,
      t`New-Day Arrows`,
      t`Orange Arrows`,
      t`Orca Hi-Tops`,
      t`Orca Passion Hi-Tops`,
      t`Orca Woven Hi-Tops`,
      t`Red Power Stripes`,
      t`Soccer Shoes`,
      t`Sunset Orca Hi-Tops`,
      t`Trooper Power Stripes`,
      t`White Arrows`,
    ],
  },
  {
    brand: t`Tentatek`,
    clothing: [
      t`Black Squideye`,
      t`Blue Tentatek Tee`,
      t`Cycle King Jersey`,
      t`Lob-Stars Jersey`,
      t`Part-Time Pirate`,
      t`Red Tentatek Tee`,
      t`Silver Tentatek Vest`,
      t`Sky-Blue Squideye`,
      t`Tentatek Slogan Tee`,
    ],
    head: [
      t`Cycle King Cap`,
      t`Fake Contacts`,
      t`Green Novelty Visor`,
      t`Orange Novelty Visor`,
      t`Pink Novelty Visor`,
      t`Purple Novelty Visor`,
      t`Soccer Headband`,
      t`Sun Visor`,
      t`Tennis Headband`,
    ],
    shoes: [
      t`Amber Sea Slug Hi-Tops`,
      t`Black Norimaki 750s`,
      t`Black Trainers`,
      t`Blue Iromaki 750s`,
      t`Blue Sea Slugs`,
      t`Canary Trainers`,
      t`Cyan Trainers`,
      t`Gray Sea-Slug Hi-Tops`,
      t`Green Iromaki 750s`,
      t`Icy Down Boots`,
      t`Neon Sea Slugs`,
      t`Orange Iromaki 750s`,
      t`Pink Trainers`,
      t`Purple Iromaki 750s`,
      t`Purple Sea Slugs`,
      t`Red Iromaki 750s`,
      t`Red Sea Slugs`,
      t`Red-Mesh Sneakers`,
      t`Sea Slug Volt 95s`,
      t`Sesame Salt 270s`,
      t`Snowy Down Boots`,
      t`Violet Trainers`,
      t`White Norimaki 750s`,
      t`Yellow Iromaki 750s`,
      t`Yellow-Mesh Sneakers`,
    ],
  },
  {
    brand: t`Toni Kensa`,
    clothing: [
      t`Dark Bomber Jacket`,
      t`Front Zip Vest`,
      t`Half-Sleeve Sweater`,
      t`Ink-Wash Shirt`,
      t`Inkfall Shirt`,
      t`Kensa Coat`,
      t`Kung-Fu Zip-Up`,
      t`Light Bomber Jacket`,
      t`Negative Longcuff Sweater`,
      t`Panda Kung-Fu Zip-Up`,
      t`Positive Longcuff Sweater`,
      t`Pullover Coat`,
      t`Short Knit Layers`,
      t`Toni K. Baseball Jersey`,
    ],
    head: [t`Face Visor`, t`Ink-Guard Goggles`, t`Toni Kensa Goggles`],
    shoes: [
      t`Arrow Pull-Ons`,
      t`Toni Kensa Black Hi-Tops`,
      t`Toni Kensa Soccer Shoes`,
    ],
  },
  {
    brand: t`Zekko`,
    clothing: [
      t`Birded Corduroy Jacket`,
      t`Black LS`,
      t`Black Polo`,
      t`Deep-Octo Satin Jacket`,
      t`Gray Mixed Shirt`,
      t`Green-Check Shirt`,
      t`Logo Aloha Shirt`,
      t`Olive Zekko Parka`,
      t`Red-Check Shirt`,
      t`Reel Sweat`,
      t`Squid Satin Jacket`,
      t`Tumeric Zekko Coat`,
      t`Varsity Jacket`,
      t`Zapfish Satin Jacket`,
      t`Zekko Baseball LS`,
      t`Zekko Hoodie`,
      t`Zekko Jade Coat`,
      t`Zekko Long Carrot Tee`,
      t`Zekko Long Radish Tee`,
      t`Zekko Redleaf Coat`,
    ],
    head: [
      t`Backwards Cap`,
      t`Black Arrowbands`,
      t`Double Egg Shades`,
      t`Five-Panel Cap`,
      t`Jogging Headband`,
      t`Matte Bike Helmet`,
      t`MTB Helmet`,
      t`Tinted Shades`,
      t`White Arrowbands`,
      t`Zekko Cap`,
      t`Zekko Mesh`,
    ],
    shoes: [
      t`Black Flip-Flops`,
      t`Blue Lo-Tops`,
      t`LE Lo-Tops`,
      t`Marination Lace-Ups`,
      t`Orange Lo-Tops`,
      t`Pearl-Scout Lace-Ups`,
      t`Suede Gray Lace-Ups`,
      t`Suede Marine Lace-Ups`,
      t`Suede Nation Lace-Ups`,
    ],
  },
  {
    brand: t`Zink`,
    clothing: [
      t`B-ball Jersey (Away)`,
      t`B-ball Jersey (Home)`,
      t`Cycling Shirt`,
      t`Dakro Golden Tee`,
      t`Dakro Nana Tee`,
      t`Inkopolis Squaps Jersey`,
      t`Navy Deca Logo Tee`,
      t`Retro Gamer Jersey`,
      t`School Jersey`,
      t`Urchins Jersey`,
      t`White Deca Logo Tee`,
      t`Zink Layered LS`,
      t`Zink LS`,
    ],
    head: [
      t`B-ball Headband`,
      t`Cycling Cap`,
      t`Golf Visor`,
      t`Squash Headband`,
      t`Swim Goggles`,
    ],
    shoes: [
      t`Black Dakroniks`,
      t`Black Seahorses`,
      t`Blue Laceless Dakroniks`,
      t`Chocolate Dakroniks`,
      t`Gold Hi-Horses`,
      t`Mint Dakroniks`,
      t`Purple Hi-Horses`,
      t`Red Hi-Horses`,
      t`White Laceless Dakroniks`,
      t`White Seahorses`,
      t`Yellow Seahorses`,
      t`Zombie Hi-Horses`,
    ],
  },
];

export const headGear = gear.flatMap((brand) => brand.head);
export const clothingGear = gear.flatMap((brand) => brand.clothing);
// for some reason TypeScript freaked out when just using .flatMap() here
export const shoesGear = gear.map((brand) => brand.shoes).flat();
