export const gearMarkdownCodes = {
  enchanted_hat: "Enchanted Hat",
  fresh_fish_head: "Fresh Fish Head",
  marinated_headphones: "Marinated Headphones",
  pearlescent_crown: "Pearlescent Crown",
  power_mask: "Power Mask",
  power_mask_mk_i: "Power Mask Mk I",
  samurai_helmet: "Samurai Helmet",
  "squid_clip-ons": "Squid Clip-Ons",
  squid_hairclip: "Squid Hairclip",
  squinja_mask: "Squinja Mask",
  steel_helm: "Steel Helm",
  enchanted_robe: "Enchanted Robe",
  fresh_fish_gloves: "Fresh Fish Gloves",
  marinated_top: "Marinated Top",
  pearlescent_hoodie: "Pearlescent Hoodie",
  power_armor: "Power Armor",
  power_armor_mk_i: "Power Armor Mk I",
  samurai_jacket: "Samurai Jacket",
  school_cardigan: "School Cardigan",
  school_uniform: "School Uniform",
  squinja_suit: "Squinja Suit",
  steel_platemail: "Steel Platemail",
  enchanted_boots: "Enchanted Boots",
  fresh_fish_feet: "Fresh Fish Feet",
  fringed_loafers: "Fringed Loafers",
  "marinated_slip-ons": "Marinated Slip-Ons",
  pearlescent_kicks: "Pearlescent Kicks",
  power_boots: "Power Boots",
  power_boots_mk_i: "Power Boots Mk I",
  samurai_shoes: "Samurai Shoes",
  school_shoes: "School Shoes",
  squinja_boots: "Squinja Boots",
  steel_greaves: "Steel Greaves",
  annaki_beret: "Annaki Beret",
  "annaki_beret_&_glasses": "Annaki Beret & Glasses",
  annaki_mask: "Annaki Mask",
  annaki_blue_cuff: "Annaki Blue Cuff",
  annaki_drive_tee_: "Annaki Drive Tee ",
  annaki_evolution_tee: "Annaki Evolution Tee",
  annaki_flannel_hoodie: "Annaki Flannel Hoodie",
  "annaki_polpo-pic_tee": "Annaki Polpo-Pic Tee",
  annaki_red_cuff: "Annaki Red Cuff",
  annaki_yellow_cuff: "Annaki Yellow Cuff",
  crimson_parashooter: "Crimson Parashooter",
  hula_punk_shirt: "Hula Punk Shirt",
  prune_parashooter: "Prune Parashooter",
  red_hula_punk_with_tie: "Red Hula Punk with Tie",
  rockin_leather_jacket: "Rockin' Leather Jacket",
  annaki_arachno_boots: "Annaki Arachno Boots",
  annaki_habaneros: "Annaki Habaneros",
  annaki_tigers: "Annaki Tigers",
  armor_helmet_replica: "Armor Helmet Replica",
  conductor_cap: "Conductor Cap",
  golden_toothpick: "Golden Toothpick",
  hero_headphones_replica: "Hero Headphones Replica",
  hero_headset_replica: "Hero Headset Replica",
  null_visor_replica: "Null Visor Replica",
  octoling_shades: "Octoling Shades",
  "old-timey_hat": "Old-Timey Hat",
  studio_octophones: "Studio Octophones",
  armor_jacket_replica: "Armor Jacket Replica",
  black_cuttlegear_ls: "Black Cuttlegear LS",
  fresh_octo_tee: "Fresh Octo Tee",
  hero_hoodie_replica: "Hero Hoodie Replica",
  hero_jacket_replica: "Hero Jacket Replica",
  neo_octoling_armor: "Neo Octoling Armor",
  null_armor_replica: "Null Armor Replica",
  octarian_retro: "Octarian Retro",
  octo_layered_ls: "Octo Layered LS",
  octo_tee: "Octo Tee",
  "old-timey_clothes": "Old-Timey Clothes",
  red_cuttlegear_ls: "Red Cuttlegear LS",
  sennyu_suit: "Sennyu Suit",
  armor_boot_replicas: "Armor Boot Replicas",
  hero_runner_replicas: "Hero Runner Replicas",
  hero_snowboots_replicas: "Hero Snowboots Replicas",
  neo_octoling_boots: "Neo Octoling Boots",
  null_boots_replica: "Null Boots Replica",
  "old-timey_shoes": "Old-Timey Shoes",
  eminence_cuff: "Eminence Cuff",
  king_facemask: "King Facemask",
  king_flip_mesh: "King Flip Mesh",
  octoking_facemask: "Octoking Facemask",
  black_velour_octoking_tee_: "Black Velour Octoking Tee ",
  grape_hoodie: "Grape Hoodie",
  green_velour_octoking_tee: "Green Velour Octoking Tee",
  king_jersey: "King Jersey",
  milky_eminence_jacket: "Milky Eminence Jacket",
  "n-pacer_sweat": "N-Pacer Sweat",
  navy_eminence_jacket: "Navy Eminence Jacket",
  navy_king_tank: "Navy King Tank",
  octoking_hk_jersey: "Octoking HK Jersey",
  slash_king_tank: "Slash King Tank",
  white_king_tank: "White King Tank",
  "black_&_blue_squidkid_v": "Black & Blue Squidkid V",
  "blue_&_black_squidkid_iv": "Blue & Black Squidkid IV",
  "honey_&_orange_squidkid_v": "Honey & Orange Squidkid V",
  milky_enperrials: "Milky Enperrials",
  "n-pacer_ag": "N-Pacer Ag",
  "n-pacer_au": "N-Pacer Au",
  "n-pacer_cao": "N-Pacer CaO",
  navy_enperrials: "Navy Enperrials",
  online_squidkid_v: "Online Squidkid V",
  pearlescent_squidkid_iv: "Pearlescent Squidkid IV",
  "red_&_black_squidkid_iv": "Red & Black Squidkid IV",
  "red_&_white_squidkid_v": "Red & White Squidkid V",
  rina_squidkid_iv: "Rina Squidkid IV",
  "sun_&_shade_squidkid_iv": "Sun & Shade Squidkid IV",
  black_fishfry_bandana: "Black FishFry Bandana",
  blowfish_bell_hat: "Blowfish Bell Hat",
  blowfish_newsie: "Blowfish Newsie",
  camo_mesh: "Camo Mesh",
  firefin_facemask: "Firefin Facemask",
  fishfry_biscuit_bandana: "FishFry Biscuit Bandana",
  fishfry_visor: "FishFry Visor",
  fugu_bell_hat: "Fugu Bell Hat",
  jet_cap: "Jet Cap",
  jungle_hat: "Jungle Hat",
  knitted_hat: "Knitted Hat",
  octoglasses: "Octoglasses",
  baseball_jersey: "Baseball Jersey",
  "black_8-bit_fishfry": "Black 8-Bit FishFry",
  "blue_16-bit_fishfry": "Blue 16-Bit FishFry",
  camo_zip_hoodie: "Camo Zip Hoodie",
  carnivore_tee: "Carnivore Tee",
  dark_urban_vest: "Dark Urban Vest",
  firefin_navy_sweat: "Firefin Navy Sweat",
  fugu_tee: "Fugu Tee",
  "gray_8-bit_fishfry": "Gray 8-Bit FishFry",
  green_zip_hoodie: "Green Zip Hoodie",
  herbivore_tee: "Herbivore Tee",
  "khaki_16-bit_fishfry": "Khaki 16-Bit FishFry",
  "white_8-bit_fishfry": "White 8-Bit FishFry",
  yellow_urban_vest: "Yellow Urban Vest",
  "ω-3_tee": "ω-3 Tee",
  red_fishfry_sandals: "Red FishFry Sandals",
  yellow_fishfry_sandals: "Yellow FishFry Sandals",
  deca_tackle_visor_helmet: "Deca Tackle Visor Helmet",
  designer_headphones: "Designer Headphones",
  "digi-camo_forge_mask": "Digi-Camo Forge Mask",
  forge_mask: "Forge Mask",
  gas_mask: "Gas Mask",
  hockey_helmet: "Hockey Helmet",
  moist_ghillie_helmet: "Moist Ghillie Helmet",
  motocross_nose_guard: "Motocross Nose Guard",
  noise_cancelers: "Noise Cancelers",
  octo_tackle_helmet_deco: "Octo Tackle Helmet Deco",
  paintball_mask: "Paintball Mask",
  pilot_goggles: "Pilot Goggles",
  safari_hat: "Safari Hat",
  sennyu_goggles: "Sennyu Goggles",
  sennyu_headphones: "Sennyu Headphones",
  skull_bandana: "Skull Bandana",
  snorkel_mask: "Snorkel Mask",
  special_forces_beret: "Special Forces Beret",
  splash_goggles: "Splash Goggles",
  squidfin_hook_cans: "Squidfin Hook Cans",
  squidlife_headphones: "Squidlife Headphones",
  stealth_goggles: "Stealth Goggles",
  studio_headphones: "Studio Headphones",
  treasure_hunter: "Treasure Hunter",
  aloha_shirt: "Aloha Shirt",
  blue_sailor_suit: "Blue Sailor Suit",
  "brown_fa-11_bomber": "Brown FA-11 Bomber",
  "custom_painted_f-3_": "Custom Painted F-3 ",
  "fa-01_jacket": "FA-01 Jacket",
  "fa-01_reversed": "FA-01 Reversed",
  forge_inkling_parka: "Forge Inkling Parka",
  forge_octarian_jacket: "Forge Octarian Jacket",
  "gray_fa-11_bomber": "Gray FA-11 Bomber",
  green_tee: "Green Tee",
  moist_ghillie_suit: "Moist Ghillie Suit",
  "white_leather_f-3": "White Leather F-3",
  white_sailor_suit: "White Sailor Suit",
  moist_ghillie_boots: "Moist Ghillie Boots",
  beekeeper_hat: "Beekeeper Hat",
  cap_of_legend: "Cap of Legend",
  dust_blocker_2000: "Dust Blocker 2000",
  headlamp_helmet: "Headlamp Helmet",
  oceanic_hard_hat: "Oceanic Hard Hat",
  octoleet_goggles: "Octoleet Goggles",
  sailor_cap: "Sailor Cap",
  welding_mask: "Welding Mask",
  workers_cap: "Worker's Cap",
  workers_head_towel: "Worker's Head Towel",
  anchor_life_vest: "Anchor Life Vest",
  crustwear_xxl: "Crustwear XXL",
  dev_uniform: "Dev Uniform",
  garden_gear: "Garden Gear",
  juice_parka: "Juice Parka",
  "north-country_parka": "North-Country Parka",
  octoleet_armor: "Octoleet Armor",
  office_attire: "Office Attire",
  online_jersey: "Online Jersey",
  record_shop_look_ep: "Record Shop Look EP",
  squiddor_polo: "Squiddor Polo",
  srl_coat: "SRL Coat",
  angry_rain_boots: "Angry Rain Boots",
  flipper_floppers: "Flipper Floppers",
  friendship_bracelet: "Friendship Bracelet",
  "non-slip_senseis": "Non-slip Senseis",
  octoleet_boots: "Octoleet Boots",
  wooden_sandals: "Wooden Sandals",
  bamboo_hat: "Bamboo Hat",
  camping_hat: "Camping Hat",
  lightweight_cap: "Lightweight Cap",
  mountie_hat: "Mountie Hat",
  seashell_bamboo_hat: "Seashell Bamboo Hat",
  short_beanie: "Short Beanie",
  tulip_parasol: "Tulip Parasol",
  yamagiri_beanie: "Yamagiri Beanie",
  berry_ski_jacket: "Berry Ski Jacket",
  blue_peaks_tee: "Blue Peaks Tee",
  "chili-pepper_ski_jacket": "Chili-Pepper Ski Jacket",
  chilly_mountain_coat: "Chilly Mountain Coat",
  eggplant_mountain_coat: "Eggplant Mountain Coat",
  fishing_vest: "Fishing Vest",
  forest_vest: "Forest Vest",
  green_striped_ls: "Green Striped LS",
  ivory_peaks_tee: "Ivory Peaks Tee",
  matcha_down_jacket: "Matcha Down Jacket",
  mountain_vest: "Mountain Vest",
  olive_ski_jacket: "Olive Ski Jacket",
  striped_peaks_ls: "Striped Peaks LS",
  acerola_rain_boots: "Acerola Rain Boots",
  birch_climbing_shoes: "Birch Climbing Shoes",
  bubble_rain_boots: "Bubble Rain Boots",
  custom_trail_boots: "Custom Trail Boots",
  green_rain_boots: "Green Rain Boots",
  luminous_delta_straps: "Luminous Delta Straps",
  "musselforge_flip-flops": "Musselforge Flip-Flops",
  neon_delta_straps: "Neon Delta Straps",
  pro_trail_boots: "Pro Trail Boots",
  snow_delta_straps: "Snow Delta Straps",
  sunny_climbing_shoes: "Sunny Climbing Shoes",
  trail_boots: "Trail Boots",
  full_moon_glasses: "Full Moon Glasses",
  hickory_work_cap: "Hickory Work Cap",
  "long-billed_cap": "Long-Billed Cap",
  paisley_bandana: "Paisley Bandana",
  "two-stripe_mesh": "Two-Stripe Mesh",
  woolly_urchins_classic: "Woolly Urchins Classic",
  chili_octo_aloha: "Chili Octo Aloha",
  "krak-on_528": "Krak-On 528",
  missus_shrug_tee: "Missus Shrug Tee",
  mister_shrug_tee: "Mister Shrug Tee",
  octobowler_shirt: "Octobowler Shirt",
  "rainy-day_tee": "Rainy-Day Tee",
  rodeo_shirt: "Rodeo Shirt",
  "squid-pattern_waistcoat": "Squid-Pattern Waistcoat",
  squidstar_waistcoat: "Squidstar Waistcoat",
  "sunny-day_tee": "Sunny-Day Tee",
  banana_basics: "Banana Basics",
  "blue_slip-ons": "Blue Slip-Ons",
  blueberry_casuals: "Blueberry Casuals",
  choco_clogs: "Choco Clogs",
  clownfish_basics: "Clownfish Basics",
  cream_basics: "Cream Basics",
  "cream_hi-tops": "Cream Hi-Tops",
  "hunter_hi-tops": "Hunter Hi-Tops",
  "midnight_slip-ons": "Midnight Slip-Ons",
  oyster_clogs: "Oyster Clogs",
  plum_casuals: "Plum Casuals",
  "polka-dot_slip-ons": "Polka-dot Slip-Ons",
  "red_hi-tops": "Red Hi-Tops",
  "red_slip-ons": "Red Slip-Ons",
  "squid-stitch_slip-ons": "Squid-Stitch Slip-Ons",
  "truffle_canvas_hi-tops": "Truffle Canvas Hi-Tops",
  "18k_aviators": "18K Aviators",
  sv925_circle_shades: "SV925 Circle Shades",
  black_baseball_ls: "Black Baseball LS",
  black_inky_rider: "Black Inky Rider",
  black_urchin_rock_tee: "Black Urchin Rock Tee",
  chirpy_chips_band_tee: "Chirpy Chips Band Tee",
  hightide_era_band_tee: "Hightide Era Band Tee",
  lumberjack_shirt: "Lumberjack Shirt",
  rockenberg_black: "Rockenberg Black",
  rockenberg_white: "Rockenberg White",
  "round-collar_shirt": "Round-Collar Shirt",
  squid_squad_band_tee: "Squid Squad Band Tee",
  vintage_check_shirt: "Vintage Check Shirt",
  wet_floor_band_tee: "Wet Floor Band Tee",
  white_baseball_ls: "White Baseball LS",
  white_inky_rider: "White Inky Rider",
  white_urchin_rock_tee: "White Urchin Rock Tee",
  blue_moto_boots: "Blue Moto Boots",
  cherry_kicks: "Cherry Kicks",
  deepsea_leather_boots: "Deepsea Leather Boots",
  "gray_yellow-soled_wingtips": "Gray Yellow-Soled Wingtips",
  inky_kid_clams: "Inky Kid Clams",
  kid_clams: "Kid Clams",
  moto_boots: "Moto Boots",
  "navy_red-soled_wingtips": "Navy Red-Soled Wingtips",
  "new-leaf_leather_boots": "New-Leaf Leather Boots",
  pearl_punk_crowns: "Pearl Punk Crowns",
  punk_blacks: "Punk Blacks",
  punk_cherries: "Punk Cherries",
  punk_whites: "Punk Whites",
  punk_yellows: "Punk Yellows",
  red_work_boots: "Red Work Boots",
  roasted_brogues: "Roasted Brogues",
  sennyu_inksoles: "Sennyu Inksoles",
  smoky_wingtips: "Smoky Wingtips",
  squink_wingtips: "Squink Wingtips",
  tan_work_boots: "Tan Work Boots",
  turquoise_kicks: "Turquoise Kicks",
  white_kicks: "White Kicks",
  bike_helmet: "Bike Helmet",
  classic_straw_boater: "Classic Straw Boater",
  "do-rag,_cap,_&_glasses": "Do-Rag, Cap, & Glasses",
  hothouse_hat: "Hothouse Hat",
  jellyvader_cap: "Jellyvader Cap",
  patched_hat: "Patched Hat",
  skate_helmet: "Skate Helmet",
  sneaky_beanie: "Sneaky Beanie",
  sporty_bobble_hat: "Sporty Bobble Hat",
  squid_nordic: "Squid Nordic",
  "squid-stitch_cap": "Squid-Stitch Cap",
  squidvader_cap: "Squidvader Cap",
  straw_boater: "Straw Boater",
  streetstyle_cap: "Streetstyle Cap",
  urchins_cap: "Urchins Cap",
  visor_skate_helmet: "Visor Skate Helmet",
  black_hoodie: "Black Hoodie",
  "dots-on-dots_shirt": "Dots-On-Dots Shirt",
  firewave_tee: "Firewave Tee",
  grape_tee: "Grape Tee",
  gray_hoodie: "Gray Hoodie",
  hothouse_hoodie: "Hothouse Hoodie",
  icewave_tee: "Icewave Tee",
  mint_tee: "Mint Tee",
  pearl_tee: "Pearl Tee",
  reggae_tee: "Reggae Tee",
  "squid-stitch_tee": "Squid-Stitch Tee",
  bobble_hat: "Bobble Hat",
  "half-rim_glasses": "Half-Rim Glasses",
  "house-tag_denim_cap": "House-Tag Denim Cap",
  pilot_hat: "Pilot Hat",
  retro_specs: "Retro Specs",
  sennyu_bon_bon_beanie: "Sennyu Bon Bon Beanie",
  sennyu_specs: "Sennyu Specs",
  striped_beanie: "Striped Beanie",
  "baby-jelly_shirt": "Baby-Jelly Shirt",
  "baby-jelly_shirt_&_tie": "Baby-Jelly Shirt & Tie",
  gray_college_sweat: "Gray College Sweat",
  green_cardigan: "Green Cardigan",
  "lime_easy-stripe_shirt": "Lime Easy-Stripe Shirt",
  linen_shirt: "Linen Shirt",
  navy_college_sweat: "Navy College Sweat",
  navy_striped_ls: "Navy Striped LS",
  orange_cardigan: "Orange Cardigan",
  "pink_easy-stripe_shirt": "Pink Easy-Stripe Shirt",
  pink_hoodie: "Pink Hoodie",
  "pirate-stripe_tee": "Pirate-Stripe Tee",
  sage_polo: "Sage Polo",
  "sailor-stripe_tee": "Sailor-Stripe Tee",
  "shirt_&_tie": "Shirt & Tie",
  shirt_with_blue_hoodie: "Shirt with Blue Hoodie",
  "shrimp-pink_polo": "Shrimp-Pink Polo",
  striped_shirt: "Striped Shirt",
  varsity_baseball_ls: "Varsity Baseball LS",
  "whale-knit_sweater": "Whale-Knit Sweater",
  white_shirt: "White Shirt",
  white_striped_ls: "White Striped LS",
  green_laceups: "Green Laceups",
  hunting_boots: "Hunting Boots",
  mawcasins: "Mawcasins",
  piranha_moccasins: "Piranha Moccasins",
  shark_moccasins: "Shark Moccasins",
  strapping_reds: "Strapping Reds",
  strapping_whites: "Strapping Whites",
  "tea-green_hunting_boots": "Tea-Green Hunting Boots",
  anglerfish_mask: "Anglerfish Mask",
  bucket_hat: "Bucket Hat",
  "eel-cake_hat": "Eel-Cake Hat",
  festive_party_cone: "Festive Party Cone",
  hockey_mask: "Hockey Mask",
  koshien_bandana: "Koshien Bandana",
  kyonshi_hat: "Kyonshi Hat",
  lil_devil_horns: "Li'l Devil Horns",
  "mecha_head_-_htr": "Mecha Head - HTR",
  new_years_glasses_dx: "New Year's Glasses DX",
  painters_mask: "Painter's Mask",
  squid_facemask: "Squid Facemask",
  twisty_headband: "Twisty Headband",
  white_headband: "White Headband",
  jetflame_crest: "Jetflame Crest",
  fierce_fishskull: "Fierce Fishskull",
  hivemind_antenna: "Hivemind Antenna",
  eye_of_justice: "Eye of Justice",
  anchor_sweat: "Anchor Sweat",
  basic_tee: "Basic Tee",
  black_anchor_tee: "Black Anchor Tee",
  black_layered_ls: "Black Layered LS",
  black_tee: "Black Tee",
  "black_v-neck_tee": "Black V-Neck Tee",
  camo_layered_ls: "Camo Layered LS",
  friend_tee: "Friend Tee",
  "green_v-neck_limited_tee": "Green V-Neck Limited Tee",
  layered_anchor_ls: "Layered Anchor LS",
  league_tee: "League Tee",
  "mecha_body_-_akm": "Mecha Body - AKM",
  octo_support_hoodie: "Octo Support Hoodie",
  "red_v-neck_limited_tee": "Red V-Neck Limited Tee",
  retro_sweat: "Retro Sweat",
  splatfest_tee: "Splatfest Tee",
  squid_yellow_layered_ls: "Squid Yellow Layered LS",
  squidmark_ls: "Squidmark LS",
  squidmark_sweat: "Squidmark Sweat",
  swc_logo_tee: "SWC Logo Tee",
  white_anchor_tee: "White Anchor Tee",
  white_layered_ls: "White Layered LS",
  white_ls: "White LS",
  white_tee: "White Tee",
  "white_v-neck_tee": "White V-Neck Tee",
  yellow_layered_ls: "Yellow Layered LS",
  "mecha_legs_-_lbs": "Mecha Legs - LBS",
  takoroka_mesh: "Takoroka Mesh",
  takoroka_visor: "Takoroka Visor",
  choco_layered_ls: "Choco Layered LS",
  fc_albacore: "FC Albacore",
  gray_vector_tee: "Gray Vector Tee",
  layered_vector_ls: "Layered Vector LS",
  purple_camo_ls: "Purple Camo LS",
  red_vector_tee: "Red Vector Tee",
  slipstream_united: "Slipstream United",
  striped_rugby: "Striped Rugby",
  takoroka_crazy_baseball_ls: "Takoroka Crazy Baseball LS",
  takoroka_galactic_tie_dye: "Takoroka Galactic Tie Dye",
  takoroka_jersey: "Takoroka Jersey",
  takoroka_nylon_vintage: "Takoroka Nylon Vintage",
  takoroka_rainbow_tie_dye: "Takoroka Rainbow Tie Dye",
  takoroka_windcrusher: "Takoroka Windcrusher",
  tricolor_rugby: "Tricolor Rugby",
  athletic_arrows: "Athletic Arrows",
  blue_power_stripes: "Blue Power Stripes",
  crazy_arrows: "Crazy Arrows",
  le_soccer_shoes: "LE Soccer Shoes",
  "new-day_arrows": "New-Day Arrows",
  orange_arrows: "Orange Arrows",
  "orca_hi-tops": "Orca Hi-Tops",
  "orca_passion_hi-tops": "Orca Passion Hi-Tops",
  "orca_woven_hi-tops": "Orca Woven Hi-Tops",
  red_power_stripes: "Red Power Stripes",
  soccer_shoes: "Soccer Shoes",
  "sunset_orca_hi-tops": "Sunset Orca Hi-Tops",
  trooper_power_stripes: "Trooper Power Stripes",
  white_arrows: "White Arrows",
  cycle_king_cap: "Cycle King Cap",
  fake_contacts: "Fake Contacts",
  green_novelty_visor: "Green Novelty Visor",
  orange_novelty_visor: "Orange Novelty Visor",
  pink_novelty_visor: "Pink Novelty Visor",
  purple_novelty_visor: "Purple Novelty Visor",
  soccer_headband: "Soccer Headband",
  sun_visor: "Sun Visor",
  tennis_headband: "Tennis Headband",
  black_squideye: "Black Squideye",
  blue_tentatek_tee: "Blue Tentatek Tee",
  cycle_king_jersey: "Cycle King Jersey",
  "lob-stars_jersey": "Lob-Stars Jersey",
  "part-time_pirate": "Part-Time Pirate",
  red_tentatek_tee: "Red Tentatek Tee",
  silver_tentatek_vest: "Silver Tentatek Vest",
  "sky-blue_squideye": "Sky-Blue Squideye",
  tentatek_slogan_tee: "Tentatek Slogan Tee",
  "amber_sea_slug_hi-tops": "Amber Sea Slug Hi-Tops",
  black_norimaki_750s: "Black Norimaki 750s",
  black_trainers: "Black Trainers",
  blue_iromaki_750s: "Blue Iromaki 750s",
  blue_sea_slugs: "Blue Sea Slugs",
  canary_trainers: "Canary Trainers",
  cyan_trainers: "Cyan Trainers",
  "gray_sea-slug_hi-tops": "Gray Sea-Slug Hi-Tops",
  green_iromaki_750s: "Green Iromaki 750s",
  icy_down_boots: "Icy Down Boots",
  neon_sea_slugs: "Neon Sea Slugs",
  orange_iromaki_750s: "Orange Iromaki 750s",
  pink_trainers: "Pink Trainers",
  purple_iromaki_750s: "Purple Iromaki 750s",
  purple_sea_slugs: "Purple Sea Slugs",
  red_iromaki_750s: "Red Iromaki 750s",
  red_sea_slugs: "Red Sea Slugs",
  "red-mesh_sneakers": "Red-Mesh Sneakers",
  sea_slug_volt_95s: "Sea Slug Volt 95s",
  sesame_salt_270s: "Sesame Salt 270s",
  snowy_down_boots: "Snowy Down Boots",
  violet_trainers: "Violet Trainers",
  white_norimaki_750s: "White Norimaki 750s",
  yellow_iromaki_750s: "Yellow Iromaki 750s",
  "yellow-mesh_sneakers": "Yellow-Mesh Sneakers",
  face_visor: "Face Visor",
  "ink-guard_goggles": "Ink-Guard Goggles",
  toni_kensa_goggles: "Toni Kensa Goggles",
  dark_bomber_jacket: "Dark Bomber Jacket",
  front_zip_vest: "Front Zip Vest",
  "half-sleeve_sweater": "Half-Sleeve Sweater",
  "ink-wash_shirt": "Ink-Wash Shirt",
  inkfall_shirt: "Inkfall Shirt",
  kensa_coat: "Kensa Coat",
  "kung-fu_zip-up": "Kung-Fu Zip-Up",
  light_bomber_jacket: "Light Bomber Jacket",
  negative_longcuff_sweater: "Negative Longcuff Sweater",
  "panda_kung-fu_zip-up": "Panda Kung-Fu Zip-Up",
  positive_longcuff_sweater: "Positive Longcuff Sweater",
  pullover_coat: "Pullover Coat",
  short_knit_layers: "Short Knit Layers",
  toni_k_baseball_jersey: "Toni K. Baseball Jersey",
  "arrow_pull-ons": "Arrow Pull-Ons",
  "toni_kensa_black_hi-tops": "Toni Kensa Black Hi-Tops",
  toni_kensa_soccer_shoes: "Toni Kensa Soccer Shoes",
  backwards_cap: "Backwards Cap",
  black_arrowbands: "Black Arrowbands",
  double_egg_shades: "Double Egg Shades",
  "five-panel_cap": "Five-Panel Cap",
  jogging_headband: "Jogging Headband",
  matte_bike_helmet: "Matte Bike Helmet",
  mtb_helmet: "MTB Helmet",
  tinted_shades: "Tinted Shades",
  white_arrowbands: "White Arrowbands",
  zekko_cap: "Zekko Cap",
  zekko_mesh: "Zekko Mesh",
  birded_corduroy_jacket: "Birded Corduroy Jacket",
  black_ls: "Black LS",
  black_polo: "Black Polo",
  "deep-octo_satin_jacket": "Deep-Octo Satin Jacket",
  gray_mixed_shirt: "Gray Mixed Shirt",
  "green-check_shirt": "Green-Check Shirt",
  logo_aloha_shirt: "Logo Aloha Shirt",
  olive_zekko_parka: "Olive Zekko Parka",
  "red-check_shirt": "Red-Check Shirt",
  reel_sweat: "Reel Sweat",
  squid_satin_jacket: "Squid Satin Jacket",
  tumeric_zekko_coat: "Tumeric Zekko Coat",
  varsity_jacket: "Varsity Jacket",
  zapfish_satin_jacket: "Zapfish Satin Jacket",
  zekko_baseball_ls: "Zekko Baseball LS",
  zekko_hoodie: "Zekko Hoodie",
  zekko_jade_coat: "Zekko Jade Coat",
  zekko_long_carrot_tee: "Zekko Long Carrot Tee",
  zekko_long_radish_tee: "Zekko Long Radish Tee",
  zekko_redleaf_coat: "Zekko Redleaf Coat",
  "black_flip-flops": "Black Flip-Flops",
  "blue_lo-tops": "Blue Lo-Tops",
  "le_lo-tops": "LE Lo-Tops",
  "marination_lace-ups": "Marination Lace-Ups",
  "orange_lo-tops": "Orange Lo-Tops",
  "pearl-scout_lace-ups": "Pearl-Scout Lace-Ups",
  "suede_gray_lace-ups": "Suede Gray Lace-Ups",
  "suede_marine_lace-ups": "Suede Marine Lace-Ups",
  "suede_nation_lace-ups": "Suede Nation Lace-Ups",
  "b-ball_headband": "B-ball Headband",
  cycling_cap: "Cycling Cap",
  golf_visor: "Golf Visor",
  squash_headband: "Squash Headband",
  swim_goggles: "Swim Goggles",
  "b-ball_jersey_(away)": "B-ball Jersey (Away)",
  "b-ball_jersey_(home)": "B-ball Jersey (Home)",
  cycling_shirt: "Cycling Shirt",
  dakro_golden_tee: "Dakro Golden Tee",
  dakro_nana_tee: "Dakro Nana Tee",
  inkopolis_squaps_jersey: "Inkopolis Squaps Jersey",
  navy_deca_logo_tee: "Navy Deca Logo Tee",
  retro_gamer_jersey: "Retro Gamer Jersey",
  school_jersey: "School Jersey",
  urchins_jersey: "Urchins Jersey",
  white_deca_logo_tee: "White Deca Logo Tee",
  zink_layered_ls: "Zink Layered LS",
  zink_ls: "Zink LS",
  black_dakroniks: "Black Dakroniks",
  black_seahorses: "Black Seahorses",
  blue_laceless_dakroniks: "Blue Laceless Dakroniks",
  chocolate_dakroniks: "Chocolate Dakroniks",
  "gold_hi-horses": "Gold Hi-Horses",
  mint_dakroniks: "Mint Dakroniks",
  "purple_hi-horses": "Purple Hi-Horses",
  "red_hi-horses": "Red Hi-Horses",
  white_laceless_dakroniks: "White Laceless Dakroniks",
  white_seahorses: "White Seahorses",
  yellow_seahorses: "Yellow Seahorses",
  "zombie_hi-horses": "Zombie Hi-Horses",
} as const;
