import { t } from "@lingui/macro";

export const stages = [
  t`The Reef`,
  t`Musselforge Fitness`,
  t`Starfish Mainstage`,
  t`Humpback Pump Track`,
  t`Inkblot Art Academy`,
  t`Sturgeon Shipyard`,
  t`Moray Towers`,
  t`Port Mackerel`,
  t`Manta Maria`,
  t`Kelp Dome`,
  t`Snapper Canal`,
  t`Blackbelly Skatepark`,
  t`MakoMart`,
  t`Walleye Warehouse`,
  t`Shellendorf Institute`,
  t`Arowana Mall`,
  t`Goby Arena`,
  t`Piranha Pit`,
  t`Camp Triggerfish`,
  t`Wahoo World`,
  t`New Albacore Hotel`,
  t`Ancho-V Games`,
  t`Skipper Pavilion`,
] as const;
