export const codeToWeapon = {
  "sploosh-o-matic": "Sploosh-o-matic",
  "neo_sploosh-o-matic": "Neo Sploosh-o-matic",
  "sploosh-o-matic_7": "Sploosh-o-matic 7",
  splattershot_jr: "Splattershot Jr.",
  custom_splattershot_jr: "Custom Splattershot Jr.",
  kensa_splattershot_jr: "Kensa Splattershot Jr.",
  "splash-o-matic": "Splash-o-matic",
  "neo_splash-o-matic": "Neo Splash-o-matic",
  aerospray_mg: "Aerospray MG",
  aerospray_rg: "Aerospray RG",
  aerospray_pg: "Aerospray PG",
  splattershot: "Splattershot",
  hero_shot_replica: "Hero Shot Replica",
  tentatek_splattershot: "Tentatek Splattershot",
  octo_shot_replica: "Octo Shot Replica",
  kensa_splattershot: "Kensa Splattershot",
  "52_gal": ".52 Gal",
  "52_gal_deco": ".52 Gal Deco",
  kensa_52_gal: "Kensa .52 Gal",
  "n-zap_85": "N-ZAP '85",
  "n-zap_89": "N-ZAP '89",
  "n-zap_83": "N-ZAP '83",
  splattershot_pro: "Splattershot Pro",
  forge_splattershot_pro: "Forge Splattershot Pro",
  kensa_splattershot_pro: "Kensa Splattershot Pro",
  "96_gal": ".96 Gal",
  "96_gal_deco": ".96 Gal Deco",
  jet_squelcher: "Jet Squelcher",
  custom_jet_squelcher: "Custom Jet Squelcher",
  "l-3_nozzlenose": "L-3 Nozzlenose",
  "l-3_nozzlenose_d": "L-3 Nozzlenose D",
  "kensa_l-3_nozzlenose": "Kensa L-3 Nozzlenose",
  "h-3_nozzlenose": "H-3 Nozzlenose",
  "h-3_nozzlenose_d": "H-3 Nozzlenose D",
  "cherry_h-3_nozzlenose": "Cherry H-3 Nozzlenose",
  squeezer: "Squeezer",
  foil_squeezer: "Foil Squeezer",
  luna_blaster: "Luna Blaster",
  luna_blaster_neo: "Luna Blaster Neo",
  kensa_luna_blaster: "Kensa Luna Blaster",
  blaster: "Blaster",
  hero_blaster_replica: "Hero Blaster Replica",
  custom_blaster: "Custom Blaster",
  range_blaster: "Range Blaster",
  custom_range_blaster: "Custom Range Blaster",
  grim_range_blaster: "Grim Range Blaster",
  rapid_blaster: "Rapid Blaster",
  rapid_blaster_deco: "Rapid Blaster Deco",
  kensa_rapid_blaster: "Kensa Rapid Blaster",
  rapid_blaster_pro: "Rapid Blaster Pro",
  rapid_blaster_pro_deco: "Rapid Blaster Pro Deco",
  clash_blaster: "Clash Blaster",
  clash_blaster_neo: "Clash Blaster Neo",
  carbon_roller: "Carbon Roller",
  carbon_roller_deco: "Carbon Roller Deco",
  splat_roller: "Splat Roller",
  hero_roller_replica: "Hero Roller Replica",
  "krak-on_splat_roller": "Krak-On Splat Roller",
  kensa_splat_roller: "Kensa Splat Roller",
  dynamo_roller: "Dynamo Roller",
  gold_dynamo_roller: "Gold Dynamo Roller",
  kensa_dynamo_roller: "Kensa Dynamo Roller",
  flingza_roller: "Flingza Roller",
  foil_flingza_roller: "Foil Flingza Roller",
  inkbrush: "Inkbrush",
  inkbrush_nouveau: "Inkbrush Nouveau",
  permanent_inkbrush: "Permanent Inkbrush",
  octobrush: "Octobrush",
  herobrush_replica: "Herobrush Replica",
  octobrush_nouveau: "Octobrush Nouveau",
  kensa_octobrush: "Kensa Octobrush",
  classic_squiffer: "Classic Squiffer",
  new_squiffer: "New Squiffer",
  fresh_squiffer: "Fresh Squiffer",
  splat_charger: "Splat Charger",
  hero_charger_replica: "Hero Charger Replica",
  firefin_splat_charger: "Firefin Splat Charger",
  kensa_charger: "Kensa Charger",
  splatterscope: "Splatterscope",
  firefin_splatterscope: "Firefin Splatterscope",
  kensa_splatterscope: "Kensa Splatterscope",
  "e-liter_4k": "E-liter 4K",
  "custom_e-liter_4k": "Custom E-liter 4K",
  "e-liter_4k_scope": "E-liter 4K Scope",
  "custom_e-liter_4k_scope": "Custom E-liter 4K Scope",
  bamboozler_14_mk_i: "Bamboozler 14 Mk I",
  bamboozler_14_mk_ii: "Bamboozler 14 Mk II",
  bamboozler_14_mk_iii: "Bamboozler 14 Mk III",
  goo_tuber: "Goo Tuber",
  custom_goo_tuber: "Custom Goo Tuber",
  slosher: "Slosher",
  hero_slosher_replica: "Hero Slosher Replica",
  slosher_deco: "Slosher Deco",
  soda_slosher: "Soda Slosher",
  "tri-slosher": "Tri-Slosher",
  "tri-slosher_nouveau": "Tri-Slosher Nouveau",
  sloshing_machine: "Sloshing Machine",
  sloshing_machine_neo: "Sloshing Machine Neo",
  kensa_sloshing_machine: "Kensa Sloshing Machine",
  bloblobber: "Bloblobber",
  bloblobber_deco: "Bloblobber Deco",
  explosher: "Explosher",
  custom_explosher: "Custom Explosher",
  mini_splatling: "Mini Splatling",
  zink_mini_splatling: "Zink Mini Splatling",
  kensa_mini_splatling: "Kensa Mini Splatling",
  heavy_splatling: "Heavy Splatling",
  hero_splatling_replica: "Hero Splatling Replica",
  heavy_splatling_deco: "Heavy Splatling Deco",
  heavy_splatling_remix: "Heavy Splatling Remix",
  hydra_splatling: "Hydra Splatling",
  custom_hydra_splatling: "Custom Hydra Splatling",
  ballpoint_splatling: "Ballpoint Splatling",
  ballpoint_splatling_nouveau: "Ballpoint Splatling Nouveau",
  nautilus_47: "Nautilus 47",
  nautilus_79: "Nautilus 79",
  dapple_dualies: "Dapple Dualies",
  dapple_dualies_nouveau: "Dapple Dualies Nouveau",
  clear_dapple_dualies: "Clear Dapple Dualies",
  splat_dualies: "Splat Dualies",
  hero_dualies_replicas: "Hero Dualie Replicas",
  enperry_splat_dualies: "Enperry Splat Dualies",
  kensa_splat_dualies: "Kensa Splat Dualies",
  glooga_dualies: "Glooga Dualies",
  glooga_dualies_deco: "Glooga Dualies Deco",
  kensa_glooga_dualies: "Kensa Glooga Dualies",
  dualie_squelchers: "Dualie Squelchers",
  custom_dualie_squelchers: "Custom Dualie Squelchers",
  dark_tetra_dualies: "Dark Tetra Dualies",
  light_tetra_dualies: "Light Tetra Dualies",
  splat_brella: "Splat Brella",
  hero_brella_replica: "Hero Brella Replica",
  sorella_brella: "Sorella Brella",
  tenta_brella: "Tenta Brella",
  tenta_sorella_brella: "Tenta Sorella Brella",
  tenta_camo_brella: "Tenta Camo Brella",
  undercover_brella: "Undercover Brella",
  undercover_sorella_brella: "Undercover Sorella Brella",
  kensa_undercover_brella: "Kensa Undercover Brella",
} as const;

export const weaponToCode = {
  "Sploosh-o-matic": "sploosh-o-matic",
  "Neo Sploosh-o-matic": "neo_sploosh-o-matic",
  "Sploosh-o-matic 7": "sploosh-o-matic_7",
  "Splattershot Jr.": "splattershot_jr",
  "Custom Splattershot Jr.": "custom_splattershot_jr",
  "Kensa Splattershot Jr.": "kensa_splattershot_jr",
  "Splash-o-matic": "splash-o-matic",
  "Neo Splash-o-matic": "neo_splash-o-matic",
  "Aerospray MG": "aerospray_mg",
  "Aerospray RG": "aerospray_rg",
  "Aerospray PG": "aerospray_pg",
  Splattershot: "splattershot",
  "Hero Shot Replica": "hero_shot_replica",
  "Tentatek Splattershot": "tentatek_splattershot",
  "Octo Shot Replica": "octo_shot_replica",
  "Kensa Splattershot": "kensa_splattershot",
  ".52 Gal": "52_gal",
  ".52 Gal Deco": "52_gal_deco",
  "Kensa .52 Gal": "kensa_52_gal",
  "N-ZAP '85": "n-zap_85",
  "N-ZAP '89": "n-zap_89",
  "N-ZAP '83": "n-zap_83",
  "Splattershot Pro": "splattershot_pro",
  "Forge Splattershot Pro": "forge_splattershot_pro",
  "Kensa Splattershot Pro": "kensa_splattershot_pro",
  ".96 Gal": "96_gal",
  ".96 Gal Deco": "96_gal_deco",
  "Jet Squelcher": "jet_squelcher",
  "Custom Jet Squelcher": "custom_jet_squelcher",
  "L-3 Nozzlenose": "l-3_nozzlenose",
  "L-3 Nozzlenose D": "l-3_nozzlenose_d",
  "Kensa L-3 Nozzlenose": "kensa_l-3_nozzlenose",
  "H-3 Nozzlenose": "h-3_nozzlenose",
  "H-3 Nozzlenose D": "h-3_nozzlenose_d",
  "Cherry H-3 Nozzlenose": "cherry_h-3_nozzlenose",
  Squeezer: "squeezer",
  "Foil Squeezer": "foil_squeezer",
  "Luna Blaster": "luna_blaster",
  "Luna Blaster Neo": "luna_blaster_neo",
  "Kensa Luna Blaster": "kensa_luna_blaster",
  Blaster: "blaster",
  "Hero Blaster Replica": "hero_blaster_replica",
  "Custom Blaster": "custom_blaster",
  "Range Blaster": "range_blaster",
  "Custom Range Blaster": "custom_range_blaster",
  "Grim Range Blaster": "grim_range_blaster",
  "Rapid Blaster": "rapid_blaster",
  "Rapid Blaster Deco": "rapid_blaster_deco",
  "Kensa Rapid Blaster": "kensa_rapid_blaster",
  "Rapid Blaster Pro": "rapid_blaster_pro",
  "Rapid Blaster Pro Deco": "rapid_blaster_pro_deco",
  "Clash Blaster": "clash_blaster",
  "Clash Blaster Neo": "clash_blaster_neo",
  "Carbon Roller": "carbon_roller",
  "Carbon Roller Deco": "carbon_roller_deco",
  "Splat Roller": "splat_roller",
  "Hero Roller Replica": "hero_roller_replica",
  "Krak-On Splat Roller": "krak-on_splat_roller",
  "Kensa Splat Roller": "kensa_splat_roller",
  "Dynamo Roller": "dynamo_roller",
  "Gold Dynamo Roller": "gold_dynamo_roller",
  "Kensa Dynamo Roller": "kensa_dynamo_roller",
  "Flingza Roller": "flingza_roller",
  "Foil Flingza Roller": "foil_flingza_roller",
  Inkbrush: "inkbrush",
  "Inkbrush Nouveau": "inkbrush_nouveau",
  "Permanent Inkbrush": "permanent_inkbrush",
  Octobrush: "octobrush",
  "Herobrush Replica": "herobrush_replica",
  "Octobrush Nouveau": "octobrush_nouveau",
  "Kensa Octobrush": "kensa_octobrush",
  "Classic Squiffer": "classic_squiffer",
  "New Squiffer": "new_squiffer",
  "Fresh Squiffer": "fresh_squiffer",
  "Splat Charger": "splat_charger",
  "Hero Charger Replica": "hero_charger_replica",
  "Firefin Splat Charger": "firefin_splat_charger",
  "Kensa Charger": "kensa_charger",
  Splatterscope: "splatterscope",
  "Firefin Splatterscope": "firefin_splatterscope",
  "Kensa Splatterscope": "kensa_splatterscope",
  "E-liter 4K": "e-liter_4k",
  "Custom E-liter 4K": "custom_e-liter_4k",
  "E-liter 4K Scope": "e-liter_4k_scope",
  "Custom E-liter 4K Scope": "custom_e-liter_4k_scope",
  "Bamboozler 14 Mk I": "bamboozler_14_mk_i",
  "Bamboozler 14 Mk II": "bamboozler_14_mk_ii",
  "Bamboozler 14 Mk III": "bamboozler_14_mk_iii",
  "Goo Tuber": "goo_tuber",
  "Custom Goo Tuber": "custom_goo_tuber",
  Slosher: "slosher",
  "Hero Slosher Replica": "hero_slosher_replica",
  "Slosher Deco": "slosher_deco",
  "Soda Slosher": "soda_slosher",
  "Tri-Slosher": "tri-slosher",
  "Tri-Slosher Nouveau": "tri-slosher_nouveau",
  "Sloshing Machine": "sloshing_machine",
  "Sloshing Machine Neo": "sloshing_machine_neo",
  "Kensa Sloshing Machine": "kensa_sloshing_machine",
  Bloblobber: "bloblobber",
  "Bloblobber Deco": "bloblobber_deco",
  Explosher: "explosher",
  "Custom Explosher": "custom_explosher",
  "Mini Splatling": "mini_splatling",
  "Zink Mini Splatling": "zink_mini_splatling",
  "Kensa Mini Splatling": "kensa_mini_splatling",
  "Heavy Splatling": "heavy_splatling",
  "Hero Splatling Replica": "hero_splatling_replica",
  "Heavy Splatling Deco": "heavy_splatling_deco",
  "Heavy Splatling Remix": "heavy_splatling_remix",
  "Hydra Splatling": "hydra_splatling",
  "Custom Hydra Splatling": "custom_hydra_splatling",
  "Ballpoint Splatling": "ballpoint_splatling",
  "Ballpoint Splatling Nouveau": "ballpoint_splatling_nouveau",
  "Nautilus 47": "nautilus_47",
  "Nautilus 79": "nautilus_79",
  "Dapple Dualies": "dapple_dualies",
  "Dapple Dualies Nouveau": "dapple_dualies_nouveau",
  "Clear Dapple Dualies": "clear_dapple_dualies",
  "Splat Dualies": "splat_dualies",
  "Hero Dualie Replicas": "hero_dualies_replicas",
  "Enperry Splat Dualies": "enperry_splat_dualies",
  "Kensa Splat Dualies": "kensa_splat_dualies",
  "Glooga Dualies": "glooga_dualies",
  "Glooga Dualies Deco": "glooga_dualies_deco",
  "Kensa Glooga Dualies": "kensa_glooga_dualies",
  "Dualie Squelchers": "dualie_squelchers",
  "Custom Dualie Squelchers": "custom_dualie_squelchers",
  "Dark Tetra Dualies": "dark_tetra_dualies",
  "Light Tetra Dualies": "light_tetra_dualies",
  "Splat Brella": "splat_brella",
  "Hero Brella Replica": "hero_brella_replica",
  "Sorella Brella": "sorella_brella",
  "Tenta Brella": "tenta_brella",
  "Tenta Sorella Brella": "tenta_sorella_brella",
  "Tenta Camo Brella": "tenta_camo_brella",
  "Undercover Brella": "undercover_brella",
  "Undercover Sorella Brella": "undercover_sorella_brella",
  "Kensa Undercover Brella": "kensa_undercover_brella",
};
