export const weaponParams = {
	mainWeapons: {
		"0": {
			SpecialPoint: 180,
			subWeaponId: 6,
			specialWeaponId: 11,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.08,
			DamageParam_ValueMax: 380,
			DamageParam_ValueMin: 190,
			Jump_DegSwerve: 18,
			Stand_DegSwerve: 12,
			InkRecoverStop: 15,
			InkConsume: 0.008,
		},
		"1": {
			SpecialPoint: 170,
			subWeaponId: 8,
			specialWeaponId: 9,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.08,
			DamageParam_ValueMax: 380,
			DamageParam_ValueMin: 190,
			Jump_DegSwerve: 18,
			Stand_DegSwerve: 12,
			InkRecoverStop: 15,
			InkConsume: 0.008,
		},
		"10": {
			SpecialPoint: 180,
			subWeaponId: 0,
			specialWeaponId: 2,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.076,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Jump_DegSwerve: 15,
			Stand_DegSwerve: 12,
			InkRecoverStop: 15,
			InkConsume: 0.0043,
		},
		"11": {
			SpecialPoint: 190,
			subWeaponId: 13,
			specialWeaponId: 7,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.076,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Jump_DegSwerve: 15,
			Stand_DegSwerve: 12,
			InkRecoverStop: 15,
			InkConsume: 0.0043,
		},
		"20": {
			SpecialPoint: 200,
			subWeaponId: 2,
			specialWeaponId: 12,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Jump_DegSwerve: 0,
			Stand_DegSwerve: 0,
			InkConsume: 0.008,
		},
		"21": {
			SpecialPoint: 200,
			subWeaponId: 1,
			specialWeaponId: 14,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Jump_DegSwerve: 0,
			Stand_DegSwerve: 0,
			InkConsume: 0.008,
		},
		"30": {
			SpecialPoint: 180,
			subWeaponId: 5,
			specialWeaponId: 13,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 240,
			DamageParam_ValueMin: 120,
			Jump_DegSwerve: 16,
			Stand_DegSwerve: 13,
			InkRecoverStop: 15,
			InkConsume: 0.005,
		},
		"31": {
			SpecialPoint: 190,
			subWeaponId: 3,
			specialWeaponId: 6,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 240,
			DamageParam_ValueMin: 120,
			Jump_DegSwerve: 16,
			Stand_DegSwerve: 13,
			InkRecoverStop: 15,
			InkConsume: 0.005,
		},
		"40": {
			SpecialPoint: 210,
			subWeaponId: 1,
			specialWeaponId: 1,
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 360,
			DamageParam_ValueMin: 180,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 5,
			InkConsume: 0.0092,
		},
		"41": {
			SpecialPoint: 190,
			subWeaponId: 0,
			specialWeaponId: 14,
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 360,
			DamageParam_ValueMin: 180,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 5,
			InkConsume: 0.0092,
		},
		"45": {
			SpecialPoint: 210,
			subWeaponId: 1,
			specialWeaponId: 1,
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 360,
			DamageParam_ValueMin: 180,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 5,
			InkConsume: 0.0092,
		},
		"46": {
			SpecialPoint: 190,
			subWeaponId: 0,
			specialWeaponId: 14,
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 360,
			DamageParam_ValueMin: 180,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 5,
			InkConsume: 0.0092,
		},
		"47": {
			SpecialPoint: 210,
			subWeaponId: 1,
			specialWeaponId: 1,
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 360,
			DamageParam_ValueMin: 180,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 5,
			InkConsume: 0.0092,
		},
		"50": {
			SpecialPoint: 200,
			subWeaponId: 4,
			specialWeaponId: 9,
			MoveSpeed: 0.06,
			DamageParam_ValueMax: 520,
			DamageParam_ValueMin: 300,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 6,
			InkConsume: 0.013,
		},
		"51": {
			SpecialPoint: 190,
			subWeaponId: 6,
			specialWeaponId: 19,
			MoveSpeed: 0.06,
			DamageParam_ValueMax: 520,
			DamageParam_ValueMin: 300,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 6,
			InkConsume: 0.013,
		},
		"60": {
			SpecialPoint: 200,
			subWeaponId: 1,
			specialWeaponId: 15,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.084,
			DamageParam_ValueMax: 300,
			DamageParam_ValueMin: 150,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 5,
			InkConsume: 0.008,
		},
		"61": {
			SpecialPoint: 170,
			subWeaponId: 7,
			specialWeaponId: 16,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.084,
			DamageParam_ValueMax: 300,
			DamageParam_ValueMin: 150,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 5,
			InkConsume: 0.008,
		},
		"70": {
			SpecialPoint: 180,
			subWeaponId: 12,
			specialWeaponId: 12,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			MoveSpeed: 0.055,
			DamageParam_ValueMax: 450,
			DamageParam_ValueMin: 225,
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 2.7,
			InkConsume: 0.02,
		},
		"71": {
			SpecialPoint: 200,
			subWeaponId: 1,
			specialWeaponId: 6,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			MoveSpeed: 0.055,
			DamageParam_ValueMax: 450,
			DamageParam_ValueMin: 225,
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 2.7,
			InkConsume: 0.02,
		},
		"80": {
			SpecialPoint: 190,
			subWeaponId: 3,
			specialWeaponId: 8,
			MoveSpeed: 0.04,
			DamageParam_ValueMax: 620,
			DamageParam_ValueMin: 350,
			Jump_DegSwerve: 11.3511,
			Stand_DegSwerve: 4,
			InkConsume: 0.023,
		},
		"81": {
			SpecialPoint: 210,
			subWeaponId: 4,
			specialWeaponId: 17,
			MoveSpeed: 0.04,
			DamageParam_ValueMax: 620,
			DamageParam_ValueMin: 350,
			Jump_DegSwerve: 11.3511,
			Stand_DegSwerve: 4,
			InkConsume: 0.023,
		},
		"90": {
			SpecialPoint: 180,
			subWeaponId: 12,
			specialWeaponId: 8,
			MoveSpeed: 0.06,
			DamageParam_ValueMax: 320,
			DamageParam_ValueMin: 160,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 2.5,
			InkConsume: 0.016,
		},
		"91": {
			SpecialPoint: 180,
			subWeaponId: 11,
			specialWeaponId: 5,
			MoveSpeed: 0.06,
			DamageParam_ValueMax: 320,
			DamageParam_ValueMin: 160,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 2.5,
			InkConsume: 0.016,
		},
		"100": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 9,
			MoveSpeed: 0.079,
			DamageParam_ValueMax: 240,
			DamageParam_ValueMin: 120,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 5.5,
			InkConsume: 0.0096,
		},
		"101": {
			SpecialPoint: 210,
			subWeaponId: 10,
			specialWeaponId: 10,
			MoveSpeed: 0.079,
			DamageParam_ValueMax: 240,
			DamageParam_ValueMin: 120,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 5.5,
			InkConsume: 0.0096,
		},
		"200": {
			SpecialPoint: 170,
			subWeaponId: 0,
			specialWeaponId: 3,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
				ReduceJumpSwerveRate: {
					Mid: 0.625,
				},
			},
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.05,
			DamageParam_ValueDirect: 1250,
			BlastParam_DistanceDamage: [
				{
					Damage: 700,
					Distance: 1.5,
				},
				{
					Damage: 500,
					Distance: 3.57,
				},
			],
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 0,
			InkRecoverStop: 55,
			InkConsume: 0.075,
		},
		"201": {
			SpecialPoint: 180,
			subWeaponId: 5,
			specialWeaponId: 11,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
				ReduceJumpSwerveRate: {
					Mid: 0.625,
				},
			},
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.05,
			DamageParam_ValueDirect: 1250,
			BlastParam_DistanceDamage: [
				{
					Damage: 700,
					Distance: 1.5,
				},
				{
					Damage: 500,
					Distance: 3.57,
				},
			],
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 0,
			InkRecoverStop: 55,
			InkConsume: 0.075,
		},
		"205": {
			SpecialPoint: 170,
			subWeaponId: 0,
			specialWeaponId: 3,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
				ReduceJumpSwerveRate: {
					Mid: 0.625,
				},
			},
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.05,
			DamageParam_ValueDirect: 1250,
			BlastParam_DistanceDamage: [
				{
					Damage: 700,
					Distance: 1.5,
				},
				{
					Damage: 500,
					Distance: 3.57,
				},
			],
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 0,
			InkRecoverStop: 55,
			InkConsume: 0.075,
		},
		"210": {
			SpecialPoint: 180,
			subWeaponId: 7,
			specialWeaponId: 2,
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			MoveSpeed: 0.045,
			DamageParam_ValueDirect: 1250,
			BlastParam_DistanceDamage: [
				{
					Damage: 700,
					Distance: 0.94,
				},
				{
					Damage: 500,
					Distance: 3.3,
				},
			],
			Jump_DegSwerve: 10,
			Stand_DegSwerve: 0,
			InkRecoverStop: 57,
			InkConsume: 0.1,
		},
		"211": {
			SpecialPoint: 180,
			subWeaponId: 9,
			specialWeaponId: 18,
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			MoveSpeed: 0.045,
			DamageParam_ValueDirect: 1250,
			BlastParam_DistanceDamage: [
				{
					Damage: 700,
					Distance: 0.94,
				},
				{
					Damage: 500,
					Distance: 3.3,
				},
			],
			Jump_DegSwerve: 10,
			Stand_DegSwerve: 0,
			InkRecoverStop: 57,
			InkConsume: 0.1,
		},
		"220": {
			SpecialPoint: 210,
			subWeaponId: 1,
			specialWeaponId: 7,
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			MoveSpeed: 0.04,
			DamageParam_ValueDirect: 1250,
			BlastParam_DistanceDamage: [
				{
					Damage: 700,
					Distance: 1,
				},
				{
					Damage: 500,
					Distance: 3.5,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 70,
			InkConsume: 0.11,
		},
		"221": {
			SpecialPoint: 200,
			subWeaponId: 0,
			specialWeaponId: 17,
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			MoveSpeed: 0.04,
			DamageParam_ValueDirect: 1250,
			BlastParam_DistanceDamage: [
				{
					Damage: 700,
					Distance: 1,
				},
				{
					Damage: 500,
					Distance: 3.5,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 70,
			InkConsume: 0.11,
		},
		"230": {
			SpecialPoint: 180,
			subWeaponId: 0,
			specialWeaponId: 1,
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.068,
			DamageParam_ValueDirect: 600,
			BlastParam_DistanceDamage: [
				{
					Damage: 300,
					Distance: 1,
				},
				{
					Damage: 300,
					Distance: 4,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 40,
			InkConsume: 0.04,
		},
		"231": {
			SpecialPoint: 170,
			subWeaponId: 6,
			specialWeaponId: 16,
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.068,
			DamageParam_ValueDirect: 600,
			BlastParam_DistanceDamage: [
				{
					Damage: 300,
					Distance: 1,
				},
				{
					Damage: 300,
					Distance: 4,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 40,
			InkConsume: 0.04,
		},
		"240": {
			SpecialPoint: 190,
			subWeaponId: 10,
			specialWeaponId: 14,
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			MoveSpeed: 0.055,
			DamageParam_ValueDirect: 850,
			BlastParam_DistanceDamage: [
				{
					Damage: 350,
					Distance: 0.94,
				},
				{
					Damage: 350,
					Distance: 3.3,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 47,
			InkConsume: 0.07,
		},
		"241": {
			SpecialPoint: 210,
			subWeaponId: 13,
			specialWeaponId: 10,
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			MoveSpeed: 0.055,
			DamageParam_ValueDirect: 850,
			BlastParam_DistanceDamage: [
				{
					Damage: 350,
					Distance: 0.94,
				},
				{
					Damage: 350,
					Distance: 3.3,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 47,
			InkConsume: 0.07,
		},
		"250": {
			SpecialPoint: 180,
			subWeaponId: 11,
			specialWeaponId: 8,
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			MoveSpeed: 0.05,
			DamageParam_ValueDirect: 850,
			BlastParam_DistanceDamage: [
				{
					Damage: 350,
					Distance: 0.94,
				},
				{
					Damage: 350,
					Distance: 3.3,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 50,
			InkConsume: 0.08,
		},
		"251": {
			SpecialPoint: 190,
			subWeaponId: 12,
			specialWeaponId: 9,
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.5,
				},
			},
			MoveSpeed: 0.05,
			DamageParam_ValueDirect: 850,
			BlastParam_DistanceDamage: [
				{
					Damage: 350,
					Distance: 0.94,
				},
				{
					Damage: 350,
					Distance: 3.3,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 50,
			InkConsume: 0.08,
		},
		"260": {
			SpecialPoint: 180,
			subWeaponId: 3,
			specialWeaponId: 13,
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.625,
				},
			},
			MoveSpeed: 0.04,
			DamageParam_ValueDirect: 1250,
			BlastParam_DistanceDamage: [
				{
					Damage: 700,
					Distance: 1,
				},
				{
					Damage: 500,
					Distance: 2,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 60,
			InkConsume: 0.085,
		},
		"261": {
			SpecialPoint: 190,
			subWeaponId: 2,
			specialWeaponId: 6,
			overwrites: {
				ReduceJumpSwerveRate: {
					Mid: 0.625,
				},
			},
			MoveSpeed: 0.04,
			DamageParam_ValueDirect: 1250,
			BlastParam_DistanceDamage: [
				{
					Damage: 700,
					Distance: 1,
				},
				{
					Damage: 500,
					Distance: 2,
				},
			],
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 0,
			InkRecoverStop: 60,
			InkConsume: 0.085,
		},
		"300": {
			SpecialPoint: 190,
			subWeaponId: 6,
			specialWeaponId: 12,
			TripleShotSpanFrame: 8,
			MoveSpeed: 0.08,
			DamageParam_ValueMax: 310,
			DamageParam_ValueMin: 155,
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 1,
			InkRecoverStop: 25,
			InkConsume: 0.0115,
		},
		"301": {
			SpecialPoint: 200,
			subWeaponId: 2,
			specialWeaponId: 11,
			TripleShotSpanFrame: 8,
			MoveSpeed: 0.08,
			DamageParam_ValueMax: 310,
			DamageParam_ValueMin: 155,
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 1,
			InkRecoverStop: 25,
			InkConsume: 0.0115,
		},
		"310": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 15,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			TripleShotSpanFrame: 20,
			MoveSpeed: 0.06,
			DamageParam_ValueMax: 440,
			DamageParam_ValueMin: 220,
			Jump_DegSwerve: 1,
			Stand_DegSwerve: 1,
			InkRecoverStop: 25,
			InkConsume: 0.0225,
		},
		"311": {
			SpecialPoint: 200,
			subWeaponId: 4,
			specialWeaponId: 2,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			TripleShotSpanFrame: 20,
			MoveSpeed: 0.06,
			DamageParam_ValueMax: 440,
			DamageParam_ValueMin: 220,
			Jump_DegSwerve: 1,
			Stand_DegSwerve: 1,
			InkRecoverStop: 25,
			InkConsume: 0.0225,
		},
		"400": {
			SpecialPoint: 220,
			subWeaponId: 4,
			specialWeaponId: 1,
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 380,
			DamageParam_ValueMin: 190,
			Variable_Damage_ValueMax: 300,
			Variable_Damage_ValueMin: 150,
			Jump_DegSwerve: 0,
			Stand_DegSwerve: 0,
			Variable_Jump_DegSwerve: 13,
			Variable_Stand_DegSwerve: 8,
			InkConsume: 0.024,
		},
		"401": {
			SpecialPoint: 190,
			subWeaponId: 7,
			specialWeaponId: 19,
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 380,
			DamageParam_ValueMin: 190,
			Variable_Damage_ValueMax: 300,
			Variable_Damage_ValueMin: 150,
			Jump_DegSwerve: 0,
			Stand_DegSwerve: 0,
			Variable_Jump_DegSwerve: 13,
			Variable_Stand_DegSwerve: 8,
			InkConsume: 0.024,
		},
		"1000": {
			SpecialPoint: 160,
			subWeaponId: 7,
			specialWeaponId: 3,
			WeaponSpeedType: "Fast",
			BodyParam_Damage: 700,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 350,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1200,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 250,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 1000,
			InkConsume_WeaponSwingParam: 0.0396,
		},
		"1001": {
			SpecialPoint: 190,
			subWeaponId: 2,
			specialWeaponId: 1,
			WeaponSpeedType: "Fast",
			BodyParam_Damage: 700,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 350,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1200,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 250,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 1000,
			InkConsume_WeaponSwingParam: 0.0396,
		},
		"1010": {
			SpecialPoint: 180,
			subWeaponId: 6,
			specialWeaponId: 2,
			BodyParam_Damage: 1250,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1500,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 350,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 1500,
			InkConsume_WeaponSwingParam: 0.085,
		},
		"1011": {
			SpecialPoint: 170,
			subWeaponId: 8,
			specialWeaponId: 17,
			BodyParam_Damage: 1250,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1500,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 350,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 1500,
			InkConsume_WeaponSwingParam: 0.085,
		},
		"1015": {
			SpecialPoint: 180,
			subWeaponId: 6,
			specialWeaponId: 2,
			BodyParam_Damage: 1250,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1500,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 350,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 1500,
			InkConsume_WeaponSwingParam: 0.085,
		},
		"1020": {
			SpecialPoint: 190,
			subWeaponId: 3,
			specialWeaponId: 15,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			WeaponSpeedType: "Slow",
			BodyParam_Damage: 1250,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1800,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 1800,
			InkConsume_WeaponSwingParam: 0.18,
		},
		"1021": {
			SpecialPoint: 180,
			subWeaponId: 0,
			specialWeaponId: 16,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			WeaponSpeedType: "Slow",
			BodyParam_Damage: 1250,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1800,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 1800,
			InkConsume_WeaponSwingParam: 0.18,
		},
		"1030": {
			SpecialPoint: 210,
			subWeaponId: 10,
			specialWeaponId: 4,
			BodyParam_Damage: 1250,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1500,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 300,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 1500,
			InkConsume_WeaponVerticalSwingParam: 0.12,
			InkConsume_WeaponWideSwingParam: 0.08,
		},
		"1031": {
			SpecialPoint: 200,
			subWeaponId: 1,
			specialWeaponId: 19,
			BodyParam_Damage: 1250,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1500,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 300,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 1500,
			InkConsume_WeaponVerticalSwingParam: 0.12,
			InkConsume_WeaponWideSwingParam: 0.08,
		},
		"1040": {
			SpecialPoint: 190,
			subWeaponId: 4,
			specialWeaponId: 8,
			BodyParam_Damage: 700,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1200,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 700,
			InkConsume_WeaponSwingParam: 0.09,
		},
		"1041": {
			SpecialPoint: 190,
			subWeaponId: 12,
			specialWeaponId: 5,
			BodyParam_Damage: 700,
			VerticalSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			VerticalSwingUnitGroupParam_DamageParam_DamageMaxValue: 1200,
			WideSwingUnitGroupParam_DamageParam_DamageMinValue: 400,
			WideSwingUnitGroupParam_DamageParam_DamageMaxValue: 700,
			InkConsume_WeaponSwingParam: 0.09,
		},
		"1100": {
			SpecialPoint: 180,
			subWeaponId: 0,
			specialWeaponId: 9,
			WeaponSpeedType: "Fast",
			BodyParam_Damage: 200,
			SwingUnitGroupParam_DamageParam_DamageMinValue: 150,
			SwingUnitGroupParam_DamageParam_DamageMaxValue: 300,
			InkConsume_WeaponSwingParam: 0.02,
		},
		"1101": {
			SpecialPoint: 180,
			subWeaponId: 10,
			specialWeaponId: 11,
			WeaponSpeedType: "Fast",
			BodyParam_Damage: 200,
			SwingUnitGroupParam_DamageParam_DamageMinValue: 150,
			SwingUnitGroupParam_DamageParam_DamageMaxValue: 300,
			InkConsume_WeaponSwingParam: 0.02,
		},
		"1110": {
			SpecialPoint: 200,
			subWeaponId: 1,
			specialWeaponId: 3,
			BodyParam_Damage: 250,
			SwingUnitGroupParam_DamageParam_DamageMinValue: 200,
			SwingUnitGroupParam_DamageParam_DamageMaxValue: 400,
			InkConsume_WeaponSwingParam: 0.03,
		},
		"1111": {
			SpecialPoint: 180,
			subWeaponId: 8,
			specialWeaponId: 5,
			BodyParam_Damage: 250,
			SwingUnitGroupParam_DamageParam_DamageMinValue: 200,
			SwingUnitGroupParam_DamageParam_DamageMaxValue: 400,
			InkConsume_WeaponSwingParam: 0.03,
		},
		"1115": {
			SpecialPoint: 200,
			subWeaponId: 1,
			specialWeaponId: 3,
			BodyParam_Damage: 250,
			SwingUnitGroupParam_DamageParam_DamageMinValue: 200,
			SwingUnitGroupParam_DamageParam_DamageMaxValue: 400,
			InkConsume_WeaponSwingParam: 0.03,
		},
		"1120": {
			SpecialPoint: 190,
			subWeaponId: 6,
			specialWeaponId: 7,
			BodyParam_Damage: 300,
			SwingUnitGroupParam_DamageParam_DamageMinValue: 310,
			SwingUnitGroupParam_DamageParam_DamageMaxValue: 600,
			InkConsume_WeaponSwingParam: 0.048,
		},
		"1121": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 4,
			BodyParam_Damage: 300,
			SwingUnitGroupParam_DamageParam_DamageMinValue: 310,
			SwingUnitGroupParam_DamageParam_DamageMaxValue: 600,
			InkConsume_WeaponSwingParam: 0.048,
		},
		"2000": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 2,
			MoveSpeedFullCharge: 0.03,
			DamageParam_ValueFullCharge: 1400,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 45,
			KeepChargeFullFrame: 75,
			InkConsumeFullCharge: 0.105,
			InkConsumeMinCharge: 0.018667,
		},
		"2001": {
			SpecialPoint: 200,
			subWeaponId: 7,
			specialWeaponId: 3,
			MoveSpeedFullCharge: 0.03,
			DamageParam_ValueFullCharge: 1400,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 45,
			KeepChargeFullFrame: 75,
			InkConsumeFullCharge: 0.105,
			InkConsumeMinCharge: 0.018667,
		},
		"2010": {
			SpecialPoint: 190,
			subWeaponId: 0,
			specialWeaponId: 8,
			MoveSpeedFullCharge: 0.02,
			DamageParam_ValueFullCharge: 1600,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			KeepChargeFullFrame: 75,
			InkConsumeFullCharge: 0.18,
			InkConsumeMinCharge: 0.0225,
		},
		"2011": {
			SpecialPoint: 210,
			subWeaponId: 4,
			specialWeaponId: 14,
			MoveSpeedFullCharge: 0.02,
			DamageParam_ValueFullCharge: 1600,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			KeepChargeFullFrame: 75,
			InkConsumeFullCharge: 0.18,
			InkConsumeMinCharge: 0.0225,
		},
		"2015": {
			SpecialPoint: 190,
			subWeaponId: 0,
			specialWeaponId: 8,
			MoveSpeedFullCharge: 0.02,
			DamageParam_ValueFullCharge: 1600,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			KeepChargeFullFrame: 75,
			InkConsumeFullCharge: 0.18,
			InkConsumeMinCharge: 0.0225,
		},
		"2020": {
			SpecialPoint: 190,
			subWeaponId: 0,
			specialWeaponId: 8,
			MoveSpeedFullCharge: 0.02,
			DamageParam_ValueFullCharge: 1600,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			InkConsumeFullCharge: 0.18,
			InkConsumeMinCharge: 0.0225,
		},
		"2021": {
			SpecialPoint: 210,
			subWeaponId: 4,
			specialWeaponId: 14,
			MoveSpeedFullCharge: 0.02,
			DamageParam_ValueFullCharge: 1600,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			InkConsumeFullCharge: 0.18,
			InkConsumeMinCharge: 0.0225,
		},
		"2030": {
			SpecialPoint: 210,
			subWeaponId: 10,
			specialWeaponId: 7,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			WeaponSpeedType: "Slow",
			MoveSpeedFullCharge: 0.015,
			DamageParam_ValueFullCharge: 1800,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 92,
			KeepChargeFullFrame: 75,
			InkConsumeFullCharge: 0.25,
			InkConsumeMinCharge: 0.0225,
		},
		"2031": {
			SpecialPoint: 210,
			subWeaponId: 8,
			specialWeaponId: 17,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			WeaponSpeedType: "Slow",
			MoveSpeedFullCharge: 0.015,
			DamageParam_ValueFullCharge: 1800,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 92,
			KeepChargeFullFrame: 75,
			InkConsumeFullCharge: 0.25,
			InkConsumeMinCharge: 0.0225,
		},
		"2040": {
			SpecialPoint: 210,
			subWeaponId: 10,
			specialWeaponId: 7,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			WeaponSpeedType: "Slow",
			MoveSpeedFullCharge: 0.015,
			DamageParam_ValueFullCharge: 1800,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 92,
			InkConsumeFullCharge: 0.25,
			InkConsumeMinCharge: 0.0225,
		},
		"2041": {
			SpecialPoint: 210,
			subWeaponId: 8,
			specialWeaponId: 17,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			WeaponSpeedType: "Slow",
			MoveSpeedFullCharge: 0.015,
			DamageParam_ValueFullCharge: 1800,
			DamageParam_ValueMaxCharge: 800,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 92,
			InkConsumeFullCharge: 0.25,
			InkConsumeMinCharge: 0.0225,
		},
		"2050": {
			SpecialPoint: 190,
			subWeaponId: 7,
			specialWeaponId: 9,
			WeaponSpeedType: "Fast",
			MoveSpeedFullCharge: 0.06,
			DamageParam_ValueFullCharge: 850,
			DamageParam_ValueMaxCharge: 850,
			DamageParam_ValueMinCharge: 300,
			ChargeFrameFullCharge: 20,
			InkConsumeFullCharge: 0.07,
			InkConsumeMinCharge: 0.028,
		},
		"2051": {
			SpecialPoint: 200,
			subWeaponId: 5,
			specialWeaponId: 16,
			WeaponSpeedType: "Fast",
			MoveSpeedFullCharge: 0.06,
			DamageParam_ValueFullCharge: 850,
			DamageParam_ValueMaxCharge: 850,
			DamageParam_ValueMinCharge: 300,
			ChargeFrameFullCharge: 20,
			InkConsumeFullCharge: 0.07,
			InkConsumeMinCharge: 0.028,
		},
		"2060": {
			SpecialPoint: 200,
			subWeaponId: 13,
			specialWeaponId: 4,
			MoveSpeedFullCharge: 0.03,
			DamageParam_ValueFullCharge: 1800,
			DamageParam_ValueMaxCharge: 1300,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 75,
			KeepChargeFullFrame: 300,
			InkConsumeFullCharge: 0.15,
			InkConsumeMinCharge: 0.02,
		},
		"2061": {
			SpecialPoint: 200,
			subWeaponId: 5,
			specialWeaponId: 11,
			MoveSpeedFullCharge: 0.03,
			DamageParam_ValueFullCharge: 1800,
			DamageParam_ValueMaxCharge: 1300,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 75,
			KeepChargeFullFrame: 300,
			InkConsumeFullCharge: 0.15,
			InkConsumeMinCharge: 0.02,
		},
		"2070": {
			SpecialPoint: 210,
			subWeaponId: 3,
			specialWeaponId: 15,
			MoveSpeedFullCharge: 0.068,
			DamageParam_ValueFullCharge: 680,
			DamageParam_ValueMaxCharge: 680,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 72,
			InkConsumeFullCharge: 0.35,
			InkConsumeMinCharge: 0.0197,
		},
		"2071": {
			SpecialPoint: 210,
			subWeaponId: 4,
			specialWeaponId: 5,
			MoveSpeedFullCharge: 0.068,
			DamageParam_ValueFullCharge: 680,
			DamageParam_ValueMaxCharge: 680,
			DamageParam_ValueMinCharge: 400,
			ChargeFrameFullCharge: 72,
			InkConsumeFullCharge: 0.35,
			InkConsumeMinCharge: 0.0197,
		},
		"3000": {
			SpecialPoint: 200,
			subWeaponId: 0,
			specialWeaponId: 14,
			MoveSpeed: 0.04,
			DamageParam_ValueDirectMax: 700,
			DamageParam_ValueDirectMin: 500,
			InkRecoverStop: 40,
			InkConsumeSlosher: 0.07,
		},
		"3001": {
			SpecialPoint: 180,
			subWeaponId: 12,
			specialWeaponId: 3,
			MoveSpeed: 0.04,
			DamageParam_ValueDirectMax: 700,
			DamageParam_ValueDirectMin: 500,
			InkRecoverStop: 40,
			InkConsumeSlosher: 0.07,
		},
		"3005": {
			SpecialPoint: 200,
			subWeaponId: 0,
			specialWeaponId: 14,
			MoveSpeed: 0.04,
			DamageParam_ValueDirectMax: 700,
			DamageParam_ValueDirectMin: 500,
			InkRecoverStop: 40,
			InkConsumeSlosher: 0.07,
		},
		"3010": {
			SpecialPoint: 180,
			subWeaponId: 11,
			specialWeaponId: 10,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.066,
			DamageParam_ValueDirectMax: 620,
			DamageParam_ValueDirectMin: 350,
			InkRecoverStop: 35,
			InkConsumeSlosher: 0.06,
		},
		"3011": {
			SpecialPoint: 210,
			subWeaponId: 5,
			specialWeaponId: 15,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.066,
			DamageParam_ValueDirectMax: 620,
			DamageParam_ValueDirectMin: 350,
			InkRecoverStop: 35,
			InkConsumeSlosher: 0.06,
		},
		"3020": {
			SpecialPoint: 220,
			subWeaponId: 5,
			specialWeaponId: 6,
			MoveSpeed: 0.07,
			DamageParam_ValueDirectMax: 760,
			DamageParam_ValueDirectMin: 520,
			BlastParam_SplashDamage: 380,
			InkRecoverStop: 42,
			InkConsumeSlosher: 0.092,
		},
		"3021": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 1,
			MoveSpeed: 0.07,
			DamageParam_ValueDirectMax: 760,
			DamageParam_ValueDirectMin: 520,
			InkRecoverStop: 42,
			InkConsumeSlosher: 0.092,
		},
		"3030": {
			SpecialPoint: 190,
			subWeaponId: 3,
			specialWeaponId: 5,
			MoveSpeed: 0.05,
			DamageParam_ValueDirect: 300,
			InkRecoverStop: 40,
			InkConsumeSlosher: 0.08,
		},
		"3031": {
			SpecialPoint: 190,
			subWeaponId: 12,
			specialWeaponId: 17,
			MoveSpeed: 0.05,
			DamageParam_ValueDirect: 300,
			InkRecoverStop: 40,
			InkConsumeSlosher: 0.08,
		},
		"3040": {
			SpecialPoint: 200,
			subWeaponId: 9,
			specialWeaponId: 5,
			WeaponSpeedType: "Slow",
			MoveSpeed: 0.045,
			DamageParam_ValueDirect: 550,
			BlastParam_DistanceDamage: [
				{
					Damage: 350,
					Distance: 2.8,
				},
			],
			InkRecoverStop: 70,
			InkConsumeSlosher: 0.117,
		},
		"3041": {
			SpecialPoint: 200,
			subWeaponId: 4,
			specialWeaponId: 18,
			WeaponSpeedType: "Slow",
			MoveSpeed: 0.045,
			DamageParam_ValueDirect: 550,
			BlastParam_DistanceDamage: [
				{
					Damage: 350,
					Distance: 2.8,
				},
			],
			InkRecoverStop: 70,
			InkConsumeSlosher: 0.117,
		},
		"3050": {
			SpecialPoint: 190,
			subWeaponId: 1,
			specialWeaponId: 13,
			MoveSpeed: 0.04,
			DamageParam_ValueDirectMax: 480,
			DamageParam_ValueDirectMin: 350,
			DamageParam_Secondary_ValueDirectMax: 420,
			DamageParam_Secondary_ValueDirectMin: 350,
			InkRecoverStop: 50,
			InkConsumeSlosher: 0.09,
		},
		"3051": {
			SpecialPoint: 190,
			subWeaponId: 8,
			specialWeaponId: 7,
			MoveSpeed: 0.04,
			DamageParam_ValueDirectMax: 480,
			DamageParam_ValueDirectMin: 350,
			DamageParam_Secondary_ValueDirectMax: 420,
			DamageParam_Secondary_ValueDirectMin: 350,
			InkRecoverStop: 50,
			InkConsumeSlosher: 0.09,
		},
		"4000": {
			SpecialPoint: 190,
			subWeaponId: 2,
			specialWeaponId: 11,
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.4,
					Low: 1,
					Mid: 1.2,
				},
			},
			MoveSpeed: 0.086,
			MoveSpeed_Charge: 0.072,
			DamageParam_ValueMax: 320,
			DamageParam_ValueMin: 160,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 4,
			InkRecoverStop: 30,
			InkConsumeFullChargeSplatling: 0.15,
		},
		"4001": {
			SpecialPoint: 190,
			subWeaponId: 11,
			specialWeaponId: 2,
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.4,
					Low: 1,
					Mid: 1.2,
				},
			},
			MoveSpeed: 0.086,
			MoveSpeed_Charge: 0.072,
			DamageParam_ValueMax: 320,
			DamageParam_ValueMin: 160,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 4,
			InkRecoverStop: 30,
			InkConsumeFullChargeSplatling: 0.15,
		},
		"4010": {
			SpecialPoint: 200,
			subWeaponId: 3,
			specialWeaponId: 7,
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.35,
					Low: 1,
					Mid: 1.175,
				},
			},
			MoveSpeed: 0.07,
			MoveSpeed_Charge: 0.062,
			DamageParam_ValueMax: 300,
			DamageParam_ValueMin: 150,
			Jump_DegSwerve: 7,
			Stand_DegSwerve: 3.3,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.225,
		},
		"4011": {
			SpecialPoint: 200,
			subWeaponId: 9,
			specialWeaponId: 17,
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.35,
					Low: 1,
					Mid: 1.175,
				},
			},
			MoveSpeed: 0.07,
			DamageParam_ValueMax: 300,
			DamageParam_ValueMin: 150,
			Jump_DegSwerve: 7,
			Stand_DegSwerve: 3.3,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.225,
		},
		"4015": {
			SpecialPoint: 200,
			subWeaponId: 3,
			specialWeaponId: 7,
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.35,
					Low: 1,
					Mid: 1.175,
				},
			},
			MoveSpeed: 0.07,
			DamageParam_ValueMax: 300,
			DamageParam_ValueMin: 150,
			Jump_DegSwerve: 7,
			Stand_DegSwerve: 3.3,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.225,
		},
		"4020": {
			SpecialPoint: 190,
			subWeaponId: 7,
			specialWeaponId: 6,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Low: 1,
					Mid: 0.7,
				},
				MoveVelRt_Shot: {
					High: 1.35,
					Low: 1,
					Mid: 1.175,
				},
			},
			WeaponSpeedType: "Slow",
			MoveSpeed: 0.06,
			MoveSpeed_Charge: 0.044,
			DamageParam_ValueMax: 320,
			DamageParam_ValueMin: 160,
			DamageParam_ValueFullChargeMax: 400,
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 3,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.35,
		},
		"4021": {
			SpecialPoint: 200,
			subWeaponId: 10,
			specialWeaponId: 19,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Low: 1,
					Mid: 0.7,
				},
				MoveVelRt_Shot: {
					High: 1.35,
					Low: 1,
					Mid: 1.175,
				},
			},
			WeaponSpeedType: "Slow",
			MoveSpeed: 0.06,
			MoveSpeed_Charge: 0.044,
			DamageParam_ValueMax: 320,
			DamageParam_ValueMin: 160,
			DamageParam_ValueFullChargeMax: 400,
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 3,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.35,
		},
		"4030": {
			SpecialPoint: 210,
			subWeaponId: 5,
			specialWeaponId: 10,
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.25,
					Low: 1,
					Mid: 1.125,
				},
			},
			MoveSpeed: 0.086,
			MoveSpeed_Charge: 0.086,
			MoveSpeedVariable: 0.05,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Variable_Damage_ValueMax: 300,
			Variable_Damage_ValueMin: 150,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 6,
			Variable_Jump_DegSwerve: 4,
			Variable_Stand_DegSwerve: 1.5,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.25,
		},
		"4031": {
			SpecialPoint: 200,
			subWeaponId: 10,
			specialWeaponId: 8,
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.25,
					Low: 1,
					Mid: 1.125,
				},
			},
			MoveSpeed: 0.086,
			MoveSpeed_Charge: 0.086,
			MoveSpeedVariable: 0.05,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Variable_Damage_ValueMax: 300,
			Variable_Damage_ValueMin: 150,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 6,
			Variable_Jump_DegSwerve: 4,
			Variable_Stand_DegSwerve: 1.5,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.25,
		},
		"4040": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 5,
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.3,
					Low: 1,
					Mid: 1.15,
				},
			},
			MoveSpeed: 0.07,
			MoveSpeed_Charge: 0.04,
			DamageParam_ValueMax: 320,
			DamageParam_ValueMin: 160,
			KeepChargeFullFrame: 200,
			Jump_DegSwerve: 3.6,
			Stand_DegSwerve: 3.3,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.15,
		},
		"4041": {
			SpecialPoint: 210,
			subWeaponId: 1,
			specialWeaponId: 18,
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.3,
					Low: 1,
					Mid: 1.15,
				},
			},
			MoveSpeed: 0.07,
			MoveSpeed_Charge: 0.04,
			DamageParam_ValueMax: 320,
			DamageParam_ValueMin: 160,
			KeepChargeFullFrame: 200,
			Jump_DegSwerve: 3.6,
			Stand_DegSwerve: 3.3,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.15,
		},
		"4050": {
			SpecialPoint: 200,
			subWeaponId: 6,
			specialWeaponId: 15,
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.4,
					Low: 1,
					Mid: 1.2,
				},
			},
			MoveSpeed: 0.086,
			MoveSpeed_Charge: 0.072,
			DamageParam_ValueMax: 260,
			DamageParam_ValueMin: 130,
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 3,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.2,
		},
		"4051": {
			SpecialPoint: 210,
			subWeaponId: 0,
			specialWeaponId: 12,
			overwrites: {
				MoveVelRt_Shot: {
					High: 1.4,
					Low: 1,
					Mid: 1.2,
				},
			},
			MoveSpeed: 0.086,
			MoveSpeed_Charge: 0.072,
			DamageParam_ValueMax: 260,
			DamageParam_ValueMin: 130,
			Jump_DegSwerve: 6,
			Stand_DegSwerve: 3,
			InkRecoverStop: 40,
			InkConsumeFullChargeSplatling: 0.2,
		},
		"5000": {
			SpecialPoint: 170,
			subWeaponId: 8,
			specialWeaponId: 15,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.084,
			DamageParam_ValueMax: 360,
			DamageParam_ValueMin: 180,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 7,
			InkConsume: 0.00663,
			InkConsume_SideStepParam: 0.05,
		},
		"5001": {
			SpecialPoint: 190,
			subWeaponId: 13,
			specialWeaponId: 13,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.084,
			DamageParam_ValueMax: 360,
			DamageParam_ValueMin: 180,
			Jump_DegSwerve: 12,
			Stand_DegSwerve: 7,
			InkConsume: 0.00663,
			InkConsume_SideStepParam: 0.05,
		},
		"5010": {
			SpecialPoint: 190,
			subWeaponId: 1,
			specialWeaponId: 12,
			MoveSpeed: 0.08,
			DamageParam_ValueMax: 300,
			DamageParam_ValueMin: 150,
			Jump_DegSwerve: 7.5,
			Stand_DegSwerve: 2,
			InkConsume: 0.0072,
			InkConsume_SideStepParam: 0.07,
		},
		"5011": {
			SpecialPoint: 200,
			subWeaponId: 6,
			specialWeaponId: 18,
			MoveSpeed: 0.08,
			DamageParam_ValueMax: 300,
			DamageParam_ValueMin: 150,
			Jump_DegSwerve: 7.5,
			Stand_DegSwerve: 2,
			InkConsume: 0.0072,
			InkConsume_SideStepParam: 0.07,
		},
		"5015": {
			SpecialPoint: 190,
			subWeaponId: 1,
			specialWeaponId: 12,
			MoveSpeed: 0.08,
			DamageParam_ValueMax: 300,
			DamageParam_ValueMin: 150,
			Jump_DegSwerve: 7.5,
			Stand_DegSwerve: 2,
			InkConsume: 0.0072,
			InkConsume_SideStepParam: 0.07,
		},
		"5020": {
			SpecialPoint: 180,
			subWeaponId: 4,
			specialWeaponId: 6,
			MoveSpeed: 0.06,
			DamageParam_ValueMax: 360,
			DamageParam_ValueMin: 180,
			DamageLapOverParam_ValueMax: 525,
			DamageLapOverParam_ValueMin: 263,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 3.2,
			InkConsume: 0.014,
			InkConsume_SideStepParam: 0.08,
		},
		"5021": {
			SpecialPoint: 190,
			subWeaponId: 9,
			specialWeaponId: 1,
			MoveSpeed: 0.06,
			DamageParam_ValueMax: 360,
			DamageParam_ValueMin: 180,
			DamageLapOverParam_ValueMax: 525,
			DamageLapOverParam_ValueMin: 263,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 3.2,
			InkConsume: 0.014,
			InkConsume_SideStepParam: 0.08,
		},
		"5030": {
			SpecialPoint: 200,
			subWeaponId: 0,
			specialWeaponId: 7,
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 4,
			InkConsume: 0.012,
			InkConsume_SideStepParam: 0.08,
		},
		"5031": {
			SpecialPoint: 210,
			subWeaponId: 8,
			specialWeaponId: 16,
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 4,
			InkConsume: 0.012,
			InkConsume_SideStepParam: 0.08,
		},
		"5040": {
			SpecialPoint: 200,
			subWeaponId: 7,
			specialWeaponId: 13,
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Jump_DegSwerve: 12.8,
			Stand_DegSwerve: 7.4,
			InkConsume: 0.008,
			InkConsume_SideStepParam: 0.03,
		},
		"5041": {
			SpecialPoint: 190,
			subWeaponId: 3,
			specialWeaponId: 3,
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 280,
			DamageParam_ValueMin: 140,
			Jump_DegSwerve: 12.8,
			Stand_DegSwerve: 7.4,
			InkConsume: 0.008,
			InkConsume_SideStepParam: 0.03,
		},
		"5050": {
			SpecialPoint: 200,
			subWeaponId: 10,
			specialWeaponId: 9,
			MoveSpeed: 0.07,
			DamageParam_ValueMax: 255,
			DamageParam_ValueMin: 128,
			DamageLapOverParam_ValueMax: 255,
			DamageLapOverParam_ValueMin: 128,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 2.5,
			InkConsume: 0.012,
			InkConsume_SideStepParam: 0.1,
		},
		"5051": {
			SpecialPoint: 200,
			subWeaponId: 2,
			specialWeaponId: 14,
			MoveSpeed: 0.07,
			DamageParam_ValueMax: 255,
			DamageParam_ValueMin: 128,
			DamageLapOverParam_ValueMax: 255,
			DamageLapOverParam_ValueMin: 128,
			Jump_DegSwerve: 8,
			Stand_DegSwerve: 2.5,
			InkConsume: 0.012,
			InkConsume_SideStepParam: 0.1,
		},
		"6000": {
			SpecialPoint: 200,
			subWeaponId: 3,
			specialWeaponId: 14,
			MoveSpeed: 0.065,
			DamageParam_ValueMax: 810,
			InkConsumeUmbrella_WeaponShelterCanopyParam: 0.3,
			InkConsume_WeaponShelterShotgunParam: 0.055,
		},
		"6001": {
			SpecialPoint: 190,
			subWeaponId: 7,
			specialWeaponId: 10,
			MoveSpeed: 0.065,
			DamageParam_ValueMax: 810,
			InkConsumeUmbrella_WeaponShelterCanopyParam: 0.3,
			InkConsume_WeaponShelterShotgunParam: 0.055,
		},
		"6005": {
			SpecialPoint: 200,
			subWeaponId: 3,
			specialWeaponId: 14,
			MoveSpeed: 0.065,
			DamageParam_ValueMax: 810,
			InkConsumeUmbrella_WeaponShelterCanopyParam: 0.3,
			InkConsume_WeaponShelterShotgunParam: 0.055,
		},
		"6010": {
			SpecialPoint: 190,
			subWeaponId: 8,
			specialWeaponId: 8,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			WeaponSpeedType: "Slow",
			MoveSpeed: 0.05,
			DamageParam_ValueMax: 1190,
			CanopyHP: 7000,
			InkConsumeUmbrella_WeaponShelterCanopyParam: 0.3,
			InkConsume_WeaponShelterShotgunParam: 0.11,
		},
		"6011": {
			SpecialPoint: 200,
			subWeaponId: 10,
			specialWeaponId: 1,
			overwrites: {
				ConsumeRt_Main: {
					High: 0.5,
					Mid: 0.7,
				},
			},
			WeaponSpeedType: "Slow",
			MoveSpeed: 0.05,
			DamageParam_ValueMax: 1190,
			CanopyHP: 7000,
			InkConsumeUmbrella_WeaponShelterCanopyParam: 0.3,
			InkConsume_WeaponShelterShotgunParam: 0.11,
		},
		"6020": {
			SpecialPoint: 180,
			subWeaponId: 10,
			specialWeaponId: 13,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 400,
			CanopyHP: 2000,
			InkConsume_WeaponShelterShotgunParam: 0.04,
		},
		"6021": {
			SpecialPoint: 180,
			subWeaponId: 13,
			specialWeaponId: 19,
			WeaponSpeedType: "Fast",
			MoveSpeed: 0.072,
			DamageParam_ValueMax: 400,
			CanopyHP: 2000,
			InkConsume_WeaponShelterShotgunParam: 0.04,
		},
		"6030": {
			SpecialPoint: 190,
			subWeaponId: 12,
			specialWeaponId: 2,
			MoveSpeed: 0.058,
			DamageParam_ValueMax: 900,
			CanopyHP: 1000,
			InkConsumeUmbrella_WeaponShelterCanopyParam: 0.15,
			InkConsume_WeaponShelterShotgunParam: 0.07,
		},
		"6031": {
			SpecialPoint: 200,
			subWeaponId: 11,
			specialWeaponId: 18,
			MoveSpeed: 0.058,
			DamageParam_ValueMax: 900,
			CanopyHP: 1000,
			InkConsumeUmbrella_WeaponShelterCanopyParam: 0.15,
			InkConsume_WeaponShelterShotgunParam: 0.07,
		},
		"7010": {
			SpecialPoint: 190,
			subWeaponId: 11,
			specialWeaponId: 9,
			MoveSpeedFullCharge: 0.068,
			DamageParam_ValueMax: 350,
			DamageParam_ValueMin: 300,
			BlastParam_DistanceDamage: [
				{
					Damage: 300,
					Distance: 2,
				},
			],
			ChargeFrameFullCharge: 72,
			InkConsumeFullCharge_ChargeParam: 0.085,
		},
		"7011": {
			SpecialPoint: 190,
			subWeaponId: 3,
			specialWeaponId: 16,
			MoveSpeedFullCharge: 0.068,
			DamageParam_ValueMax: 350,
			DamageParam_ValueMin: 300,
			BlastParam_DistanceDamage: [
				{
					Damage: 300,
					Distance: 2,
				},
			],
			ChargeFrameFullCharge: 72,
			InkConsumeFullCharge_ChargeParam: 0.085,
		},
		"7015": {
			SpecialPoint: 190,
			subWeaponId: 11,
			specialWeaponId: 9,
			MoveSpeedFullCharge: 0.068,
			DamageParam_ValueMax: 350,
			DamageParam_ValueMin: 300,
			BlastParam_DistanceDamage: [
				{
					Damage: 300,
					Distance: 2,
				},
			],
			ChargeFrameFullCharge: 72,
			InkConsumeFullCharge_ChargeParam: 0.085,
		},
		"7020": {
			SpecialPoint: 210,
			subWeaponId: 6,
			specialWeaponId: 4,
			WeaponSpeedType: "Fast",
			MoveSpeedFullCharge: 0.084,
			DamageParam_ValueMax: 450,
			DamageParam_ValueMin: 300,
			ChargeFrameFullCharge: 34,
			KeepChargeFullFrame: 75,
			InkConsumeFullCharge_ChargeParam: 0.065,
		},
		"7021": {
			SpecialPoint: 200,
			subWeaponId: 4,
			specialWeaponId: 13,
			WeaponSpeedType: "Fast",
			MoveSpeedFullCharge: 0.084,
			DamageParam_ValueMax: 450,
			DamageParam_ValueMin: 300,
			BlastParam_DistanceDamage: [
				{
					Damage: 280,
					Distance: 2,
				},
			],
			ChargeFrameFullCharge: 34,
			KeepChargeFullFrame: 75,
			InkConsumeFullCharge_ChargeParam: 0.065,
		},
		"7030": {
			SpecialPoint: 200,
			subWeaponId: 7,
			specialWeaponId: 11,
			WeaponSpeedType: "Slow",
			MoveSpeedFullCharge: 0.04,
			DamageParam_ValueMax: 350,
			DamageParam_ValueMin: 240,
			BlastParam_DistanceDamage: [
				{
					Damage: 300,
					Distance: 2,
				},
			],
			ChargeFrameFullCharge: 80,
			InkConsumeFullCharge_ChargeParam: 0.09,
		},
		"7031": {
			SpecialPoint: 200,
			subWeaponId: 9,
			specialWeaponId: 7,
			WeaponSpeedType: "Slow",
			MoveSpeedFullCharge: 0.04,
			DamageParam_ValueMax: 350,
			DamageParam_ValueMin: 240,
			BlastParam_DistanceDamage: [
				{
					Damage: 300,
					Distance: 2,
				},
			],
			ChargeFrameFullCharge: 80,
			InkConsumeFullCharge_ChargeParam: 0.09,
		},
		"8000": {
			SpecialPoint: 210,
			subWeaponId: 2,
			specialWeaponId: 3,
			DamageParam_SplatanaVerticalDirect: 1400,
			DamageParam_SplatanaVertical: 700,
			DamageParam_SplatanaHorizontalDirect: 550,
			DamageParam_SplatanaHorizontal: 350,
			InkConsume_SwingParam: 0.052,
			InkConsumeFullCharge_ChargeParam: 0.117,
		},
		"8001": {
			SpecialPoint: 210,
			subWeaponId: 11,
			specialWeaponId: 12,
			DamageParam_SplatanaVerticalDirect: 1400,
			DamageParam_SplatanaVertical: 700,
			DamageParam_SplatanaHorizontalDirect: 550,
			DamageParam_SplatanaHorizontal: 350,
			InkConsume_SwingParam: 0.052,
			InkConsumeFullCharge_ChargeParam: 0.117,
		},
		"8005": {
			SpecialPoint: 210,
			subWeaponId: 2,
			specialWeaponId: 3,
			DamageParam_SplatanaVerticalDirect: 1400,
			DamageParam_SplatanaVertical: 700,
			DamageParam_SplatanaHorizontalDirect: 550,
			DamageParam_SplatanaHorizontal: 350,
			InkConsume_SwingParam: 0.052,
			InkConsumeFullCharge_ChargeParam: 0.117,
		},
		"8010": {
			SpecialPoint: 190,
			subWeaponId: 13,
			specialWeaponId: 11,
			WeaponSpeedType: "Fast",
			DamageParam_SplatanaVerticalDirect: 1200,
			DamageParam_SplatanaVertical: 600,
			DamageParam_SplatanaHorizontalDirect: 450,
			DamageParam_SplatanaHorizontal: 300,
			InkConsume_SwingParam: 0.03,
			InkConsumeFullCharge_ChargeParam: 0.06,
		},
		"8011": {
			SpecialPoint: 190,
			subWeaponId: 8,
			specialWeaponId: 4,
			WeaponSpeedType: "Fast",
			DamageParam_SplatanaVerticalDirect: 1200,
			DamageParam_SplatanaVertical: 600,
			DamageParam_SplatanaHorizontalDirect: 450,
			DamageParam_SplatanaHorizontal: 300,
			InkConsume_SwingParam: 0.03,
			InkConsumeFullCharge_ChargeParam: 0.06,
		},
		"8020": {
			SpecialPoint: 200,
			subWeaponId: 1,
			specialWeaponId: 2,
			DamageParam_SplatanaVerticalDirect: 1600,
			DamageParam_SplatanaVertical: 800,
			DamageParam_SplatanaHorizontalDirect: 700,
			DamageParam_SplatanaHorizontal: 400,
			InkConsume_SwingParam: 0.065,
			InkConsumeFullCharge_ChargeParam: 0.13,
		},
		"8021": {
			SpecialPoint: 200,
			subWeaponId: 4,
			specialWeaponId: 10,
			DamageParam_SplatanaVerticalDirect: 1600,
			DamageParam_SplatanaVertical: 800,
			DamageParam_SplatanaHorizontalDirect: 700,
			DamageParam_SplatanaHorizontal: 400,
			InkConsume_SwingParam: 0.065,
			InkConsumeFullCharge_ChargeParam: 0.13,
		},
	},
	subWeapons: {
		"0": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.68,
					Low: 1.12,
					Mid: 1.4,
				},
			},
			SubInkSaveLv: 2,
			InkConsume: 0.7,
			InkRecoverStop: 60,
			DistanceDamage: [
				{
					Damage: 1800,
					Distance: 3.6,
				},
				{
					Damage: 300,
					Distance: 7,
				},
			],
		},
		"1": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.68,
					Low: 1.12,
					Mid: 1.4,
				},
			},
			SubInkSaveLv: 2,
			InkConsume: 0.7,
			InkRecoverStop: 60,
			DistanceDamage: [
				{
					Damage: 1800,
					Distance: 4.6,
				},
				{
					Damage: 300,
					Distance: 8,
				},
			],
		},
		"2": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.68,
					Low: 1.12,
					Mid: 1.4,
				},
			},
			SubInkSaveLv: 4,
			InkConsume: 0.45,
			InkRecoverStop: 60,
			DistanceDamage: [
				{
					Damage: 350,
					Distance: 2.8,
				},
				{
					Damage: 250,
					Distance: 4,
				},
			],
		},
		"3": {
			overwrites: {
				PeriodFirst: {
					High: 780,
					Low: 480,
					Mid: 630,
				},
				PeriodSecond: {
					High: 1020,
					Low: 900,
					Mid: 960,
				},
			},
			SubInkSaveLv: 3,
			InkConsume: 0.6,
			InkRecoverStop: 60,
		},
		"4": {
			overwrites: {
				MaxHP: {
					High: 15000,
					Low: 8000,
					Mid: 11500,
				},
			},
			SubInkSaveLv: 2,
			InkConsume: 0.6,
			InkRecoverStop: 85,
		},
		"5": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.84,
					Low: 1.36,
					Mid: 1.6,
				},
			},
			SubInkSaveLv: 1,
			InkConsume: 0.6,
			InkRecoverStop: 85,
			DistanceDamage_BlastParamArray: [
				[
					{
						Damage: 500,
						Distance: 1.6,
					},
					{
						Damage: 350,
						Distance: 3.8,
					},
				],
				[
					{
						Damage: 500,
						Distance: 1.95,
					},
					{
						Damage: 350,
						Distance: 4.5,
					},
				],
				[
					{
						Damage: 500,
						Distance: 2.6,
					},
					{
						Damage: 350,
						Distance: 5.45,
					},
				],
			],
		},
		"6": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 0.52,
					Low: 0.4,
					Mid: 0.46,
				},
			},
			SubInkSaveLv: 2,
			InkConsume: 0.65,
			InkRecoverStop: 70,
			DistanceDamage: [
				[
					{
						Damage: 1800,
						Distance: 4.6,
					},
					{
						Damage: 300,
						Distance: 8,
					},
				],
				[
					{
						Damage: 1800,
						Distance: 1.6,
					},
					{
						Damage: 300,
						Distance: 5,
					},
				],
			],
			DirectDamage: 200,
		},
		"7": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.68,
					Low: 1.12,
					Mid: 1.4,
				},
			},
			SubInkSaveLv: 1,
			InkConsume: 0.55,
			InkRecoverStop: 85,
			DistanceDamage: [
				{
					Damage: 1800,
					Distance: 2.85,
				},
				{
					Damage: 300,
					Distance: 6.5,
				},
			],
		},
		"8": {
			overwrites: {
				SubSpecUpParam: {
					Low: 0,
					High: 57,
					Mid: 25,
				},
			},
			SubInkSaveLv: 3,
			InkConsume: 0.75,
			InkRecoverStop: 0,
		},
		"9": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.87,
					Low: 1.38,
					Mid: 1.64,
				},
				MarkingFrameSubSpec: {
					High: 960,
					Low: 480,
					Mid: 720,
				},
			},
			SubInkSaveLv: 1,
			InkConsume: 0.45,
			InkRecoverStop: 75,
		},
		"10": {
			overwrites: {
				MarkingFrameSubSpec: {
					High: 600,
					Low: 300,
					Mid: 450,
				},
				SensorRadius: {
					High: 4,
					Low: 3,
					Mid: 3.5,
				},
				ExplosionRadius: {
					High: 11,
					Low: 8,
					Mid: 9.5,
				},
			},
			SubInkSaveLv: 3,
			InkConsume: 0.6,
			InkRecoverStop: 0,
			DistanceDamage: [
				{
					Damage: 450,
					Distance: 3.6,
				},
				{
					Damage: 350,
					Distance: 8,
				},
			],
		},
		"11": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.68,
					Low: 1.12,
					Mid: 1.4,
				},
			},
			SubInkSaveLv: 1,
			InkConsume: 0.6,
			InkRecoverStop: 75,
		},
		"12": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 6.48,
					Low: 6,
					Mid: 6.24,
				},
				MarkingFrameSubSpec: {
					High: 600,
					Low: 300,
					Mid: 450,
				},
			},
			SubInkSaveLv: 0,
			InkConsume: 0.4,
			InkRecoverStop: 50,
			DirectDamage: 400,
		},
		"13": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.84,
					Low: 1.36,
					Mid: 1.6,
				},
			},
			SubInkSaveLv: 2,
			InkConsume: 0.65,
			InkRecoverStop: 88,
			DistanceDamage_BlastParamChase: [
				{
					Damage: 600,
					Distance: 2.6,
				},
				{
					Damage: 350,
					Distance: 6,
				},
			],
			DistanceDamage_SplashBlastParam: [
				{
					Damage: 120,
					Distance: 2.6,
				},
			],
		},
	},
	specialWeapons: {
		"1": {
			overwrites: {
				PaintRadius: {
					High: 4,
					Low: 3.2,
					Mid: 3.6,
				},
				DistanceDamageDistanceRate: {
					High: 1.3,
					Low: 1,
					Mid: 1.15,
				},
				SpecialDurationFrame: {
					High: 480,
					Low: 360,
					Mid: 420,
				},
			},
			DistanceDamage: [
				{
					Damage: 530,
					Distance: 4,
				},
			],
			DirectDamage: 2200,
		},
		"2": {
			overwrites: {
				MaxFieldHP: {
					High: 36864,
					Low: 30720,
					Mid: 33792,
				},
				MaxHP: {
					High: 18432,
					Low: 15360,
					Mid: 16896,
				},
			},
		},
		"3": {
			overwrites: {
				InkConsume_Hook: {
					High: 0.0225,
					Low: 0.06,
					Mid: 0.0375,
				},
				InkConsume_PerSec: {
					High: 0.12,
					Low: 0.15,
					Mid: 0.1305,
				},
			},
			DistanceDamage: [
				{
					Damage: 450,
					Distance: 4.8,
				},
				{
					Damage: 350,
					Distance: 6,
				},
			],
		},
		"4": {
			overwrites: {
				TargetInCircleRadius: {
					High: 240,
					Low: 140,
					Mid: 190,
				},
			},
			DistanceDamage: [
				{
					Damage: 1500,
					Distance: 1.1,
				},
				{
					Damage: 500,
					Distance: 2.1,
				},
				{
					Damage: 300,
					Distance: 4.25,
				},
			],
		},
		"5": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.68,
					Low: 1.12,
					Mid: 1.4,
				},
				SpecialDurationFrame: {
					High: 600,
					Low: 480,
					Mid: 540,
				},
			},
			TickDamage: 4,
		},
		"6": {
			overwrites: {
				ChargeRateAutoPerFrame: {
					High: 0.01,
					Low: 0.002,
					Mid: 0.006,
				},
			},
			TickDamage: 33,
		},
		"7": {
			overwrites: {
				MaxFrame: {
					High: 216,
					Low: 160,
					Mid: 192,
				},
				MaxRadius: {
					High: 27,
					Low: 20,
					Mid: 24,
				},
			},
			DirectDamage: 300,
			WaveDamage: 450,
		},
		"8": {
			overwrites: {
				RadiusMax: {
					High: 4.3,
					Low: 3.3,
					Mid: 3.8,
				},
				RadiusMin: {
					High: 1.4,
					Low: 0.8,
					Mid: 1.1,
				},
			},
			ExhaleBlastParamMinChargeDistanceDamage: [
				{
					Damage: 2200,
					Distance: 6,
				},
			],
			ExhaleBlastParamMaxChargeDistanceDamage: [
				{
					Damage: 2200,
					Distance: 10,
				},
			],
		},
		"9": {
			overwrites: {
				SpecialDurationFrame: {
					High: 240,
					Low: 180,
					Mid: 220,
				},
			},
			TickDamage: 35,
		},
		"10": {
			overwrites: {
				DistanceDamageDistanceRate: {
					High: 1.3,
					Low: 1,
					Mid: 1.15,
				},
				SplashAroundVelocityMin: {
					High: 0.52,
					Low: 0.49,
					Mid: 0.505,
				},
				SplashAroundVelocityMax: {
					High: 0.35,
					Low: 0.33,
					Mid: 0.34,
				},
				SpecialDurationFrame: {
					High: 510,
					Low: 450,
					Mid: 480,
				},
				PaintRadius: {
					High: 3.9000000000000004,
					Mid: 3.865,
					Low: 3.83,
				},
			},
			DistanceDamage: [
				{
					Damage: 500,
					Distance: 2.55,
				},
				{
					Damage: 300,
					Distance: 5,
				},
			],
			DirectDamage: 1200,
		},
		"11": {
			overwrites: {
				SpecialDurationFrame: {
					High: 660,
					Low: 450,
					Mid: 570,
				},
			},
			SwingDamage: [
				{
					Damage: 1000,
					Distance: 0,
				},
				{
					Damage: 400,
					Distance: 4,
				},
			],
			ThrowDamage: [
				{
					Damage: 600,
					Distance: 4,
				},
				{
					Damage: 300,
					Distance: 8,
				},
			],
			ThrowDirectDamage: 2200,
		},
		"12": {
			ArmorHP: 5000,
			overwrites: {
				SpecialDurationFrame: {
					High: 660,
					Low: 480,
					Mid: 570,
				},
			},
			BulletDamageMin: 160,
			BulletDamageMax: 320,
			CannonDamage: [
				{
					Damage: 600,
					Distance: 1,
				},
				{
					Damage: 300,
					Distance: 5.6,
				},
			],
			BumpDamage: 400,
		},
		"13": {
			overwrites: {
				DistanceDamageDistanceRate: {
					High: 1.2,
					Low: 1,
					Mid: 1.1,
				},
				PaintRadius: {
					High: 10.889999999999999,
					Mid: 9.982,
					Low: 9.075,
				},
				SplashAroundVelocityMin: {
					High: 0.7,
					Low: 0.6,
					Mid: 0.65,
				},
				SplashAroundVelocityMax: {
					High: 0.8,
					Low: 0.7,
					Mid: 0.75,
				},
			},
			DistanceDamage: [
				{
					Damage: 2200,
					Distance: 7.5,
				},
				{
					Damage: 700,
					Distance: 14.9,
				},
			],
		},
		"14": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 2.6,
					Low: 2,
					Mid: 2.3,
				},
			},
		},
		"15": {
			overwrites: {
				PowerUpFrame: {
					High: 1500,
					Low: 1020,
					Mid: 1290,
				},
			},
		},
		"16": {
			overwrites: {
				CrossPaintCheckLength: {
					High: 3,
					Low: 2.5,
					Mid: 2.75,
				},
				CrossPaintRadius: {
					High: 3,
					Low: 2.5,
					Mid: 2.75,
				},
				DistanceDamageDistanceRate: {
					High: 1.2,
					Low: 1,
					Mid: 1.1,
				},
			},
			DistanceDamage: [
				{
					Damage: 700,
					Distance: 3.6,
				},
				{
					Damage: 350,
					Distance: 6,
				},
			],
		},
		"17": {
			overwrites: {
				SpecialDurationFrame: {
					High: 600,
					Low: 480,
					Mid: 540,
				},
			},
			DirectDamage: 1200,
			JumpDamage: 600,
		},
		"18": {
			overwrites: {
				DistanceDamageDistanceRate: {
					High: 1.1,
					Low: 1,
					Mid: 1.05,
				},
				PaintRadius: {
					High: 10.8,
					Low: 9,
					Mid: 9.9,
				},
			},
			DistanceDamage: [
				{
					Damage: 2200,
					Distance: 7,
				},
				{
					Damage: 600,
					Distance: 10.5,
				},
			],
		},
		"19": {
			overwrites: {
				SpawnSpeedZSpecUp: {
					High: 1.68,
					Low: 1.12,
					Mid: 1.4,
				},
				MoveSpeed: {
					High: 0.06,
					Low: 0.04,
					Mid: 0.053,
				},
			},
		},
	},
};
