const translations = {
  game: {
    Baller: "Baller",
    SquidForce: "SquidForce",
    Zink: "Zink",
    "Krak-On": "Krak-On",
    Rockenberg: "Rockenberg",
    Zekko: "Zekko",
    Forge: "Forge",
    Firefin: "Firefin",
    Skalop: "Skalop",
    "Splash Mob": "Splash Mob",
    Inkline: "Inkline",
    Tentatek: "Tentatek",
    Takoroka: "Takoroka",
    Annaki: "Annaki",
    Enperry: "Enperry",
    "Toni Kensa": "Toni Kensa",
    Grizzco: "Grizzco",
    Cuttlegear: "Cuttlegear",
    amiibo: "amiibo",
    "Princess Cannon": "Princess Cannon",
    "Fire Rate": "Fire Rate",
    "Bomb Defense Up DX": "Bomb Defense Up DX",
    "Sub Power Up": "Sub Power Up",
    "Curling Bomb": "Curling Bomb",
    Autobomb: "Autobomb",
    "Splat Bomb": "Splat Bomb",
    "Fizzy Bomb": "Fizzy Bomb",
    "Burst Bomb": "Burst Bomb",
    "Suction Bomb": "Suction Bomb",
    Torpedo: "Torpedo",
    "Charge Speed": "Charge Speed",
    "Grizzco Charger": "Grizzco Charger",
    "Goo Tuber": "Goo Tuber",
    "Custom Goo Tuber": "Custom Goo Tuber",
    "Bamboozler 14 Mk I": "Bamboozler 14 Mk I",
    "Bamboozler 14 Mk II": "Bamboozler 14 Mk II",
    "Bamboozler 14 Mk III": "Bamboozler 14 Mk III",
    "E-liter 4K Scope": "E-liter 4K Scope",
    "Custom E-liter 4K Scope": "Custom E-liter 4K Scope",
    "E-liter 4K": "E-liter 4K",
    "Custom E-liter 4K": "Custom E-liter 4K",
    "Hero Charger": "Hero Charger",
    Splatterscope: "Splatterscope",
    "Firefin Splatterscope": "Firefin Splatterscope",
    "Kensa Splatterscope": "Kensa Splatterscope",
    "Splat Charger": "Splat Charger",
    "Firefin Splat Charger": "Firefin Splat Charger",
    "Kensa Charger": "Kensa Charger",
    "Hero Charger Replica": "Hero Charger Replica",
    "Classic Squiffer": "Classic Squiffer",
    "New Squiffer": "New Squiffer",
    "Fresh Squiffer": "Fresh Squiffer",
    "School Uniform": "School Uniform",
    "Samurai Jacket": "Samurai Jacket",
    "Power Armor": "Power Armor",
    "School Cardigan": "School Cardigan",
    "Squinja Suit": "Squinja Suit",
    "Power Armor Mk I": "Power Armor Mk I",
    "Pearlescent Hoodie": "Pearlescent Hoodie",
    "Marinated Top": "Marinated Top",
    "Enchanted Robe": "Enchanted Robe",
    "Steel Platemail": "Steel Platemail",
    "Fresh Fish Gloves": "Fresh Fish Gloves",
    "Squiddor Polo": "Squiddor Polo",
    "Anchor Life Vest": "Anchor Life Vest",
    "Juice Parka": "Juice Parka",
    "Garden Gear": "Garden Gear",
    "Crustwear XXL": "Crustwear XXL",
    "North-Country Parka": "North-Country Parka",
    "Octoleet Armor": "Octoleet Armor",
    "Record Shop Look EP": "Record Shop Look EP",
    "Dev Uniform": "Dev Uniform",
    "Office Attire": "Office Attire",
    "SRL Coat": "SRL Coat",
    "Mecha Body - AKM": "Mecha Body - AKM",
    "Basic Tee": "Basic Tee",
    "Fresh Octo Tee": "Fresh Octo Tee",
    "Splatfest Tee": "Splatfest Tee",
    "Splatfest Tee Replica": "Splatfest Tee Replica",
    "Olive Ski Jacket": "Olive Ski Jacket",
    "Takoroka Nylon Vintage": "Takoroka Nylon Vintage",
    "Berry Ski Jacket": "Berry Ski Jacket",
    "Varsity Jacket": "Varsity Jacket",
    "School Jersey": "School Jersey",
    "Green Cardigan": "Green Cardigan",
    "Black Inky Rider": "Black Inky Rider",
    "White Inky Rider": "White Inky Rider",
    "Retro Gamer Jersey": "Retro Gamer Jersey",
    "Orange Cardigan": "Orange Cardigan",
    "Forge Inkling Parka": "Forge Inkling Parka",
    "Forge Octarian Jacket": "Forge Octarian Jacket",
    "Blue Sailor Suit": "Blue Sailor Suit",
    "White Sailor Suit": "White Sailor Suit",
    "Squid Satin Jacket": "Squid Satin Jacket",
    "Zapfish Satin Jacket": "Zapfish Satin Jacket",
    "Krak-On 528": "Krak-On 528",
    "Chilly Mountain Coat": "Chilly Mountain Coat",
    "Takoroka Windcrusher": "Takoroka Windcrusher",
    "Matcha Down Jacket": "Matcha Down Jacket",
    "FA-01 Jacket": "FA-01 Jacket",
    "FA-01 Reversed": "FA-01 Reversed",
    "Pullover Coat": "Pullover Coat",
    "Kensa Coat": "Kensa Coat",
    "Birded Corduroy Jacket": "Birded Corduroy Jacket",
    "Deep-Octo Satin Jacket": "Deep-Octo Satin Jacket",
    "Zekko Redleaf Coat": "Zekko Redleaf Coat",
    "Eggplant Mountain Coat": "Eggplant Mountain Coat",
    "Zekko Jade Coat": "Zekko Jade Coat",
    "Light Bomber Jacket": "Light Bomber Jacket",
    "Brown FA-11 Bomber": "Brown FA-11 Bomber",
    "Gray FA-11 Bomber": "Gray FA-11 Bomber",
    "Milky Eminence Jacket": "Milky Eminence Jacket",
    "Navy Eminence Jacket": "Navy Eminence Jacket",
    "Tumeric Zekko Coat": "Tumeric Zekko Coat",
    "Custom Painted F-3 ": "Custom Painted F-3 ",
    "Dark Bomber Jacket": "Dark Bomber Jacket",
    "Moist Ghillie Suit": "Moist Ghillie Suit",
    "White Leather F-3": "White Leather F-3",
    "Chili-Pepper Ski Jacket": "Chili-Pepper Ski Jacket",
    "Whale-Knit Sweater": "Whale-Knit Sweater",
    "Rockin' Leather Jacket": "Rockin' Leather Jacket",
    "Kung-Fu Zip-Up": "Kung-Fu Zip-Up",
    "Panda Kung-Fu Zip-Up": "Panda Kung-Fu Zip-Up",
    "Sennyu Suit": "Sennyu Suit",
    "Hero Jacket Replica": "Hero Jacket Replica",
    "Armor Jacket Replica": "Armor Jacket Replica",
    "Hero Hoodie Replica": "Hero Hoodie Replica",
    "Neo Octoling Armor": "Neo Octoling Armor",
    "Null Armor Replica": "Null Armor Replica",
    "Old-Timey Clothes": "Old-Timey Clothes",
    "Shrimp-Pink Polo": "Shrimp-Pink Polo",
    "Striped Rugby": "Striped Rugby",
    "Tricolor Rugby": "Tricolor Rugby",
    "Sage Polo": "Sage Polo",
    "Black Polo": "Black Polo",
    "Cycling Shirt": "Cycling Shirt",
    "Cycle King Jersey": "Cycle King Jersey",
    "Slipstream United": "Slipstream United",
    "FC Albacore": "FC Albacore",
    "Camo Zip Hoodie": "Camo Zip Hoodie",
    "Green Zip Hoodie": "Green Zip Hoodie",
    "Zekko Hoodie": "Zekko Hoodie",
    "Shirt with Blue Hoodie": "Shirt with Blue Hoodie",
    "Grape Hoodie": "Grape Hoodie",
    "Gray Hoodie": "Gray Hoodie",
    "Hothouse Hoodie": "Hothouse Hoodie",
    "Pink Hoodie": "Pink Hoodie",
    "Olive Zekko Parka": "Olive Zekko Parka",
    "Black Hoodie": "Black Hoodie",
    "Octo Support Hoodie": "Octo Support Hoodie",
    "Octoling Armor": "Octoling Armor",
    "Lumberjack Shirt": "Lumberjack Shirt",
    "Rodeo Shirt": "Rodeo Shirt",
    "Green-Check Shirt": "Green-Check Shirt",
    "White Shirt": "White Shirt",
    "Urchins Jersey": "Urchins Jersey",
    "Aloha Shirt": "Aloha Shirt",
    "Red-Check Shirt": "Red-Check Shirt",
    "Baby-Jelly Shirt": "Baby-Jelly Shirt",
    "Baseball Jersey": "Baseball Jersey",
    "Gray Mixed Shirt": "Gray Mixed Shirt",
    "Vintage Check Shirt": "Vintage Check Shirt",
    "Round-Collar Shirt": "Round-Collar Shirt",
    "Logo Aloha Shirt": "Logo Aloha Shirt",
    "Striped Shirt": "Striped Shirt",
    "Linen Shirt": "Linen Shirt",
    "Shirt & Tie": "Shirt & Tie",
    "Hula Punk Shirt": "Hula Punk Shirt",
    "Octobowler Shirt": "Octobowler Shirt",
    "Inkfall Shirt": "Inkfall Shirt",
    "Crimson Parashooter": "Crimson Parashooter",
    "Baby-Jelly Shirt & Tie": "Baby-Jelly Shirt & Tie",
    "Prune Parashooter": "Prune Parashooter",
    "Red Hula Punk with Tie": "Red Hula Punk with Tie",
    "Chili Octo Aloha": "Chili Octo Aloha",
    "Annaki Flannel Hoodie": "Annaki Flannel Hoodie",
    "Ink-Wash Shirt": "Ink-Wash Shirt",
    "Dots-On-Dots Shirt": "Dots-On-Dots Shirt",
    "Toni K. Baseball Jersey": "Toni K. Baseball Jersey",
    "Online Jersey": "Online Jersey",
    "Gray College Sweat": "Gray College Sweat",
    "Squidmark Sweat": "Squidmark Sweat",
    "Retro Sweat": "Retro Sweat",
    "Firefin Navy Sweat": "Firefin Navy Sweat",
    "Navy College Sweat": "Navy College Sweat",
    "Reel Sweat": "Reel Sweat",
    "Anchor Sweat": "Anchor Sweat",
    "Negative Longcuff Sweater": "Negative Longcuff Sweater",
    "Short Knit Layers": "Short Knit Layers",
    "Positive Longcuff Sweater": "Positive Longcuff Sweater",
    "Annaki Blue Cuff": "Annaki Blue Cuff",
    "Annaki Yellow Cuff": "Annaki Yellow Cuff",
    "Annaki Red Cuff": "Annaki Red Cuff",
    "N-Pacer Sweat": "N-Pacer Sweat",
    "Octarian Retro": "Octarian Retro",
    "Takoroka Jersey": "Takoroka Jersey",
    "White Striped LS": "White Striped LS",
    "Black LS": "Black LS",
    "Purple Camo LS": "Purple Camo LS",
    "Navy Striped LS": "Navy Striped LS",
    "Zekko Baseball LS": "Zekko Baseball LS",
    "Varsity Baseball LS": "Varsity Baseball LS",
    "Black Baseball LS": "Black Baseball LS",
    "White Baseball LS": "White Baseball LS",
    "White LS": "White LS",
    "Green Striped LS": "Green Striped LS",
    "Squidmark LS": "Squidmark LS",
    "Zink LS": "Zink LS",
    "Striped Peaks LS": "Striped Peaks LS",
    "Pink Easy-Stripe Shirt": "Pink Easy-Stripe Shirt",
    "Inkopolis Squaps Jersey": "Inkopolis Squaps Jersey",
    "Annaki Drive Tee ": "Annaki Drive Tee ",
    "Lime Easy-Stripe Shirt": "Lime Easy-Stripe Shirt",
    "Annaki Evolution Tee": "Annaki Evolution Tee",
    "Zekko Long Carrot Tee": "Zekko Long Carrot Tee",
    "Zekko Long Radish Tee": "Zekko Long Radish Tee",
    "Black Cuttlegear LS": "Black Cuttlegear LS",
    "Takoroka Crazy Baseball LS": "Takoroka Crazy Baseball LS",
    "Red Cuttlegear LS": "Red Cuttlegear LS",
    "Khaki 16-Bit FishFry": "Khaki 16-Bit FishFry",
    "Blue 16-Bit FishFry": "Blue 16-Bit FishFry",
    "White Tee": "White Tee",
    "Black Squideye": "Black Squideye",
    "Sky-Blue Squideye": "Sky-Blue Squideye",
    "Rockenberg White": "Rockenberg White",
    "Rockenberg Black": "Rockenberg Black",
    "Black Tee": "Black Tee",
    "Sunny-Day Tee": "Sunny-Day Tee",
    "Rainy-Day Tee": "Rainy-Day Tee",
    "Reggae Tee": "Reggae Tee",
    "Fugu Tee": "Fugu Tee",
    "Mint Tee": "Mint Tee",
    "Grape Tee": "Grape Tee",
    "Red Vector Tee": "Red Vector Tee",
    "Gray Vector Tee": "Gray Vector Tee",
    "Blue Peaks Tee": "Blue Peaks Tee",
    "Ivory Peaks Tee": "Ivory Peaks Tee",
    "Squid-Stitch Tee": "Squid-Stitch Tee",
    "Pirate-Stripe Tee": "Pirate-Stripe Tee",
    "Sailor-Stripe Tee": "Sailor-Stripe Tee",
    "White 8-Bit FishFry": "White 8-Bit FishFry",
    "Black 8-Bit FishFry": "Black 8-Bit FishFry",
    "White Anchor Tee": "White Anchor Tee",
    "Black Anchor Tee": "Black Anchor Tee",
    "Carnivore Tee": "Carnivore Tee",
    "Pearl Tee": "Pearl Tee",
    "Octo Tee": "Octo Tee",
    "Herbivore Tee": "Herbivore Tee",
    "Black V-Neck Tee": "Black V-Neck Tee",
    "White Deca Logo Tee": "White Deca Logo Tee",
    "Half-Sleeve Sweater": "Half-Sleeve Sweater",
    "King Jersey": "King Jersey",
    "Gray 8-Bit FishFry": "Gray 8-Bit FishFry",
    "White V-Neck Tee": "White V-Neck Tee",
    "White Urchin Rock Tee": "White Urchin Rock Tee",
    "Black Urchin Rock Tee": "Black Urchin Rock Tee",
    "Wet Floor Band Tee": "Wet Floor Band Tee",
    "Squid Squad Band Tee": "Squid Squad Band Tee",
    "Navy Deca Logo Tee": "Navy Deca Logo Tee",
    "Mister Shrug Tee": "Mister Shrug Tee",
    "Chirpy Chips Band Tee": "Chirpy Chips Band Tee",
    "Hightide Era Band Tee": "Hightide Era Band Tee",
    "Red V-Neck Limited Tee": "Red V-Neck Limited Tee",
    "Green V-Neck Limited Tee": "Green V-Neck Limited Tee",
    "\u03c9-3 Tee": "\u03c9-3 Tee",
    "Annaki Polpo-Pic Tee": "Annaki Polpo-Pic Tee",
    "Firewave Tee": "Firewave Tee",
    "Takoroka Galactic Tie Dye": "Takoroka Galactic Tie Dye",
    "Takoroka Rainbow Tie Dye": "Takoroka Rainbow Tie Dye",
    "Missus Shrug Tee": "Missus Shrug Tee",
    "League Tee": "League Tee",
    "Friend Tee": "Friend Tee",
    "Tentatek Slogan Tee": "Tentatek Slogan Tee",
    "Icewave Tee": "Icewave Tee",
    "Octoking HK Jersey": "Octoking HK Jersey",
    "Dakro Nana Tee": "Dakro Nana Tee",
    "Dakro Golden Tee": "Dakro Golden Tee",
    "Black Velour Octoking Tee ": "Black Velour Octoking Tee ",
    "Green Velour Octoking Tee": "Green Velour Octoking Tee",
    "SWC Logo Tee": "SWC Logo Tee",
    "White Layered LS": "White Layered LS",
    "Yellow Layered LS": "Yellow Layered LS",
    "Camo Layered LS": "Camo Layered LS",
    "Black Layered LS": "Black Layered LS",
    "Zink Layered LS": "Zink Layered LS",
    "Layered Anchor LS": "Layered Anchor LS",
    "Choco Layered LS": "Choco Layered LS",
    "Part-Time Pirate": "Part-Time Pirate",
    "Layered Vector LS": "Layered Vector LS",
    "Green Tee": "Green Tee",
    "Red Tentatek Tee": "Red Tentatek Tee",
    "Blue Tentatek Tee": "Blue Tentatek Tee",
    "Octo Layered LS": "Octo Layered LS",
    "Squid Yellow Layered LS": "Squid Yellow Layered LS",
    "B-ball Jersey (Home)": "B-ball Jersey (Home)",
    "B-ball Jersey (Away)": "B-ball Jersey (Away)",
    "White King Tank": "White King Tank",
    "Slash King Tank": "Slash King Tank",
    "Navy King Tank": "Navy King Tank",
    "Lob-Stars Jersey": "Lob-Stars Jersey",
    "Mountain Vest": "Mountain Vest",
    "Forest Vest": "Forest Vest",
    "Dark Urban Vest": "Dark Urban Vest",
    "Yellow Urban Vest": "Yellow Urban Vest",
    "Squid-Pattern Waistcoat": "Squid-Pattern Waistcoat",
    "Squidstar Waistcoat": "Squidstar Waistcoat",
    "Fishing Vest": "Fishing Vest",
    "Front Zip Vest": "Front Zip Vest",
    "Silver Tentatek Vest": "Silver Tentatek Vest",
    Comeback: "Comeback",
    Haunt: "Haunt",
    Durability: "Durability",
    "Last-Ditch Effort": "Last-Ditch Effort",
    "Ability Doubler": "Ability Doubler",
    "Respawn Punisher": "Respawn Punisher",
    Impact: "Impact",
    "Squid Beakon": "Squid Beakon",
    "Port Mackerel": "Port Mackerel",
    "Camp Triggerfish": "Camp Triggerfish",
    "Wahoo World": "Wahoo World",
    "Goby Arena": "Goby Arena",
    "Windmill House on the Pearlie": "Windmill House on the Pearlie",
    "Wayslide Cool": "Wayslide Cool",
    "The Secret of S.P.L.A.T.": "The Secret of S.P.L.A.T.",
    Goosponge: "Goosponge",
    "Cannon Fire Pearl": "Cannon Fire Pearl",
    "Zone of Glass": "Zone of Glass",
    "Fancy Spew": "Fancy Spew",
    "Grapplink Girl": "Grapplink Girl",
    "Zappy Longshocking": "Zappy Longshocking",
    "The Bunker Games": "The Bunker Games",
    "A Swiftly Tilting Balance": "A Swiftly Tilting Balance",
    "The Switches": "The Switches",
    "Sweet Valley Tentacles": "Sweet Valley Tentacles",
    "The Bouncey Twins": "The Bouncey Twins",
    "Railway Chillin'": "Railway Chillin'",
    "Gusher Towns": "Gusher Towns",
    "The Maze Dasher": "The Maze Dasher",
    "Flooders in the Attic": "Flooders in the Attic",
    "The Splat in our Zones": "The Splat in our Zones",
    "The Ink is Spreading": "The Ink is Spreading",
    "Bridge to Tentaswitchia": "Bridge to Tentaswitchia",
    "The Chronicles of Rolonium": "The Chronicles of Rolonium",
    "Furler in the Ashes": "Furler in the Ashes",
    "MC.Princess Diaries": "MC.Princess Diaries",
    "Shifty Station": "Shifty Station",
    "The Reef": "The Reef",
    "Snapper Canal": "Snapper Canal",
    MakoMart: "MakoMart",
    "Kelp Dome": "Kelp Dome",
    "Skipper Pavilion": "Skipper Pavilion",
    "Sturgeon Shipyard": "Sturgeon Shipyard",
    "New Albacore Hotel": "New Albacore Hotel",
    "Ancho-V Games": "Ancho-V Games",
    "Manta Maria": "Manta Maria",
    "Piranha Pit": "Piranha Pit",
    "Lost Outpost": "Lost Outpost",
    "Salmonid Smokeyard": "Salmonid Smokeyard",
    "Ruins of Ark Polaris": "Ruins of Ark Polaris",
    "Marooner's Bay": "Marooner's Bay",
    "Spawning Grounds": "Spawning Grounds",
    "Blackbelly Skatepark": "Blackbelly Skatepark",
    "Shellendorf Institute": "Shellendorf Institute",
    "Moray Towers": "Moray Towers",
    "Musselforge Fitness": "Musselforge Fitness",
    "Arowana Mall": "Arowana Mall",
    "Inkblot Art Academy": "Inkblot Art Academy",
    "Starfish Mainstage": "Starfish Mainstage",
    "Walleye Warehouse": "Walleye Warehouse",
    "Humpback Pump Track": "Humpback Pump Track",
    "Eminence Cuff": "Eminence Cuff",
    "Squid Hairclip": "Squid Hairclip",
    "Samurai Helmet": "Samurai Helmet",
    "Power Mask": "Power Mask",
    "Squid Clip-Ons": "Squid Clip-Ons",
    "Squinja Mask": "Squinja Mask",
    "Power Mask Mk I": "Power Mask Mk I",
    "Pearlescent Crown": "Pearlescent Crown",
    "Marinated Headphones": "Marinated Headphones",
    "Enchanted Hat": "Enchanted Hat",
    "Steel Helm": "Steel Helm",
    "Fresh Fish Head": "Fresh Fish Head",
    "Urchins Cap": "Urchins Cap",
    "Lightweight Cap": "Lightweight Cap",
    "Takoroka Mesh": "Takoroka Mesh",
    "Streetstyle Cap": "Streetstyle Cap",
    "Squid-Stitch Cap": "Squid-Stitch Cap",
    "Squidvader Cap": "Squidvader Cap",
    "Camo Mesh": "Camo Mesh",
    "Five-Panel Cap": "Five-Panel Cap",
    "Zekko Mesh": "Zekko Mesh",
    "Backwards Cap": "Backwards Cap",
    "Two-Stripe Mesh": "Two-Stripe Mesh",
    "Jet Cap": "Jet Cap",
    "Cycling Cap": "Cycling Cap",
    "Cycle King Cap": "Cycle King Cap",
    "Legendary Cap": "Legendary Cap",
    "Long-Billed Cap": "Long-Billed Cap",
    "King Flip Mesh": "King Flip Mesh",
    "Hickory Work Cap": "Hickory Work Cap",
    "Woolly Urchins Classic": "Woolly Urchins Classic",
    "Jellyvader Cap": "Jellyvader Cap",
    "House-Tag Denim Cap": "House-Tag Denim Cap",
    "Blowfish Newsie": "Blowfish Newsie",
    "Do-Rag, Cap, & Glasses": "Do-Rag, Cap, & Glasses",
    "Pilot Hat": "Pilot Hat",
    "Headlamp Helmet": "Headlamp Helmet",
    "Dust Blocker 2000": "Dust Blocker 2000",
    "Welding Mask": "Welding Mask",
    "Beekeeper Hat": "Beekeeper Hat",
    "Octoleet Goggles": "Octoleet Goggles",
    "Cap of Legend": "Cap of Legend",
    "Oceanic Hard Hat": "Oceanic Hard Hat",
    "Worker's Head Towel": "Worker's Head Towel",
    "Worker's Cap": "Worker's Cap",
    "Sailor Cap": "Sailor Cap",
    "Mecha Head - HTR": "Mecha Head - HTR",
    "Retro Specs": "Retro Specs",
    "Splash Goggles": "Splash Goggles",
    "Pilot Goggles": "Pilot Goggles",
    "Tinted Shades": "Tinted Shades",
    "Black Arrowbands": "Black Arrowbands",
    "Snorkel Mask": "Snorkel Mask",
    "White Arrowbands": "White Arrowbands",
    "Fake Contacts": "Fake Contacts",
    "18K Aviators": "18K Aviators",
    "Full Moon Glasses": "Full Moon Glasses",
    Octoglasses: "Octoglasses",
    "Half-Rim Glasses": "Half-Rim Glasses",
    "Double Egg Shades": "Double Egg Shades",
    "Zekko Cap": "Zekko Cap",
    "SV925 Circle Shades": "SV925 Circle Shades",
    "Annaki Beret & Glasses": "Annaki Beret & Glasses",
    "Swim Goggles": "Swim Goggles",
    "Ink-Guard Goggles": "Ink-Guard Goggles",
    "Toni Kensa Goggles": "Toni Kensa Goggles",
    "Sennyu Goggles": "Sennyu Goggles",
    "Sennyu Specs": "Sennyu Specs",
    "White Headband": "White Headband",
    "Kyonshi Hat": "Kyonshi Hat",
    "Li'l Devil Horns": "Li'l Devil Horns",
    "Hockey Mask": "Hockey Mask",
    "Anglerfish Mask": "Anglerfish Mask",
    "Festive Party Cone": "Festive Party Cone",
    "New Year's Glasses DX": "New Year's Glasses DX",
    "Twisty Headband": "Twisty Headband",
    "Eel-Cake Hat": "Eel-Cake Hat",
    "Purple Novelty Visor": "Purple Novelty Visor",
    "Green Novelty Visor": "Green Novelty Visor",
    "Orange Novelty Visor": "Orange Novelty Visor",
    "Pink Novelty Visor": "Pink Novelty Visor",
    "Jetflame Crest": "Jetflame Crest",
    "Fierce Fishskull": "Fierce Fishskull",
    "Hivemind Antenna": "Hivemind Antenna",
    "Eye of Justice": "Eye of Justice",
    "Safari Hat": "Safari Hat",
    "Jungle Hat": "Jungle Hat",
    "Camping Hat": "Camping Hat",
    "Blowfish Bell Hat": "Blowfish Bell Hat",
    "Bamboo Hat": "Bamboo Hat",
    "Straw Boater": "Straw Boater",
    "Classic Straw Boater": "Classic Straw Boater",
    "Treasure Hunter": "Treasure Hunter",
    "Bucket Hat": "Bucket Hat",
    "Patched Hat": "Patched Hat",
    "Tulip Parasol": "Tulip Parasol",
    "Fugu Bell Hat": "Fugu Bell Hat",
    "Seashell Bamboo Hat": "Seashell Bamboo Hat",
    "Hothouse Hat": "Hothouse Hat",
    "Mountie Hat": "Mountie Hat",
    "B-ball Headband": "B-ball Headband",
    "Squash Headband": "Squash Headband",
    "Tennis Headband": "Tennis Headband",
    "Jogging Headband": "Jogging Headband",
    "Soccer Headband": "Soccer Headband",
    "FishFry Biscuit Bandana": "FishFry Biscuit Bandana",
    "Black FishFry Bandana": "Black FishFry Bandana",
    "Studio Headphones": "Studio Headphones",
    "Designer Headphones": "Designer Headphones",
    "Noise Cancelers": "Noise Cancelers",
    "Squidfin Hook Cans": "Squidfin Hook Cans",
    "Squidlife Headphones": "Squidlife Headphones",
    "Studio Octophones": "Studio Octophones",
    "Sennyu Headphones": "Sennyu Headphones",
    "Bike Helmet": "Bike Helmet",
    "Stealth Goggles": "Stealth Goggles",
    "Tentacles Helmet": "Tentacles Helmet",
    "Skate Helmet": "Skate Helmet",
    "Visor Skate Helmet": "Visor Skate Helmet",
    "MTB Helmet": "MTB Helmet",
    "Hockey Helmet": "Hockey Helmet",
    "Matte Bike Helmet": "Matte Bike Helmet",
    "Octo Tackle Helmet Deco": "Octo Tackle Helmet Deco",
    "Moist Ghillie Helmet": "Moist Ghillie Helmet",
    "Deca Tackle Visor Helmet": "Deca Tackle Visor Helmet",
    "Gas Mask": "Gas Mask",
    "Paintball Mask": "Paintball Mask",
    "Paisley Bandana": "Paisley Bandana",
    "Skull Bandana": "Skull Bandana",
    "Painter's Mask": "Painter's Mask",
    "Annaki Mask": "Annaki Mask",
    "Octoking Facemask": "Octoking Facemask",
    "Squid Facemask": "Squid Facemask",
    "Firefin Facemask": "Firefin Facemask",
    "King Facemask": "King Facemask",
    "Motocross Nose Guard": "Motocross Nose Guard",
    "Forge Mask": "Forge Mask",
    "Digi-Camo Forge Mask": "Digi-Camo Forge Mask",
    "Koshien Bandana": "Koshien Bandana",
    "Hero Headset Replica": "Hero Headset Replica",
    "Armor Helmet Replica": "Armor Helmet Replica",
    "Hero Headphones Replica": "Hero Headphones Replica",
    "Octoling Shades": "Octoling Shades",
    "Null Visor Replica": "Null Visor Replica",
    "Old-Timey Hat": "Old-Timey Hat",
    "Conductor Cap": "Conductor Cap",
    "Golden Toothpick": "Golden Toothpick",
    "Bobble Hat": "Bobble Hat",
    "Short Beanie": "Short Beanie",
    "Striped Beanie": "Striped Beanie",
    "Sporty Bobble Hat": "Sporty Bobble Hat",
    "Special Forces Beret": "Special Forces Beret",
    "Squid Nordic": "Squid Nordic",
    "Sennyu Bon Bon Beanie": "Sennyu Bon Bon Beanie",
    "Knitted Hat": "Knitted Hat",
    "Annaki Beret": "Annaki Beret",
    "Yamagiri Beanie": "Yamagiri Beanie",
    "Sneaky Beanie": "Sneaky Beanie",
    "Octoling Goggles": "Octoling Goggles",
    "Golf Visor": "Golf Visor",
    "FishFry Visor": "FishFry Visor",
    "Sun Visor": "Sun Visor",
    "Takoroka Visor": "Takoroka Visor",
    "Face Visor": "Face Visor",
    "Run Speed Up": "Run Speed Up",
    "Ink Recovery Up": "Ink Recovery Up",
    Inkjet: "Inkjet",
    "Quick Super Jump": "Quick Super Jump",
    "Curling-Bomb Launcher": "Curling-Bomb Launcher",
    "Burst-Bomb Launcher": "Burst-Bomb Launcher",
    "Autobomb Launcher": "Autobomb Launcher",
    "Splat-Bomb Launcher": "Splat-Bomb Launcher",
    "Suction-Bomb Launcher": "Suction-Bomb Launcher",
    "Slightly increases\nmovement speed\nwhile inking.":
      "Slightly increases\nmovement speed\nwhile inking.",
    "Increases Brella\ncanopy durability.":
      "Increases Brella\ncanopy durability.",
    "Speeds up Brella\ncanopy regeneration.":
      "Speeds up Brella\ncanopy regeneration.",
    "Increases high-damage\nradius of explosions.":
      "Increases high-damage\nradius of explosions.",
    "Increases maximum\ndamage range.": "Increases maximum\ndamage range.",
    "Increases damage.": "Increases damage.",
    "Increases ink coverage.": "Increases ink coverage.",
    "Slightly increases range.": "Slightly increases range.",
    "Increases shot accuracy\nwhen firing while jumping.":
      "Increases shot accuracy\nwhen firing while jumping.",
    "Increases duration of\nfiring in a burst.":
      "Increases duration of\nfiring in a burst.",
    "Ink Saver (Main)": "Ink Saver (Main)",
    "Main Power Up": "Main Power Up",
    Tenacity: "Tenacity",
    Cannon: "Cannon",
    Mobility: "Mobility",
    "Object Shredder": "Object Shredder",
    "Ink Resistance Up": "Ink Resistance Up",
    "Ink Speed": "Ink Speed",
    "Point Sensor": "Point Sensor",
    "Toxic Mist": "Toxic Mist",
    Damage: "Damage",
    "Ink Storm": "Ink Storm",
    Range: "Range",
    "Special Saver": "Special Saver",
    "Quick Respawn": "Quick Respawn",
    Inkbrush: "Inkbrush",
    "Inkbrush Nouveau": "Inkbrush Nouveau",
    "Permanent Inkbrush": "Permanent Inkbrush",
    Octobrush: "Octobrush",
    "Octobrush Nouveau": "Octobrush Nouveau",
    "Kensa Octobrush": "Kensa Octobrush",
    "Herobrush Replica": "Herobrush Replica",
    "Carbon Roller": "Carbon Roller",
    "Carbon Roller Deco": "Carbon Roller Deco",
    "Dynamo Roller": "Dynamo Roller",
    "Gold Dynamo Roller": "Gold Dynamo Roller",
    "Kensa Dynamo Roller": "Kensa Dynamo Roller",
    "Flingza Roller": "Flingza Roller",
    "Foil Flingza Roller": "Foil Flingza Roller",
    Herobrush: "Herobrush",
    "Hero Roller": "Hero Roller",
    "Splat Roller": "Splat Roller",
    "Krak-On Splat Roller": "Krak-On Splat Roller",
    "Kensa Splat Roller": "Kensa Splat Roller",
    "Hero Roller Replica": "Hero Roller Replica",
    "Reduces damage taken by\nblasts from non-main\nweapons, and reduces\nthe time you're tracked.":
      "Reduces damage taken by\nblasts from non-main\nweapons, and reduces\nthe time you're tracked.",
    "Upgrades your\nsub weapon.": "Upgrades your\nsub weapon.",
    "Boosts some of your\nabilities for a short\ntime after respawning.":
      "Boosts some of your\nabilities for a short\ntime after respawning.",
    "Once you've respawned,\nreveals the position of\nplayers who've splatted\nyou.":
      "Once you've respawned,\nreveals the position of\nplayers who've splatted\nyou.",
    "Boosts ink recovery\nrate and weapon ink\nefficiency for the last\n30 seconds of battle.":
      "Boosts ink recovery\nrate and weapon ink\nefficiency for the last\n30 seconds of battle.",
    "Doubles the effect of\nother gear abilities\nattached to this gear.":
      "Doubles the effect of\nother gear abilities\nattached to this gear.",
    "Increases respawn time\nand special-gauge spawn\npenalty for you and any\nplayer you splat.":
      "Increases respawn time\nand special-gauge spawn\npenalty for you and any\nplayer you splat.",
    "Increases movement\nspeed in Inkling form.":
      "Increases movement\nspeed in Inkling form.",
    "Increases ink-tank refill\nrate.": "Increases ink-tank refill\nrate.",
    "Increases Super Jump\nspeed.": "Increases Super Jump\nspeed.",
    "Decreases amount\nof ink consumed by\nyour main weapon.":
      "Decreases amount\nof ink consumed by\nyour main weapon.",
    "[\u000e\u0004\u0000\u0004\u0000\ucd00]\n\u000e\u0004\u0005\u0000":
      "[\u000e\u0004\u0000\u0004\u0000\ucd00]\n\u000e\u0004\u0005\u0000",
    "Upgrades your\nmain weapon.": "Upgrades your\nmain weapon.",
    "Fills special gauge\nautomatically if your\nteam has fewer active\nplayers than the enemy.":
      "Fills special gauge\nautomatically if your\nteam has fewer active\nplayers than the enemy.",
    "Increases damage dealt\nto all non-player targets.":
      "Increases damage dealt\nto all non-player targets.",
    "Reduces damage taken\nand improves mobility\nwhen walking through\nenemy ink.":
      "Reduces damage taken\nand improves mobility\nwhen walking through\nenemy ink.",
    "Reduces special-gauge\ndecrease after getting\nsplatted.":
      "Reduces special-gauge\ndecrease after getting\nsplatted.",
    "Reduces respawn time\nafter getting splatted\nrepeatedly without\nsplatting any opponents.":
      "Reduces respawn time\nafter getting splatted\nrepeatedly without\nsplatting any opponents.",
    "Tilting the L Stick during\na Super Jump allows you\nto perform a roll in that\ndirection when landing.":
      "Tilting the L Stick during\na Super Jump allows you\nto perform a roll in that\ndirection when landing.",
    "Increases special-\ngauge fill rate.":
      "Increases special-\ngauge fill rate.",
    "Upgrades your\nspecial weapon.": "Upgrades your\nspecial weapon.",
    "Leaves no trace when\nswimming in inked\nground, but slightly\nreduces swim speed.":
      "Leaves no trace when\nswimming in inked\nground, but slightly\nreduces swim speed.",
    "Increases movement\nspeed in squid form.":
      "Increases movement\nspeed in squid form.",
    "Boosts your speed while\nmoving for the first 30\nseconds of battle.":
      "Boosts your speed while\nmoving for the first 30\nseconds of battle.",
    "Decreases amount\nof ink consumed by\nyour sub weapon.":
      "Decreases amount\nof ink consumed by\nyour sub weapon.",
    "Hides your Super Jump\nlanding point from\ndistant players.":
      "Hides your Super Jump\nlanding point from\ndistant players.",
    "Allows you to track\ndistant players hit with\nshots from your main\nweapon.":
      "Allows you to track\ndistant players hit with\nshots from your main\nweapon.",
    "Unlock this ability by\nbattling while wearing\nthis gear.":
      "Unlock this ability by\nbattling while wearing\nthis gear.",
    Rainmaker: "Rainmaker",
    "Splash Wall": "Splash Wall",
    "Grizzco Blaster": "Grizzco Blaster",
    "Rapid Blaster Pro": "Rapid Blaster Pro",
    "Rapid Blaster Pro Deco": "Rapid Blaster Pro Deco",
    "Clash Blaster": "Clash Blaster",
    "Clash Blaster Neo": "Clash Blaster Neo",
    "Rapid Blaster": "Rapid Blaster",
    "Rapid Blaster Deco": "Rapid Blaster Deco",
    "Kensa Rapid Blaster": "Kensa Rapid Blaster",
    "Range Blaster": "Range Blaster",
    "Custom Range Blaster": "Custom Range Blaster",
    "Grim Range Blaster": "Grim Range Blaster",
    Blaster: "Blaster",
    "Custom Blaster": "Custom Blaster",
    "Hero Blaster Replica": "Hero Blaster Replica",
    "Hero Blaster": "Hero Blaster",
    "Luna Blaster": "Luna Blaster",
    "Luna Blaster Neo": "Luna Blaster Neo",
    "Kensa Luna Blaster": "Kensa Luna Blaster",
    "Aerospray MG": "Aerospray MG",
    "Aerospray RG": "Aerospray RG",
    "Aerospray PG": "Aerospray PG",
    "Splattershot Pro": "Splattershot Pro",
    "Forge Splattershot Pro": "Forge Splattershot Pro",
    "Kensa Splattershot Pro": "Kensa Splattershot Pro",
    "Splattershot Jr.": "Splattershot Jr.",
    "Custom Splattershot Jr.": "Custom Splattershot Jr.",
    "Kensa Splattershot Jr.": "Kensa Splattershot Jr.",
    Squeezer: "Squeezer",
    "Foil Squeezer": "Foil Squeezer",
    ".52 Gal": ".52 Gal",
    ".52 Gal Deco": ".52 Gal Deco",
    "Kensa .52 Gal": "Kensa .52 Gal",
    ".96 Gal": ".96 Gal",
    ".96 Gal Deco": ".96 Gal Deco",
    "Jet Squelcher": "Jet Squelcher",
    "Custom Jet Squelcher": "Custom Jet Squelcher",
    "Hero Shot": "Hero Shot",
    Splattershot: "Splattershot",
    "Tentatek Splattershot": "Tentatek Splattershot",
    "Kensa Splattershot": "Kensa Splattershot",
    "Hero Shot Replica": "Hero Shot Replica",
    "Octo Shot Replica": "Octo Shot Replica",
    "Splash-o-matic": "Splash-o-matic",
    "Neo Splash-o-matic": "Neo Splash-o-matic",
    "N-ZAP '85": "N-ZAP '85",
    "N-ZAP '89": "N-ZAP '89",
    "N-ZAP '83": "N-ZAP '83",
    "Sploosh-o-matic": "Sploosh-o-matic",
    "Neo Sploosh-o-matic": "Neo Sploosh-o-matic",
    "Sploosh-o-matic 7": "Sploosh-o-matic 7",
    "H-3 Nozzlenose": "H-3 Nozzlenose",
    "H-3 Nozzlenose D": "H-3 Nozzlenose D",
    "Cherry H-3 Nozzlenose": "Cherry H-3 Nozzlenose",
    "L-3 Nozzlenose": "L-3 Nozzlenose",
    "L-3 Nozzlenose D": "L-3 Nozzlenose D",
    "Kensa L-3 Nozzlenose": "Kensa L-3 Nozzlenose",
    "School Shoes": "School Shoes",
    "Samurai Shoes": "Samurai Shoes",
    "Power Boots": "Power Boots",
    "Fringed Loafers": "Fringed Loafers",
    "Squinja Boots": "Squinja Boots",
    "Power Boots Mk I": "Power Boots Mk I",
    "Pearlescent Kicks": "Pearlescent Kicks",
    "Marinated Slip-Ons": "Marinated Slip-Ons",
    "Enchanted Boots": "Enchanted Boots",
    "Steel Greaves": "Steel Greaves",
    "Fresh Fish Feet": "Fresh Fish Feet",
    "Moto Boots": "Moto Boots",
    "Tan Work Boots": "Tan Work Boots",
    "Red Work Boots": "Red Work Boots",
    "Blue Moto Boots": "Blue Moto Boots",
    "Green Rain Boots": "Green Rain Boots",
    "Acerola Rain Boots": "Acerola Rain Boots",
    "Punk Whites": "Punk Whites",
    "Punk Cherries": "Punk Cherries",
    "Punk Yellows": "Punk Yellows",
    "Bubble Rain Boots": "Bubble Rain Boots",
    "Snowy Down Boots": "Snowy Down Boots",
    "Icy Down Boots": "Icy Down Boots",
    "Hunting Boots": "Hunting Boots",
    "Punk Blacks": "Punk Blacks",
    "Deepsea Leather Boots": "Deepsea Leather Boots",
    "Moist Ghillie Boots": "Moist Ghillie Boots",
    "Annaki Arachno Boots": "Annaki Arachno Boots",
    "New-Leaf Leather Boots": "New-Leaf Leather Boots",
    "Tea-Green Hunting Boots": "Tea-Green Hunting Boots",
    "Blueberry Casuals": "Blueberry Casuals",
    "Plum Casuals": "Plum Casuals",
    "Angry Rain Boots": "Angry Rain Boots",
    "Non-slip Senseis": "Non-slip Senseis",
    "Octoleet Boots": "Octoleet Boots",
    "Friendship Bracelet": "Friendship Bracelet",
    "Flipper Floppers": "Flipper Floppers",
    "Wooden Sandals": "Wooden Sandals",
    "Mecha Legs - LBS": "Mecha Legs - LBS",
    "Cream Basics": "Cream Basics",
    "Pearl-Scout Lace-Ups": "Pearl-Scout Lace-Ups",
    "Pearlescent Squidkid IV": "Pearlescent Squidkid IV",
    "Pearl Punk Crowns": "Pearl Punk Crowns",
    "New-Day Arrows": "New-Day Arrows",
    "Marination Lace-Ups": "Marination Lace-Ups",
    "Rina Squidkid IV": "Rina Squidkid IV",
    "Trooper Power Stripes": "Trooper Power Stripes",
    "Midnight Slip-Ons": "Midnight Slip-Ons",
    "White Kicks": "White Kicks",
    "Cherry Kicks": "Cherry Kicks",
    "Turquoise Kicks": "Turquoise Kicks",
    "Squink Wingtips": "Squink Wingtips",
    "Roasted Brogues": "Roasted Brogues",
    "Kid Clams": "Kid Clams",
    "Smoky Wingtips": "Smoky Wingtips",
    "Navy Red-Soled Wingtips": "Navy Red-Soled Wingtips",
    "Gray Yellow-Soled Wingtips": "Gray Yellow-Soled Wingtips",
    "Inky Kid Clams": "Inky Kid Clams",
    "Annaki Habaneros": "Annaki Habaneros",
    "Annaki Tigers": "Annaki Tigers",
    "Sennyu Inksoles": "Sennyu Inksoles",
    "Hero Runner Replicas": "Hero Runner Replicas",
    "Armor Boot Replicas": "Armor Boot Replicas",
    "Hero Snowboots Replicas": "Hero Snowboots Replicas",
    "Neo Octoling Boots": "Neo Octoling Boots",
    "Null Boots Replica": "Null Boots Replica",
    "Old-Timey Shoes": "Old-Timey Shoes",
    "Octoling Boots": "Octoling Boots",
    "Oyster Clogs": "Oyster Clogs",
    "Choco Clogs": "Choco Clogs",
    "Neon Delta Straps": "Neon Delta Straps",
    "Black Flip-Flops": "Black Flip-Flops",
    "Snow Delta Straps": "Snow Delta Straps",
    "Luminous Delta Straps": "Luminous Delta Straps",
    "Red FishFry Sandals": "Red FishFry Sandals",
    "Yellow FishFry Sandals": "Yellow FishFry Sandals",
    "Musselforge Flip-Flops": "Musselforge Flip-Flops",
    "Red Hi-Horses": "Red Hi-Horses",
    "Zombie Hi-Horses": "Zombie Hi-Horses",
    "Cream Hi-Tops": "Cream Hi-Tops",
    "Purple Hi-Horses": "Purple Hi-Horses",
    "Hunter Hi-Tops": "Hunter Hi-Tops",
    "Red Hi-Tops": "Red Hi-Tops",
    "Gold Hi-Horses": "Gold Hi-Horses",
    "Shark Moccasins": "Shark Moccasins",
    Mawcasins: "Mawcasins",
    "Chocolate Dakroniks": "Chocolate Dakroniks",
    "Mint Dakroniks": "Mint Dakroniks",
    "Black Dakroniks": "Black Dakroniks",
    "Piranha Moccasins": "Piranha Moccasins",
    "White Norimaki 750s": "White Norimaki 750s",
    "Black Norimaki 750s": "Black Norimaki 750s",
    "Sunset Orca Hi-Tops": "Sunset Orca Hi-Tops",
    "Red & Black Squidkid IV": "Red & Black Squidkid IV",
    "Blue & Black Squidkid IV": "Blue & Black Squidkid IV",
    "Gray Sea-Slug Hi-Tops": "Gray Sea-Slug Hi-Tops",
    "Orca Hi-Tops": "Orca Hi-Tops",
    "Milky Enperrials": "Milky Enperrials",
    "Navy Enperrials": "Navy Enperrials",
    "Amber Sea Slug Hi-Tops": "Amber Sea Slug Hi-Tops",
    "Yellow Iromaki 750s": "Yellow Iromaki 750s",
    "Red & White Squidkid V": "Red & White Squidkid V",
    "Honey & Orange Squidkid V": "Honey & Orange Squidkid V",
    "Sun & Shade Squidkid IV": "Sun & Shade Squidkid IV",
    "Orca Woven Hi-Tops": "Orca Woven Hi-Tops",
    "Green Iromaki 750s": "Green Iromaki 750s",
    "Purple Iromaki 750s": "Purple Iromaki 750s",
    "Red Iromaki 750s": "Red Iromaki 750s",
    "Blue Iromaki 750s": "Blue Iromaki 750s",
    "Orange Iromaki 750s": "Orange Iromaki 750s",
    "Red Power Stripes": "Red Power Stripes",
    "Blue Power Stripes": "Blue Power Stripes",
    "Toni Kensa Black Hi-Tops": "Toni Kensa Black Hi-Tops",
    "Sesame Salt 270s": "Sesame Salt 270s",
    "Black & Blue Squidkid V": "Black & Blue Squidkid V",
    "Orca Passion Hi-Tops": "Orca Passion Hi-Tops",
    "Truffle Canvas Hi-Tops": "Truffle Canvas Hi-Tops",
    "Online Squidkid V": "Online Squidkid V",
    "Pink Trainers": "Pink Trainers",
    "Orange Arrows": "Orange Arrows",
    "Neon Sea Slugs": "Neon Sea Slugs",
    "White Arrows": "White Arrows",
    "Cyan Trainers": "Cyan Trainers",
    "Blue Sea Slugs": "Blue Sea Slugs",
    "Red Sea Slugs": "Red Sea Slugs",
    "Purple Sea Slugs": "Purple Sea Slugs",
    "Crazy Arrows": "Crazy Arrows",
    "Black Trainers": "Black Trainers",
    "Violet Trainers": "Violet Trainers",
    "Canary Trainers": "Canary Trainers",
    "Yellow-Mesh Sneakers": "Yellow-Mesh Sneakers",
    "Arrow Pull-Ons": "Arrow Pull-Ons",
    "Red-Mesh Sneakers": "Red-Mesh Sneakers",
    "N-Pacer CaO": "N-Pacer CaO",
    "N-Pacer Ag": "N-Pacer Ag",
    "N-Pacer Au": "N-Pacer Au",
    "Sea Slug Volt 95s": "Sea Slug Volt 95s",
    "Athletic Arrows": "Athletic Arrows",
    "Blue Lo-Tops": "Blue Lo-Tops",
    "Banana Basics": "Banana Basics",
    "LE Lo-Tops": "LE Lo-Tops",
    "White Seahorses": "White Seahorses",
    "Orange Lo-Tops": "Orange Lo-Tops",
    "Black Seahorses": "Black Seahorses",
    "Clownfish Basics": "Clownfish Basics",
    "Yellow Seahorses": "Yellow Seahorses",
    "Strapping Whites": "Strapping Whites",
    "Strapping Reds": "Strapping Reds",
    "Soccer Shoes": "Soccer Shoes",
    "LE Soccer Shoes": "LE Soccer Shoes",
    "Sunny Climbing Shoes": "Sunny Climbing Shoes",
    "Birch Climbing Shoes": "Birch Climbing Shoes",
    "Green Laceups": "Green Laceups",
    "White Laceless Dakroniks": "White Laceless Dakroniks",
    "Blue Laceless Dakroniks": "Blue Laceless Dakroniks",
    "Suede Gray Lace-Ups": "Suede Gray Lace-Ups",
    "Suede Nation Lace-Ups": "Suede Nation Lace-Ups",
    "Suede Marine Lace-Ups": "Suede Marine Lace-Ups",
    "Toni Kensa Soccer Shoes": "Toni Kensa Soccer Shoes",
    "Blue Slip-Ons": "Blue Slip-Ons",
    "Red Slip-Ons": "Red Slip-Ons",
    "Squid-Stitch Slip-Ons": "Squid-Stitch Slip-Ons",
    "Polka-dot Slip-Ons": "Polka-dot Slip-Ons",
    "Trail Boots": "Trail Boots",
    "Custom Trail Boots": "Custom Trail Boots",
    "Pro Trail Boots": "Pro Trail Boots",
    Bloblobber: "Bloblobber",
    "Bloblobber Deco": "Bloblobber Deco",
    "Grizzco Slosher": "Grizzco Slosher",
    "Tri-Slosher": "Tri-Slosher",
    "Tri-Slosher Nouveau": "Tri-Slosher Nouveau",
    "Sloshing Machine": "Sloshing Machine",
    "Sloshing Machine Neo": "Sloshing Machine Neo",
    "Kensa Sloshing Machine": "Kensa Sloshing Machine",
    "Hero Slosher": "Hero Slosher",
    Slosher: "Slosher",
    "Slosher Deco": "Slosher Deco",
    "Soda Slosher": "Soda Slosher",
    "Hero Slosher Replica": "Hero Slosher Replica",
    Explosher: "Explosher",
    "Custom Explosher": "Custom Explosher",
    "Drop Roller": "Drop Roller",
    "Special Charge Up": "Special Charge Up",
    "Special Power Up": "Special Power Up",
    "Ballpoint Splatling": "Ballpoint Splatling",
    "Ballpoint Splatling Nouveau": "Ballpoint Splatling Nouveau",
    "Hydra Splatling": "Hydra Splatling",
    "Custom Hydra Splatling": "Custom Hydra Splatling",
    "Hero Splatling": "Hero Splatling",
    "Mini Splatling": "Mini Splatling",
    "Zink Mini Splatling": "Zink Mini Splatling",
    "Kensa Mini Splatling": "Kensa Mini Splatling",
    "Nautilus 47": "Nautilus 47",
    "Nautilus 79": "Nautilus 79",
    "Heavy Splatling": "Heavy Splatling",
    "Heavy Splatling Deco": "Heavy Splatling Deco",
    "Heavy Splatling Remix": "Heavy Splatling Remix",
    "Hero Splatling Replica": "Hero Splatling Replica",
    Sprinkler: "Sprinkler",
    "Ninja Squid": "Ninja Squid",
    "Swim Speed Up": "Swim Speed Up",
    "Opening Gambit": "Opening Gambit",
    "Ink Saver (Sub)": "Ink Saver (Sub)",
    "Ink Armor": "Ink Armor",
    "Booyah Bomb": "Booyah Bomb",
    "Bubble Blower": "Bubble Blower",
    "Stealth Jump": "Stealth Jump",
    Splashdown: "Splashdown",
    "Tenta Missiles": "Tenta Missiles",
    "Ultra Stamp": "Ultra Stamp",
    "Thermal Ink": "Thermal Ink",
    "Ink Mine": "Ink Mine",
    "Dualie Squelchers": "Dualie Squelchers",
    "Custom Dualie Squelchers": "Custom Dualie Squelchers",
    "Glooga Dualies": "Glooga Dualies",
    "Glooga Dualies Deco": "Glooga Dualies Deco",
    "Kensa Glooga Dualies": "Kensa Glooga Dualies",
    "Hero Dualies": "Hero Dualies",
    "Splat Dualies": "Splat Dualies",
    "Enperry Splat Dualies": "Enperry Splat Dualies",
    "Kensa Splat Dualies": "Kensa Splat Dualies",
    "Hero Dualie Replicas": "Hero Dualie Replicas",
    "Dapple Dualies": "Dapple Dualies",
    "Dapple Dualies Nouveau": "Dapple Dualies Nouveau",
    "Clear Dapple Dualies": "Clear Dapple Dualies",
    "Dark Tetra Dualies": "Dark Tetra Dualies",
    "Light Tetra Dualies": "Light Tetra Dualies",
    "Undercover Brella": "Undercover Brella",
    "Undercover Sorella Brella": "Undercover Sorella Brella",
    "Kensa Undercover Brella": "Kensa Undercover Brella",
    "Grizzco Brella": "Grizzco Brella",
    "Hero Brella": "Hero Brella",
    "Splat Brella": "Splat Brella",
    "Sorella Brella": "Sorella Brella",
    "Hero Brella Replica": "Hero Brella Replica",
    "Tenta Brella": "Tenta Brella",
    "Tenta Sorella Brella": "Tenta Sorella Brella",
    "Tenta Camo Brella": "Tenta Camo Brella",
    "Sting Ray": "Sting Ray",
    Handling: "Handling",
    "Turf War (Splatfest)": "Turf War (Splatfest)",
    "Turf War": "Turf War",
    "Turf\nWar": "Turf\nWar",
    "Splat Zones": "Splat Zones",
    "Splat\nZones": "Splat\nZones",
    "Clam Blitz": "Clam Blitz",
    "Clam\nBlitz": "Clam\nBlitz",
    "Tower Control": "Tower Control",
    "Tower\nControl": "Tower\nControl",
  },
  countries: {
    AF: "Afghanistan",
    AX: "\u00c5land Islands",
    AL: "Albania",
    DZ: "Algeria",
    AS: "American Samoa",
    AD: "Andorra",
    AO: "Angola",
    AI: "Anguilla",
    AQ: "Antarctica",
    AG: "Antigua & Barbuda",
    AR: "Argentina",
    AM: "Armenia",
    AW: "Aruba",
    AU: "Australia",
    AT: "Austria",
    AZ: "Azerbaijan",
    BS: "Bahamas",
    BH: "Bahrain",
    BD: "Bangladesh",
    BB: "Barbados",
    BY: "Belarus",
    BE: "Belgium",
    BZ: "Belize",
    BJ: "Benin",
    BM: "Bermuda",
    BT: "Bhutan",
    BO: "Bolivia",
    BA: "Bosnia & Herzegovina",
    BW: "Botswana",
    BV: "Bouvet Island",
    BR: "Brazil",
    IO: "British Indian Ocean Territory",
    VG: "British Virgin Islands",
    BN: "Brunei",
    BG: "Bulgaria",
    BF: "Burkina Faso",
    BI: "Burundi",
    KH: "Cambodia",
    CM: "Cameroon",
    CA: "Canada",
    CV: "Cape Verde",
    BQ: "Caribbean Netherlands",
    KY: "Cayman Islands",
    CF: "Central African Republic",
    TD: "Chad",
    CL: "Chile",
    CN: "China",
    CX: "Christmas Island",
    CC: "Cocos (Keeling) Islands",
    CO: "Colombia",
    KM: "Comoros",
    CG: "Congo - Brazzaville",
    CD: "Congo - Kinshasa",
    CK: "Cook Islands",
    CR: "Costa Rica",
    CI: "C\u00f4te d\u2019Ivoire",
    HR: "Croatia",
    CU: "Cuba",
    CW: "Cura\u00e7ao",
    CY: "Cyprus",
    CZ: "Czechia",
    DK: "Denmark",
    DJ: "Djibouti",
    DM: "Dominica",
    DO: "Dominican Republic",
    EC: "Ecuador",
    EG: "Egypt",
    SV: "El Salvador",
    GQ: "Equatorial Guinea",
    ER: "Eritrea",
    EE: "Estonia",
    SZ: "Eswatini",
    ET: "Ethiopia",
    FK: "Falkland Islands",
    FO: "Faroe Islands",
    FJ: "Fiji",
    FI: "Finland",
    FR: "France",
    GF: "French Guiana",
    PF: "French Polynesia",
    TF: "French Southern Territories",
    GA: "Gabon",
    GM: "Gambia",
    GE: "Georgia",
    DE: "Germany",
    GH: "Ghana",
    GI: "Gibraltar",
    GR: "Greece",
    GL: "Greenland",
    GD: "Grenada",
    GP: "Guadeloupe",
    GU: "Guam",
    GT: "Guatemala",
    GG: "Guernsey",
    GN: "Guinea",
    GW: "Guinea-Bissau",
    GY: "Guyana",
    HT: "Haiti",
    HM: "Heard & McDonald Islands",
    HN: "Honduras",
    HK: "Hong Kong SAR China",
    HU: "Hungary",
    IS: "Iceland",
    IN: "India",
    ID: "Indonesia",
    IR: "Iran",
    IQ: "Iraq",
    IE: "Ireland",
    IM: "Isle of Man",
    IL: "Israel",
    IT: "Italy",
    JM: "Jamaica",
    JP: "Japan",
    JE: "Jersey",
    JO: "Jordan",
    KZ: "Kazakhstan",
    KE: "Kenya",
    KI: "Kiribati",
    KW: "Kuwait",
    KG: "Kyrgyzstan",
    LA: "Laos",
    LV: "Latvia",
    LB: "Lebanon",
    LS: "Lesotho",
    LR: "Liberia",
    LY: "Libya",
    LI: "Liechtenstein",
    LT: "Lithuania",
    LU: "Luxembourg",
    MO: "Macao SAR China",
    MG: "Madagascar",
    MW: "Malawi",
    MY: "Malaysia",
    MV: "Maldives",
    ML: "Mali",
    MT: "Malta",
    MH: "Marshall Islands",
    MQ: "Martinique",
    MR: "Mauritania",
    MU: "Mauritius",
    YT: "Mayotte",
    MX: "Mexico",
    FM: "Micronesia",
    MD: "Moldova",
    MC: "Monaco",
    MN: "Mongolia",
    ME: "Montenegro",
    MS: "Montserrat",
    MA: "Morocco",
    MZ: "Mozambique",
    MM: "Myanmar (Burma)",
    NA: "Namibia",
    NR: "Nauru",
    NP: "Nepal",
    NL: "Netherlands",
    NC: "New Caledonia",
    NZ: "New Zealand",
    NI: "Nicaragua",
    NE: "Niger",
    NG: "Nigeria",
    NU: "Niue",
    NF: "Norfolk Island",
    KP: "North Korea",
    MK: "North Macedonia",
    MP: "Northern Mariana Islands",
    NO: "Norway",
    OM: "Oman",
    PK: "Pakistan",
    PW: "Palau",
    PS: "Palestinian Territories",
    PA: "Panama",
    PG: "Papua New Guinea",
    PY: "Paraguay",
    PE: "Peru",
    PH: "Philippines",
    PN: "Pitcairn Islands",
    PL: "Poland",
    PT: "Portugal",
    PR: "Puerto Rico",
    QA: "Qatar",
    RE: "R\u00e9union",
    RO: "Romania",
    RU: "Russia",
    RW: "Rwanda",
    WS: "Samoa",
    SM: "San Marino",
    ST: "S\u00e3o Tom\u00e9 & Pr\u00edncipe",
    SA: "Saudi Arabia",
    SN: "Senegal",
    RS: "Serbia",
    SC: "Seychelles",
    SL: "Sierra Leone",
    SG: "Singapore",
    SX: "Sint Maarten",
    SK: "Slovakia",
    SI: "Slovenia",
    SB: "Solomon Islands",
    SO: "Somalia",
    ZA: "South Africa",
    GS: "South Georgia & South Sandwich Islands",
    KR: "South Korea",
    SS: "South Sudan",
    ES: "Spain",
    LK: "Sri Lanka",
    BL: "St. Barth\u00e9lemy",
    SH: "St. Helena",
    KN: "St. Kitts & Nevis",
    LC: "St. Lucia",
    MF: "St. Martin",
    PM: "St. Pierre & Miquelon",
    VC: "St. Vincent & Grenadines",
    SD: "Sudan",
    SR: "Suriname",
    SJ: "Svalbard & Jan Mayen",
    SE: "Sweden",
    CH: "Switzerland",
    SY: "Syria",
    TW: "Taiwan",
    TJ: "Tajikistan",
    TZ: "Tanzania",
    TH: "Thailand",
    TL: "Timor-Leste",
    TG: "Togo",
    TK: "Tokelau",
    TO: "Tonga",
    TT: "Trinidad & Tobago",
    TN: "Tunisia",
    TR: "Turkey",
    TM: "Turkmenistan",
    TC: "Turks & Caicos Islands",
    TV: "Tuvalu",
    UM: "U.S. Outlying Islands",
    VI: "U.S. Virgin Islands",
    UG: "Uganda",
    UA: "Ukraine",
    AE: "United Arab Emirates",
    GB: "United Kingdom",
    US: "United States",
    UY: "Uruguay",
    UZ: "Uzbekistan",
    VU: "Vanuatu",
    VA: "Vatican City",
    VE: "Venezuela",
    VN: "Vietnam",
    WF: "Wallis & Futuna",
    EH: "Western Sahara",
    YE: "Yemen",
    ZM: "Zambia",
    ZW: "Zimbabwe",
  },
  navigation: {
    "Map Planner": "Map Planner",
    Calendar: "Calendar",
    Builds: "Builds",
    "Build Analyzer": "Build Analyzer",
    "User Search": "User Search",
    "Free Agents": "Free Agents",
    "Tournament Results": "Tournament Results",
    Tournaments: "Tournaments",
    "Draft Cup": "Draft Cup",
    "Top 500 Browser": "Top 500 Browser",
    "Top 500": "Top 500",
    "Top 500 Tier Lists": "Top 500 Tier Lists",
    Leaderboards: "Leaderboards",
    "X Rank Leaderboards": "X Rank Leaderboards",
    "Plus Server": "Plus Server",
    Profile: "Profile",
    "Log out": "Log out",
    "Log in via Discord": "Log in via Discord",
    "Choose language": "Choose language",
    "Choose theme": "Choose theme",
    Browser: "Browser",
    Trends: "Trends",
    Analyzer: "Analyzer",
    FAQ: "FAQ",
    "Voting history": "Voting history",
    "Suggested and vouched players": "Suggested and vouched players",
    "Next voting": "Next voting",
    Voting: "Voting",
    Gray: "Gray",
    Red: "Red",
    Orange: "Orange",
    Yellow: "Yellow",
    Green: "Green",
    Teal: "Teal",
    Blue: "Blue",
    Cyan: "Cyan",
    Purple: "Purple",
    Pink: "Pink",
    paginationNext: "Next",
    paginationPrevious: "Previous",
  },
  home: {
    "Competitive Splatoon Hub": "Competitive Splatoon Hub",
    "Play in competitive events this week":
      "Play in competitive events this week",
    "View more info": "View more info",
    "Featuring...": "Featuring...",
    xRankMonths:
      "{{xRankMonthCount}} months of <3><0>X Rank Top 500 data</0></3>",
    buildCount: "<0></0> <2><0>builds</0></2>",
    userCount: "<0></0> <2><0>users</0></2>",
    faCount: "<0></0> <2><0>free agents</0></2>",
    tournamentCount: "<0></0> <2><0>tournament results</0></2>",
    "As well as": "As well as",
    calendarExplanation: "<0><0>Calendar</0></0> to discover upcoming events",
    drawingToolExplanation:
      "<0><0>Map drawing tool</0></0> to easily share your plans",
    analyzerExplanation:
      "<0><0>Build analyzer</0></0> to find out exactly what your builds are doing",
  },
  plans: {
    tooNarrowAlert:
      "Unfortunately this tool isn't designed for narrow screens but you can still give it a go",
    Weapons: "Weapons",
    Tools: "Tools",
    "Pencil (P)": "Pencil (P)",
    "Line (L)": "Line (L)",
    "Rectangle (R)": "Rectangle (R)",
    "Circle (C)": "Circle (C)",
    "Select (S)": "Select (S)",
    "Delete selected": "Delete selected",
    Undo: "Undo",
    Redo: "Redo",
    "Add text": "Add text",
    "Clear drawings": "Clear drawings",
    "Download as .png": "Download as .png",
    "Download as .json": "Download as .json",
    "Load from .json": "Load from .json",
    splatZonesShort: "SZ",
    towerControlShort: "TC",
    rainMakerShort: "RM",
    clamBlitzShort: "CB",
    turfWarShort: "TW",
    "Show top-down view": "Show top-down view",
  },
  calendar: {
    "Competitive Calendar": "Competitive Calendar",
    "Filter tournaments": "Filter tournaments",
    weekNumber: "Week {{weekNumber}}",
    "This week": "This week",
    "Join Discord": "Join Discord",
    "Hide info": "Hide info",
    "Show info": "Show info",
    Edit: "Edit",
    footer:
      "All events listed in your local time: {{timeNow}}<2>If you want your event displayed here message Sendou#0043 on Discord</2>",
    plusVotingInfo:
      "<0>Plus Server voting</0> of the month starts and lasts for the weekend",
  },
  builds: {
    "Default to Ability Point view": "Default to Ability Point view",
    "Select a weapon to start viewing builds":
      "Select a weapon to start viewing builds",
    "Filter by ability": "Filter by ability",
    "Click an ability to filter by it": "Click an ability to filter by it",
    "Only showing builds featuring the following abilities":
      "Only showing builds featuring the following abilities",
    Shooters: "Shooters",
    Blasters: "Blasters",
    Rollers: "Rollers",
    Brushes: "Brushes",
    Chargers: "Chargers",
    Sloshers: "Sloshers",
    Splatlings: "Splatings",
    Dualies: "Dualies",
    Brellas: "Brellas",
    "Maker of the build has reached top 500 with this weapon":
      "Maker of the build has reached top 500 with this weapon",
    expandBuilds: "Show all {{otherBuildCount}} builds by {{username}}",
    "No more builds to show": "No more builds to show",
    "No builds found with the current filter":
      "No builds found with the current filter",
    "Return to the top": "Return to the top",
  },
  analyzer: {
    currentPatch: "Patch {{CURRENT_PATCH}}",
    apExplanation: "AP = Ability Point = Mains * 10 + Subs * 3",
    Compare: "Compare",
    "Stop comparing": "Stop comparing",
    Editing: "Editing",
    ldeFullEffectExplanation:
      "Enemy has reached the 30 point mark OR there is 30 seconds or less on the clock OR it is overtime",
    ldeInBetweenExplanation: "Enemy has reached the {{pointMark}} point mark",
    ldeNoEffectExplanation:
      "Enemy has not reached the 50 point mark or there is more than 30 seconds on the clock",
    abilityPointShort: "AP",
    "Main only abilities (click to select)":
      "Main only abilities (click to select)",
    "Stackable abilities": "Stackable abilities",
    "Show settings": "Show settings",
    "Hide settings": "Hide settings",
    "Hide stats at base value": "Hide stats at base value",
    "Progress bars show progress to max value":
      "Progress bars show progress to max value",
    "Start charts Y axis from zero": "Start charts Y axis from zero",
    "Full charges per ink tank": "Full charges per ink tank",
    "Shots per ink tank": "Shots per ink tank",
    "Shots per ink tank (autofire mode)": "Shots per ink tank (autofire mode)",
    "Fully charged shots per ink tank": "Fully charged shots per ink tank",
    "Tap shots per ink tank": "Tap shots per ink tank",
    "Swings per ink tank": "Swings per ink tank",
    "Ground swings per ink tank": "Ground swings per ink tank",
    "Jumping swings per ink tank": "Jumping swings per ink tank",
    "Dodge roll ink consumption": "Dodge roll ink consumption",
    "of ink tank": "of ink tank",
    "Brella shield launch ink consumption":
      "Brella shield launch ink consumption",
    "ink consumption": "ink consumption",
    "Ink tank recovery from empty to full (squid form)":
      "Ink tank recovery from empty to full (squid form)",
    frames: "frames",
    seconds: "seconds",
    "Run speed": "Run speed",
    "Run speed (firing)": "Run speed (firing)",
    "distance units / frame": "distance units / frame",
    "Swim speed": "Swim speed",
    "Points to special": "Points to special",
    speed: "speed",
    pointsShort: "p",
    "Special lost when killed": "Special lost when killed",
    "Special lost when killed mid-Splashdown":
      "Special lost when killed mid-Splashdown",
    "of the charge": "of the charge",
    duration: "duration",
    "Special Power Up also increases Inkjet's shots' painting and blast radius":
      "Special Power Up also increases Inkjet's shots' painting and blast radius",
    "reticle size": "reticle size",
    "ink coverage": "ink coverage",
    "180dmg hitbox size": "180dmg hitbox size",
    "70dmg hitbox size": "70dmg hitbox size",
    "55dmg hitbox can't be increased with Special Power Up so the total radius of the special doesn't change":
      "55dmg hitbox can't be increased with Special Power Up so the total radius of the special doesn't change",
    "activation time": "activation time",
    "Amount inked by Ink Storm is not increased only in how long distance the droplets are spread. Special Power Up also increases the distance you can throw the seed.":
      "Amount inked by Ink Storm is not increased only in how long distance the droplets are spread. Special Power Up also increases the distance you can throw the seed.",
    durability: "durability",
    "55dmg explosion hitbox size": "55dmg explosion hitbox size",
    "bubble size": "bubble size",
    "explosion hitbox": "explosion hitbox",
    "autocharge speed": "autocharge speed",
    time: "time",
    "Quick Respawn activates when enemy kills you twice without you getting a kill in between":
      "Quick Respawn activates when enemy kills you twice without you getting a kill in between",
    "(in the air)": "(in the air)",
    "(on the ground)": "(on the ground)",
    "range and velocity": "range and velocity",
    "full-power phase duration": "full-power phase duration",
    "mid-phase duration": "mid-phase duration",
    "tracking duration": "tracking duration",
    "tracking range": "tracking range",
    boost: "boost",
    "When jumping to Sub Power Up boosted beakons QSJ AP bonus is applied on top of any existing QSJ the jumper has. 57AP can't be exceeded. Value shown is the bonus if the user of Beakon has 0AP invested in QSJ.":
      "When jumping to Sub Power Up boosted beakons QSJ AP bonus is applied on top of any existing QSJ the jumper has. 57AP can't be exceeded. Value shown is the bonus if the user of Beakon has 0AP invested in QSJ.",
    "Frames before taking damage from enemy ink":
      "Frames before taking damage from enemy ink",
    "Ink Resistance Up also allows you to jump higher and strafe faster while shooting in enemy ink":
      "Ink Resistance Up also allows you to jump higher and strafe faster while shooting in enemy ink",
    "hp / frame": "hp / frame",
    hp: "hp",
    "Limit on the damage enemy ink can deal on you":
      "Limit on the damage enemy ink can deal on you",
    "Run speed in enemy ink": "Run speed in enemy ink",
    "Sub Weapon damage (indirect)": "Sub Weapon damage (indirect)",
    "Special Weapon damage (indirect)": "Special Weapon damage (indirect)",
    "Bomb Defense Up DX also lessens the damage of a direct bomb hit but it will never make a bomb not kill that would have dealt over 100dmg without any of the ability on":
      "Bomb Defense Up DX also lessens the damage of a direct bomb hit but it will never make a bomb not kill that would have dealt over 100dmg without any of the ability on",
    "Tenta Missiles, Inkjet, Splashdown, Baller, Bubble Blower, Booyah Bomb & Ultra Stamp generate damage lessened by Bomb Defense Up DX. OHKO's are unaffected":
      "Tenta Missiles, Inkjet, Splashdown, Baller, Bubble Blower, Booyah Bomb & Ultra Stamp generate damage lessened by Bomb Defense Up DX. OHKO's are unaffected",
    "Base tracking time (Point Sensor)": "Base tracking time (Point Sensor)",
    "Base tracking time (Ink Mine)": "Base tracking time (Ink Mine)",
    "bullet ink coverage": "bullet ink coverage",
    "damage per shot": "damage per shot",
    "bullet spread (not jumping)": "bullet spread (not jumping)",
    "bullet spread (in the air)": "bullet spread (in the air)",
    "range and bullet velocity": "range and bullet velocity",
    "70dmg hitbox portion of the total explosion hitbox":
      "70dmg hitbox portion of the total explosion hitbox",
    "bullet explosion hitbox size": "bullet explosion hitbox size",
    "bullet explosion paint": "bullet explosion paint",
    "movement speed holding trigger down":
      "movement speed holding trigger down",
    "ink trail width": "ink trail width",
    "fully charged shot range": "fully charged shot range",
    "damage per fully charged shot": "damage per fully charged shot",
    "Ink coverage bonus is only applied to the circle at the end of the shot":
      "Ink coverage bonus is only applied to the circle at the end of the shot",
    "Ink coverage bonus is only applied to the line before the impact":
      "Ink coverage bonus is only applied to the line before the impact",
    "damage per shot (fully charged)": "damage per shot (fully charged)",
    "shield recharge time": "shield recharge time",
    "shield durability": "shield durability",
    "full charge shooting duration": "full charge shooting duration",
    "Slosher has weird physics so we haven't fully deciphered this parameter.":
      "Slosher has weird physics so we haven't fully deciphered this parameter.",
    damage: "damage",
    pointShort: "p",
    "Damage taken in enemy ink": "Damage taken in enemy ink",
    Intensity: "Intensity",
  },
  users: {
    "Filter by username, Twitter name or Discord ID":
      "Filter by username, Twitter name or Discord ID",
    Stick: "Stick",
    Motion: "Motion",
    "X Rank Top 500": "X Rank Top 500",
    "Edit profile": "Edit profile",
    "Motion sensitivity entered without stick sensitivity":
      "Motion sensitivity entered without stick sensitivity",
    "Custom URL has to be over 2 characters long":
      "Custom URL has to be over 2 characters long",
    "Custom URL can be at most 32 characters long":
      "Custom URL can be at most 32 characters long",
    "Custom URL has to contain at least one letter":
      "Custom URL has to contain at least one letter",
    "Custom URL can only contain letters and numbers":
      "Custom URL can only contain letters and numbers",
    "Filter builds by title or weapon": "Filter builds by title or weapon",
    "Weapon pool's max size is 5": "Weapon pool's max size is 5",
    "Bio's max length is 10000": "Bio's max length is 10000",
    "Profile updated": "Profile updated",
    "An error occurred": "An error occurred",
    "Editing profile": "Editing profile",
    "Profile picture": "Profile picture",
    profilePicExplanation:
      "Your profile picture comes from your Discord profile. If you change your profile picture on Discord you need to log out and back in to get it updated on sendou.ink.",
    "Custom URL": "Custom URL",
    "Please note Custom URL can't be updated after you have set it.":
      "Please note Custom URL can't be updated after you have set it.",
    Country: "Country",
    "Stick sensitivity": "Stick sensitivity",
    "Motion sensitivity": "Motion sensitivity",
    "Weapon pool": "Weapon pool",
    Bio: "Bio",
    markdownPrompt: "Markdown is supported - ",
    Submit: "Submit",
    Cancel: "Cancel",
    Edit: "Edit",
    Preview: "Preview",
    "Add build": "Add build",
    tooManyBuilds:
      "You already have 100 builds. Please delete one before adding a new one",
    "New build created": "New build created",
    "Build updated": "Build updated",
    "Build deleted": "Build deleted",
    "Delete build": "Delete build",
    "Adding a new build": "Adding a new build",
    "Editing existing build": "Editing existing build",
    Weapon: "Weapon",
    Headgear: "Headgear",
    Clothing: "Clothing",
    Shoes: "Shoes",
    Title: "Title",
    Description: "Description",
    "Best placement": "Best placement",
    "Highest power": "Highest power",
    "Number of placements": "Number of placements",
    "Best placement / power": "Best placement / power",
    noPlacementsPromptNew:
      "If you have reached Top 500 in a <1>finished</1> X Rank season you can have it displayed here! Simply contact Sendou#0043 on Discord with your in-game nick. Once set up new results are added automatically and no further action is needed.",
  },
  freeagents: {
    loginPrompt: "Log in to make your own free agent post and start matching!",
    pleaseWaitPrompt:
      "You need to wait a week after deleting your old free agent post before making a new one",
    "Hide filters": "Hide filters",
    "Show filters": "Show filters",
    Playstyle: "Playstyle",
    Region: "Region",
    Any: "Any",
    "Frontline/Slayer": "Frontline/Slayer",
    "Midline/Support": "Midline/Support",
    "Backline/Anchor": "Backline/Anchor",
    Europe: "Europe",
    "The Americas": "The Americas",
    Oceania: "Oceania",
    Other: "Other",
    Weapon: "Weapon",
    "Edit free agent post": "Edit free agent post",
    "New free agent post": "New free agent post",
    MATCHES: "MATCHES",
    youHaveAMatch:
      "You have a match with <1>{{matchFullName}}</1>! Contact them to see if you can get a team going",
    getLiking: "This match is revealed when you like them back!",
    getLiking_plural: "These matches are revealed when you like them back!",
    "No free agents found with the current filter":
      "No free agents found with the current filter",
    "No more free agents to show": "No more free agents to show",
    "Return to the top": "Return to the top",
    "Can VC": "Can VC",
    "Can VC usually": "Can VC usually",
    "Can VC sometimes": "Can VC sometimes",
    "Can't VC": "Can't VC",
    "Show more information": "Show more information",
    Activity: "Activity",
    "Looking for": "Looking for",
    "Past experience": "Past experience",
    Description: "Description",
    "Free agent post added": "Free agent post added",
    "Free agent post edited": "Free agent post edited",
    "Free agent post deleted": "Free agent post deleted",
    "Adding a new free agent post": "Adding a new free agent post",
    "Editing a free agent post": "Editing a free agent post",
    "Delete free agent post": "Delete free agent post",
    deleteNotif:
      "Note that if you decide to delete your post you need to wait a week before posting a new one.",
    "Confirm deletion": "Confirm deletion",
    theyAreSynced:
      "Profile picture, Discord name, Twitter user, weapon pool and Top 500 history are automatically synced up with your profile. Also please note that the post automatically sent to Discord can't be edited afterwards so you want to set these before making a post.",
    Playstyles: "Playstyles",
    "Required field": "Required field",
    "Value too long": "Value too long",
    "Free agent has reached Top 500 in X Rank":
      "Free agent has reached Top 500 in X Rank",
    "Can you voice chat?": "Can you voice chat?",
    Yes: "Yes",
    Usually: "Usually",
    Sometimes: "Sometimes",
    No: "No",
    "Past competitive experience": "Past competitive experience",
    "What is your activity like on a typical week?":
      "What is your activity like on a typical week?",
    "What are you looking from a team?": "What are you looking from a team?",
    "Free word": "Free word",
  },
  tournaments: {
    Tournament: "Tournament",
    Team: "Team",
    Player: "Player",
    Comp: "Comp",
    "Map & mode": "Map & mode",
    Region: "Region",
    All: "All",
    Western: "Western",
    Japanese: "Japanese",
    Apply: "Apply",
    "Clear filters": "Clear filters",
    "All tournaments": "All tournaments",
    "Popular weapons": "Popular weapons",
    VICTORY: "VICTORY",
    DEFEAT: "DEFEAT",
  },
  draft: {
    draftExplanation:
      "Draft Cup is a tournament series open for +1 and +2 members. On this page you can browse the leaderboards and detailed match reports.",
    "View matches": "View matches",
    Bracket: "Bracket",
    "Back to Draft Cup home": "Back to Draft Cup home",
    Expand: "Expand",
    paintShort: "p",
  },
  xsearch: {
    Name: "Name",
    Month: "Month",
    Year: "Year",
    Mode: "Mode",
    "All modes": "All modes",
    idViewed: "Viewing placements by player with the id {{idViewed}}",
    "X Power": "X Power",
    Placement: "Placement",
    ID: "ID",
  },
  xtrends: {
    trendsExplanation:
      "Here you can find X Rank Top 500 usage tier lists. For example for a weapon to be in the X tier it needs at least 30 placements in that mode that month.",
  },
  xleaderboards: {
    PEAK_XP: "X Power (all weapons)",
    UNIQUE_WEAPONS_COUNT: "Top 500 placements with different weapons",
    FOUR_MODE_PEAK_AVERAGE: "4 mode peak X Power average",
    PLACEMENTS_COUNT: "Top 500 placements",
    Score: "Score",
  },
  footer: {
    About: "About",
    "External links": "External links",
    Feedback: "Help/Feedback",
    feedbackText:
      "Noticed a bug? Something could be done better? Thought of a new cool feature you'd like to see on the site? Need help using the site? You can either:",
    "Thanks to": "Thanks to",
    createIssue: "Create an issue on <2>GitHub</2>",
    postOnDiscord:
      "Post on the #helpdesk or #feedback channel of our <2>Discord</2>",
    dmMe: "DM me on <2>Twitter</2> or Discord (Sendou#0043)",
    "provided the Top 500 X Rank data": "provided the Top 500 X Rank data",
    "provided background pictures for the map planner":
      "provided background pictures for the map planner",
    "provided the data for tournament browser":
      "provided the data for tournament browser",
    "gave plenty of useful feedback": "gave plenty of useful feedback",
    "art for the site like the inkling on the front page as well as footer pictures":
      "art for the site like the inkling on the front page as well as footer pictures",
    translation: "translation",
    Links: "Links",
    Guides: "Guides",
    Discord: "Discord",
    Misc: "Misc",
    englishOnly:
      "This content is currently available in English only. We will look into adding resources in other languages too.",
  },
} as const;

const t = (key: string) => {
  const [category, line] = key.split(";");

  // @ts-ignore
  return translations[category][line];
};

export const useTranslation = () => ({ t });
