/**
 * GENERATED by scripts/scanner/build-localized-entries.ts from the splat3 repo's
 * language dumps — do not edit by hand; regenerate when the game adds
 * content. Per-language kill-feed row templates: the "Splatted <name>!" row
 * wraps the splatted player's name in language-specific text on either side
 * (spaces kept as rendered; either side may be empty).
 */

export interface KillMessageTemplate {
	/** languages sharing this exact template */
	langs: readonly string[];
	/** constant text before the name (may end with a space, or be empty) */
	pre: string;
	/** constant text after the name (may start with a space, or be empty) */
	post: string;
}

export const KILL_MESSAGE_TEMPLATES: readonly KillMessageTemplate[] = [
	{
		langs: ["CNzh"],
		pre: "击倒了",
		post: "！",
	},
	{
		langs: ["EUde"],
		pre: "",
		post: " erledigt!",
	},
	{
		langs: ["EUen", "USen"],
		pre: "Splatted ",
		post: "!",
	},
	{
		langs: ["EUes"],
		pre: "¡Has eliminado a ",
		post: "!",
	},
	{
		langs: ["EUfr"],
		pre: "Tu as liquidé ",
		post: " !",
	},
	{
		langs: ["EUit"],
		pre: "Hai splattato ",
		post: "!",
	},
	{
		langs: ["EUnl"],
		pre: "",
		post: " uitgeschakeld!",
	},
	{
		langs: ["EUru"],
		pre: "Плюхнут игрок ",
		post: "!",
	},
	{
		langs: ["JPja"],
		pre: "",
		post: " をたおした！",
	},
	{
		langs: ["KRko"],
		pre: "",
		post: " 쓰러뜨렸다!",
	},
	{
		langs: ["TWzh"],
		pre: "將",
		post: "擊倒了！",
	},
	{
		langs: ["USes"],
		pre: "¡Reventaste a ",
		post: "!",
	},
	{
		langs: ["USfr"],
		pre: "Éclaboussé ",
		post: "!",
	},
];
