export { modes, modesShort } from "./modes";
export {
	weaponCategories,
	mainWeaponIds,
	weaponIdToAltId,
	weaponIdIsNotAlt,
	subWeaponIds,
	specialWeaponIds,
	exampleMainWeaponIdWithSpecialWeaponId,
	nonBombSubWeaponIds,
	nonDamagingSpecialWeaponIds,
	SPLAT_BOMB_ID,
	SUCTION_BOMB_ID,
	BURST_BOMB_ID,
	SPRINKLER_ID,
	SPLASH_WALL_ID,
	FIZZY_BOMB_ID,
	CURLING_BOMB_ID,
	AUTO_BOMB_ID,
	SQUID_BEAKON_ID,
	POINT_SENSOR_ID,
	INK_MINE_ID,
	TOXIC_MIST_ID,
	ANGLE_SHOOTER_ID,
	TORPEDO_ID,
	TRIZOOKA_ID,
	BIG_BUBBLER_ID,
	ZIPCASTER_ID,
	TENTA_MISSILES_ID,
	INK_STORM_ID,
	BOOYAH_BOMB_ID,
	WAVE_BREAKER_ID,
	INK_VAC_ID,
	KILLER_WAIL_ID,
	INKJET_ID,
	ULTRA_STAMP_ID,
	CRAB_TANK_ID,
	REEF_SLIDER_ID,
	TRIPLE_INKSTRIKE_ID,
	TACTICOOLER_ID,
} from "./weapon-ids";
export { headGearIds, clothesGearIds, shoesGearIds } from "./gear-ids";
export { abilitiesShort, abilities } from "./abilities";
export type {
	Ability,
	AbilityType,
	AbilityWithUnknown,
	ModeShort,
	ModeWithStage,
	StageId,
	BuildAbilitiesTuple,
	BuildAbilitiesTupleWithUnknown,
	MainWeaponId,
	SubWeaponId,
	SpecialWeaponId,
	RankedModeShort,
} from "./types";
export { isAbility } from "./utils";
export { stageIds } from "./stage-ids";
