export const countries = [
  { code: "af", name: "Afghanistan" },
  { code: "ax", name: "Åland Islands" },
  { code: "al", name: "Albania" },
  { code: "dz", name: "Algeria" },
  { code: "as", name: "American Samoa" },
  { code: "ad", name: "Andorra" },
  { code: "ao", name: "Angola" },
  { code: "ai", name: "Anguilla" },
  { code: "ag", name: "Antigua and Barbuda" },
  { code: "ar", name: "Argentina" },
  { code: "am", name: "Armenia" },
  { code: "aw", name: "Aruba" },
  { code: "au", name: "Australia" },
  { code: "at", name: "Austria" },
  { code: "az", name: "Azerbaijan" },
  { code: "bs", name: "Bahamas" },
  { code: "bh", name: "Bahrain" },
  { code: "bd", name: "Bangladesh" },
  { code: "bb", name: "Barbados" },
  { code: "by", name: "Belarus" },
  { code: "be", name: "Belgium" },
  { code: "bz", name: "Belize" },
  { code: "bj", name: "Benin" },
  { code: "bm", name: "Bermuda" },
  { code: "bt", name: "Bhutan" },
  { code: "bo", name: "Bolivia, Plurinational State of" },
  { code: "ba", name: "Bosnia and Herzegovina" },
  { code: "bw", name: "Botswana" },
  { code: "bv", name: "Bouvet Island" },
  { code: "br", name: "Brazil" },
  { code: "io", name: "BritishIndian Ocean Territory" },
  { code: "bn", name: "Brunei Darussalam" },
  { code: "bg", name: "Bulgaria" },
  { code: "bf", name: "Burkina Faso" },
  { code: "bi", name: "Burundi" },
  { code: "kh", name: "Cambodia" },
  { code: "cm", name: "Cameroon" },
  { code: "ca", name: "Canada" },
  { code: "cv", name: "Cape Verde" },
  { code: "ky", name: "Cayman Islands" },
  { code: "cf", name: "Central African Republic" },
  { code: "td", name: "Chad" },
  { code: "cl", name: "Chile" },
  { code: "cn", name: "China" },
  { code: "cx", name: "Christmas Island" },
  { code: "cc", name: "Cocos (Keeling) Islands" },
  { code: "co", name: "Colombia" },
  { code: "km", name: "Comoros" },
  { code: "cg", name: "Congo" },
  { code: "cd", name: "Congo, the Democratic Republic of the" },
  { code: "ck", name: "Cook Islands" },
  { code: "cr", name: "Costa Rica" },
  { code: "ci", name: "Côte d'Ivoire" },
  { code: "hr", name: "Croatia" },
  { code: "cu", name: "Cuba" },
  { code: "cy", name: "Cyprus" },
  { code: "cz", name: "Czech Republic" },
  { code: "dk", name: "Denmark" },
  { code: "dj", name: "Djibouti" },
  { code: "dm", name: "Dominica" },
  { code: "do", name: "Dominican Republic" },
  { code: "ec", name: "Ecuador" },
  { code: "eg", name: "Egypt" },
  { code: "sv", name: "El Salvador" },
  { code: "gq", name: "Equatorial Guinea" },
  { code: "er", name: "Eritrea" },
  { code: "ee", name: "Estonia" },
  { code: "et", name: "Ethiopia" },
  { code: "fk", name: "Falkland Islands (Malvinas)" },
  { code: "fo", name: "FaroeIslands" },
  { code: "fj", name: "Fiji" },
  { code: "fi", name: "Finland" },
  { code: "fr", name: "France" },
  { code: "gf", name: "French Guiana" },
  { code: "pf", name: "French Polynesia" },
  { code: "tf", name: "French Southern Territories" },
  { code: "ga", name: "Gabon" },
  { code: "gm", name: "Gambia" },
  { code: "ge", name: "Georgia" },
  { code: "de", name: "Germany" },
  { code: "gh", name: "Ghana" },
  { code: "gi", name: "Gibraltar" },
  { code: "gr", name: "Greece" },
  { code: "gl", name: "Greenland" },
  { code: "gd", name: "Grenada" },
  { code: "gp", name: "Guadeloupe" },
  { code: "gu", name: "Guam" },
  { code: "gt", name: "Guatemala" },
  { code: "gn", name: "Guinea" },
  { code: "gw", name: "Guinea-Bissau" },
  { code: "gy", name: "Guyana" },
  { code: "ht", name: "Haiti" },
  { code: "hm", name: "Heard Island and McDonald Islands" },
  { code: "va", name: "Holy See (Vatican City State)" },
  { code: "hn", name: "Honduras" },
  { code: "hk", name: "Hong Kong" },
  { code: "hu", name: "Hungary" },
  { code: "is", name: "Iceland" },
  { code: "in", name: "India" },
  { code: "id", name: "Indonesia" },
  { code: "ir", name: "Iran, Islamic Republic of" },
  { code: "iq", name: "Iraq" },
  { code: "ie", name: "Ireland" },
  { code: "il", name: "Israel" },
  { code: "it", name: "Italy" },
  { code: "jm", name: "Jamaica" },
  { code: "jp", name: "Japan" },
  { code: "jo", name: "Jordan" },
  { code: "kz", name: "Kazakhstan" },
  { code: "ke", name: "Kenya" },
  { code: "ki", name: "Kiribati" },
  { code: "kp", name: "Korea, Democratic People'sRepublic of" },
  { code: "kr", name: "Korea, Republic of" },
  { code: "kw", name: "Kuwait" },
  { code: "kg", name: "Kyrgyzstan" },
  { code: "la", name: "Lao People's Democratic Republic" },
  { code: "lv", name: "Latvia" },
  { code: "lb", name: "Lebanon" },
  { code: "ls", name: "Lesotho" },
  { code: "lr", name: "Liberia" },
  { code: "ly", name: "Libya" },
  { code: "li", name: "Liechtenstein" },
  { code: "lt", name: "Lithuania" },
  { code: "lu", name: "Luxembourg" },
  { code: "mo", name: "Macao" },
  { code: "mk", name: "Macedonia, the Former Yugoslav Republic of" },
  { code: "mg", name: "Madagascar" },
  { code: "mw", name: "Malawi" },
  { code: "my", name: "Malaysia" },
  { code: "mv", name: "Maldives" },
  { code: "ml", name: "Mali" },
  { code: "mt", name: "Malta" },
  { code: "mh", name: "Marshall Islands" },
  { code: "mq", name: "Martinique" },
  { code: "mr", name: "Mauritania" },
  { code: "mu", name: "Mauritius" },
  { code: "yt", name: "Mayotte" },
  { code: "mx", name: "Mexico" },
  { code: "fm", name: "Micronesia, Federated States of" },
  { code: "md", name: "Moldova, Republic of" },
  { code: "mc", name: "Monaco" },
  { code: "mn", name: "Mongolia" },
  { code: "me", name: "Montenegro" },
  { code: "ms", name: "Montserrat" },
  { code: "ma", name: "Morocco" },
  { code: "mz", name: "Mozambique" },
  { code: "mm", name: "Myanmar" },
  { code: "na", name: "Namibia" },
  { code: "nr", name: "Nauru" },
  { code: "np", name: "Nepal" },
  { code: "nl", name: "Netherlands" },
  { code: "nc", name: "New Caledonia" },
  { code: "nz", name: "New Zealand" },
  { code: "ni", name: "Nicaragua" },
  { code: "ne", name: "Niger" },
  { code: "ng", name: "Nigeria" },
  { code: "nu", name: "Niue" },
  { code: "nf", name: "Norfolk Island" },
  { code: "mp", name: "Northern Mariana Islands" },
  { code: "no", name: "Norway" },
  { code: "om", name: "Oman" },
  { code: "pk", name: "Pakistan" },
  { code: "pw", name: "Palau" },
  { code: "ps", name: "Palestine, State of" },
  { code: "pa", name: "Panama" },
  { code: "pg", name: "Papua New Guinea" },
  { code: "py", name: "Paraguay" },
  { code: "pe", name: "Peru" },
  { code: "ph", name: "Philippines" },
  { code: "pn", name: "Pitcairn" },
  { code: "pl", name: "Poland" },
  { code: "pt", name: "Portugal" },
  { code: "pr", name: "Puerto Rico" },
  { code: "qa", name: "Qatar" },
  { code: "re", name: "Réunion" },
  { code: "ro", name: "Romania" },
  { code: "ru", name: "Russian Federation" },
  { code: "rw", name: "Rwanda" },
  { code: "sh", name: "Saint Helena, Ascension and Tristan da Cunha" },
  { code: "kn", name: "Saint Kitts and Nevis" },
  { code: "lc", name: "Saint Lucia" },
  { code: "pm", name: "Saint Pierre and Miquelon" },
  { code: "vc", name: "Saint Vincent and the Grenadines" },
  { code: "ws", name: "Samoa" },
  { code: "sm", name: "San Marino" },
  { code: "st", name: "Sao Tome and Principe" },
  { code: "sa", name: "Saudi Arabia" },
  { code: "sn", name: "Senegal" },
  { code: "rs", name: "Serbia" },
  { code: "sc", name: "Seychelles" },
  { code: "sl", name: "Sierra Leone" },
  { code: "sg", name: "Singapore" },
  { code: "sk", name: "Slovakia" },
  { code: "si", name: "Slovenia" },
  { code: "sb", name: "Solomon Islands" },
  { code: "so", name: "Somalia" },
  { code: "za", name: "South Africa" },
  { code: "gs", name: "South Georgia and the South Sandwich Islands" },
  { code: "es", name: "Spain" },
  { code: "lk", name: "Sri Lanka" },
  { code: "sd", name: "Sudan" },
  { code: "sr", name: "Suriname" },
  { code: "sj", name: "Svalbard and Jan Mayen" },
  { code: "sz", name: "Swaziland" },
  { code: "se", name: "Sweden" },
  { code: "ch", name: "Switzerland" },
  { code: "sy", name: "Syrian Arab Republic" },
  { code: "tw", name: "Taiwan, Province of China" },
  { code: "tj", name: "Tajikistan" },
  { code: "tz", name: "Tanzania, United Republic of" },
  { code: "th", name: "Thailand" },
  { code: "tl", name: "Timor-Leste" },
  { code: "tg", name: "Togo" },
  { code: "tk", name: "Tokelau" },
  { code: "to", name: "Tonga" },
  { code: "tt", name: "Trinidad and Tobago" },
  { code: "tn", name: "Tunisia" },
  { code: "tr", name: "Turkey" },
  { code: "tm", name: "Turkmenistan" },
  { code: "tc", name: "Turks and Caicos Islands" },
  { code: "tv", name: "Tuvalu" },
  { code: "ug", name: "Uganda" },
  { code: "ua", name: "Ukraine" },
  { code: "ae", name: "United Arab Emirates" },
  { code: "gb", name: "United Kingdom" },
  { code: "us", name: "United States" },
  { code: "um", name: "United States Minor Outlying Islands" },
  { code: "uy", name: "Uruguay" },
  { code: "uz", name: "Uzbekistan" },
  { code: "vu", name: "Vanuatu" },
  { code: "ve", name: "Venezuela, Bolivarian Republic of" },
  { code: "vn", name: "Viet Nam" },
  { code: "vg", name: "Virgin Islands, British" },
  { code: "vi", name: "Virgin Islands, U.S." },
  { code: "wf", name: "Wallis and Futuna" },
  { code: "eh", name: "Western Sahara" },
  { code: "ye", name: "Yemen" },
  { code: "zm", name: "Zambia" },
  { code: "zw", name: "Zimbabwe" },
]

export const continents = {
  af: "AS",
  ax: "EU",
  al: "EU",
  dz: "AF",
  as: "OC",
  ad: "EU",
  ao: "AF",
  ai: "NA",
  ag: "NA",
  ar: "SA",
  am: "AS",
  aw: "NA",
  au: "OC",
  at: "EU",
  az: "AS",
  bs: "NA",
  bh: "AS",
  bd: "AS",
  bb: "NA",
  by: "EU",
  be: "EU",
  bz: "NA",
  bj: "AF",
  bm: "NA",
  bt: "AS",
  bo: "SA",
  ba: "EU",
  bw: "AF",
  bv: "AN",
  br: "SA",
  io: "AS",
  bn: "AS",
  bg: "EU",
  bf: "AF",
  bi: "AF",
  kh: "AS",
  cm: "AF",
  ca: "NA",
  cv: "AF",
  ky: "NA",
  cf: "AF",
  td: "AF",
  cl: "SA",
  cn: "AS",
  cx: "AS",
  cc: "AS",
  co: "SA",
  km: "AF",
  cg: "AF",
  cd: "AF",
  ck: "OC",
  cr: "NA",
  ci: "AF",
  hr: "EU",
  cu: "NA",
  cy: "EU",
  cz: "EU",
  dk: "EU",
  dj: "AF",
  dm: "NA",
  do: "NA",
  ec: "SA",
  eg: "AF",
  sv: "NA",
  gq: "AF",
  er: "AF",
  ee: "EU",
  et: "AF",
  fk: "SA",
  fo: "EU",
  fj: "OC",
  fi: "EU",
  fr: "EU",
  gf: "SA",
  pf: "OC",
  tf: "AN",
  ga: "AF",
  gm: "AF",
  ge: "AS",
  de: "EU",
  gh: "AF",
  gi: "EU",
  gr: "EU",
  gl: "NA",
  gd: "NA",
  gp: "NA",
  gu: "OC",
  gt: "NA",
  gn: "AF",
  gw: "AF",
  gy: "SA",
  ht: "NA",
  hm: "AN",
  va: "EU",
  hn: "NA",
  hk: "AS",
  hu: "EU",
  is: "EU",
  in: "AS",
  id: "AS",
  ir: "AS",
  iq: "AS",
  ie: "EU",
  il: "AS",
  it: "EU",
  jm: "NA",
  jp: "AS",
  jo: "AS",
  kz: "AS",
  ke: "AF",
  ki: "OC",
  kp: "AS",
  kr: "AS",
  kw: "AS",
  kg: "AS",
  la: "AS",
  lv: "EU",
  lb: "AS",
  ls: "AF",
  lr: "AF",
  ly: "AF",
  li: "EU",
  lt: "EU",
  lu: "EU",
  mo: "AS",
  mk: "EU",
  mg: "AF",
  mw: "AF",
  my: "AS",
  mv: "AS",
  ml: "AF",
  mt: "EU",
  mh: "OC",
  mq: "NA",
  mr: "AF",
  mu: "AF",
  yt: "AF",
  mx: "NA",
  fm: "OC",
  md: "EU",
  mc: "EU",
  mn: "AS",
  me: "EU",
  ms: "NA",
  ma: "AF",
  mz: "AF",
  mm: "AS",
  na: "AF",
  nr: "OC",
  np: "AS",
  nl: "EU",
  nc: "OC",
  nz: "OC",
  ni: "NA",
  ne: "AF",
  ng: "AF",
  nu: "OC",
  nf: "OC",
  mp: "OC",
  no: "EU",
  om: "AS",
  pk: "AS",
  pw: "OC",
  ps: "AS",
  pa: "NA",
  pg: "OC",
  py: "SA",
  pe: "SA",
  ph: "AS",
  pn: "OC",
  pl: "EU",
  pt: "EU",
  pr: "NA",
  qa: "AS",
  re: "AF",
  ro: "EU",
  ru: "EU",
  rw: "AF",
  sh: "AF",
  kn: "NA",
  lc: "NA",
  pm: "NA",
  vc: "NA",
  ws: "OC",
  sm: "EU",
  st: "AF",
  sa: "AS",
  sn: "AF",
  rs: "EU",
  sc: "AF",
  sl: "AF",
  sg: "AS",
  sk: "EU",
  si: "EU",
  sb: "OC",
  so: "AF",
  za: "AF",
  gs: "AN",
  es: "EU",
  lk: "AS",
  sd: "AF",
  sr: "SA",
  sj: "EU",
  sz: "AF",
  se: "EU",
  ch: "EU",
  sy: "AS",
  tw: "AS",
  tj: "AS",
  tz: "AF",
  th: "AS",
  tl: "OC",
  tg: "AF",
  tk: "OC",
  to: "OC",
  tt: "NA",
  tn: "AF",
  tr: "AS",
  tm: "AS",
  tc: "NA",
  tv: "OC",
  ug: "AF",
  ua: "EU",
  ae: "AS",
  gb: "EU",
  us: "NA",
  um: "OC",
  uy: "SA",
  uz: "AS",
  vu: "OC",
  ve: "SA",
  vn: "AS",
  vg: "NA",
  vi: "NA",
  wf: "OC",
  eh: "AF",
  ye: "AS",
  zm: "AF",
  zw: "AF",
}

export const modes = [
  "",
  "Splat Zones",
  "Tower Control",
  "Rainmaker",
  "Clam Blitz",
]

export const months = [
  "",
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
]

export const weapons = [
  "Sploosh-o-matic",
  "Neo Sploosh-o-matic",
  "Sploosh-o-matic 7",
  "Splattershot Jr.",
  "Custom Splattershot Jr.",
  "Kensa Splattershot Jr.",
  "Splash-o-matic",
  "Neo Splash-o-matic",
  "Aerospray MG",
  "Aerospray RG",
  "Aerospray PG",
  "Splattershot",
  "Tentatek Splattershot",
  "Kensa Splattershot",
  ".52 Gal",
  ".52 Gal Deco",
  "Kensa .52 Gal",
  "N-ZAP '85",
  "N-ZAP '89",
  "N-ZAP '83",
  "Splattershot Pro",
  "Forge Splattershot Pro",
  "Kensa Splattershot Pro",
  ".96 Gal",
  ".96 Gal Deco",
  "Jet Squelcher",
  "Custom Jet Squelcher",
  "L-3 Nozzlenose",
  "L-3 Nozzlenose D",
  "Kensa L-3 Nozzlenose",
  "H-3 Nozzlenose",
  "H-3 Nozzlenose D",
  "Cherry H-3 Nozzlenose",
  "Squeezer",
  "Foil Squeezer",
  "Luna Blaster",
  "Luna Blaster Neo",
  "Kensa Luna Blaster",
  "Blaster",
  "Custom Blaster",
  "Range Blaster",
  "Custom Range Blaster",
  "Grim Range Blaster",
  "Rapid Blaster",
  "Rapid Blaster Deco",
  "Kensa Rapid Blaster",
  "Rapid Blaster Pro",
  "Rapid Blaster Pro Deco",
  "Clash Blaster",
  "Clash Blaster Neo",
  "Carbon Roller",
  "Carbon Roller Deco",
  "Splat Roller",
  "Krak-On Splat Roller",
  "Kensa Splat Roller",
  "Dynamo Roller",
  "Gold Dynamo Roller",
  "Kensa Dynamo Roller",
  "Flingza Roller",
  "Foil Flingza Roller",
  "Inkbrush",
  "Inkbrush Nouveau",
  "Permanent Inkbrush",
  "Octobrush",
  "Octobrush Nouveau",
  "Kensa Octobrush",
  "Classic Squiffer",
  "New Squiffer",
  "Fresh Squiffer",
  "Splat Charger",
  "Firefin Splat Charger",
  "Kensa Charger",
  "Splatterscope",
  "Firefin Splatterscope",
  "Kensa Splatterscope",
  "E-liter 4K",
  "Custom E-liter 4K",
  "E-liter 4K Scope",
  "Custom E-liter 4K Scope",
  "Bamboozler 14 Mk I",
  "Bamboozler 14 Mk II",
  "Bamboozler 14 Mk III",
  "Goo Tuber",
  "Custom Goo Tuber",
  "Slosher",
  "Slosher Deco",
  "Soda Slosher",
  "Tri-Slosher",
  "Tri-Slosher Nouveau",
  "Sloshing Machine",
  "Sloshing Machine Neo",
  "Kensa Sloshing Machine",
  "Bloblobber",
  "Bloblobber Deco",
  "Explosher",
  "Custom Explosher",
  "Mini Splatling",
  "Zink Mini Splatling",
  "Kensa Mini Splatling",
  "Heavy Splatling",
  "Heavy Splatling Deco",
  "Heavy Splatling Remix",
  "Hydra Splatling",
  "Custom Hydra Splatling",
  "Ballpoint Splatling",
  "Ballpoint Splatling Nouveau",
  "Nautilus 47",
  "Nautilus 79",
  "Dapple Dualies",
  "Dapple Dualies Nouveau",
  "Clear Dapple Dualies",
  "Splat Dualies",
  "Enperry Splat Dualies",
  "Kensa Splat Dualies",
  "Glooga Dualies",
  "Glooga Dualies Deco",
  "Kensa Glooga Dualies",
  "Dualie Squelchers",
  "Custom Dualie Squelchers",
  "Dark Tetra Dualies",
  "Light Tetra Dualies",
  "Splat Brella",
  "Sorella Brella",
  "Tenta Brella",
  "Tenta Sorella Brella",
  "Tenta Camo Brella",
  "Undercover Brella",
  "Undercover Sorella Brella",
  "Kensa Undercover Brella",
]

export const shooters = [
  "Sploosh-o-matic",
  "Neo Sploosh-o-matic",
  "Sploosh-o-matic 7",
  "Splattershot Jr.",
  "Custom Splattershot Jr.",
  "Kensa Splattershot Jr.",
  "Splash-o-matic",
  "Neo Splash-o-matic",
  "Aerospray MG",
  "Aerospray RG",
  "Aerospray PG",
  "Splattershot",
  "Tentatek Splattershot",
  "Kensa Splattershot",
  ".52 Gal",
  ".52 Gal Deco",
  "Kensa .52 Gal",
  "N-ZAP '85",
  "N-ZAP '89",
  "N-ZAP '83",
  "Splattershot Pro",
  "Forge Splattershot Pro",
  "Kensa Splattershot Pro",
  ".96 Gal",
  ".96 Gal Deco",
  "Jet Squelcher",
  "Custom Jet Squelcher",
]

export const semiauto = [
  "L-3 Nozzlenose",
  "L-3 Nozzlenose D",
  "Kensa L-3 Nozzlenose",
  "H-3 Nozzlenose",
  "H-3 Nozzlenose D",
  "Cherry H-3 Nozzlenose",
  "Squeezer",
  "Foil Squeezer",
]

export const blasters = [
  "Luna Blaster",
  "Luna Blaster Neo",
  "Kensa Luna Blaster",
  "Blaster",
  "Custom Blaster",
  "Range Blaster",
  "Custom Range Blaster",
  "Grim Range Blaster",
  "Rapid Blaster",
  "Rapid Blaster Deco",
  "Kensa Rapid Blaster",
  "Rapid Blaster Pro",
  "Rapid Blaster Pro Deco",
  "Clash Blaster",
  "Clash Blaster Neo",
]

export const rollers = [
  "Carbon Roller",
  "Carbon Roller Deco",
  "Splat Roller",
  "Krak-On Splat Roller",
  "Kensa Splat Roller",
  "Dynamo Roller",
  "Gold Dynamo Roller",
  "Kensa Dynamo Roller",
  "Flingza Roller",
  "Foil Flingza Roller",
]

export const brushes = [
  "Inkbrush",
  "Inkbrush Nouveau",
  "Permanent Inkbrush",
  "Octobrush",
  "Octobrush Nouveau",
  "Kensa Octobrush",
]

export const chargers = [
  "Classic Squiffer",
  "New Squiffer",
  "Fresh Squiffer",
  "Splat Charger",
  "Firefin Splat Charger",
  "Kensa Charger",
  "Splatterscope",
  "Firefin Splatterscope",
  "Kensa Splatterscope",
  "E-liter 4K",
  "Custom E-liter 4K",
  "E-liter 4K Scope",
  "Custom E-liter 4K Scope",
  "Bamboozler 14 Mk I",
  "Bamboozler 14 Mk II",
  "Bamboozler 14 Mk III",
  "Goo Tuber",
  "Custom Goo Tuber",
]

export const sloshers = [
  "Slosher",
  "Slosher Deco",
  "Soda Slosher",
  "Tri-Slosher",
  "Tri-Slosher Nouveau",
  "Sloshing Machine",
  "Sloshing Machine Neo",
  "Kensa Sloshing Machine",
  "Bloblobber",
  "Bloblobber Deco",
  "Explosher",
  "Custom Explosher",
]

export const splatlings = [
  "Mini Splatling",
  "Zink Mini Splatling",
  "Kensa Mini Splatling",
  "Heavy Splatling",
  "Heavy Splatling Deco",
  "Heavy Splatling Remix",
  "Hydra Splatling",
  "Custom Hydra Splatling",
  "Ballpoint Splatling",
  "Ballpoint Splatling Nouveau",
  "Nautilus 47",
  "Nautilus 79",
]

export const dualies = [
  "Dapple Dualies",
  "Dapple Dualies Nouveau",
  "Clear Dapple Dualies",
  "Splat Dualies",
  "Enperry Splat Dualies",
  "Kensa Splat Dualies",
  "Glooga Dualies",
  "Glooga Dualies Deco",
  "Kensa Glooga Dualies",
  "Dualie Squelchers",
  "Custom Dualie Squelchers",
  "Dark Tetra Dualies",
  "Light Tetra Dualies",
]

export const brellas = [
  "Splat Brella",
  "Sorella Brella",
  "Tenta Brella",
  "Tenta Sorella Brella",
  "Tenta Camo Brella",
  "Undercover Brella",
  "Undercover Sorella Brella",
  "Kensa Undercover Brella",
]

export const weaponsByCategory = {
  Shooters: shooters,
  "Semi-automatic Shooters": semiauto,
  Blasters: blasters,
  Rollers: rollers,
  Brushes: brushes,
  Chargers: chargers,
  Sloshers: sloshers,
  Splatlings: splatlings,
  Dualies: dualies,
  Brellas: brellas,
}

export const categoryKeys = [
  "Shooters",
  "Semi-automatic Shooters",
  "Blasters",
  "Rollers",
  "Brushes",
  "Chargers",
  "Sloshers",
  "Splatlings",
  "Dualies",
  "Brellas",
]

export const gearEnglish = [
  {
    brand: "amiibo",
    clothes: [
      "Enchanted Robe",
      "Fresh Fish Gloves",
      "Marinated Top",
      "Pearlescent Hoodie",
      "Power Armor",
      "Power Armor Mk I",
      "Samurai Jacket",
      "School Cardigan",
      "School Uniform",
      "Squinja Suit",
      "Steel Platemail",
    ],
    head: [
      "Enchanted Hat",
      "Fresh Fish Head",
      "Marinated Headphones",
      "Pearlescent Crown",
      "Power Mask",
      "Power Mask Mk I",
      "Samurai Helmet",
      "Squid Clip-Ons",
      "Squid Hairclip",
      "Squinja Mask",
      "Steel Helm",
    ],
    shoes: [
      "Enchanted Boots",
      "Fresh Fish Feet",
      "Fringed Loafers",
      "Marinated Slip-Ons",
      "Pearlescent Kicks",
      "Power Boots",
      "Power Boots Mk I",
      "Samurai Shoes",
      "School Shoes",
      "Squinja Boots",
      "Steel Greaves",
    ],
  },
  {
    brand: "Annaki",
    clothes: [
      "Annaki Blue Cuff",
      "Annaki Drive Tee ",
      "Annaki Evolution Tee",
      "Annaki Flannel Hoodie",
      "Annaki Polpo-Pic Tee",
      "Annaki Red Cuff",
      "Annaki Yellow Cuff",
      "Crimson Parashooter",
      "Hula Punk Shirt",
      "Prune Parashooter",
      "Red Hula Punk with Tie",
      "Rockin' Leather Jacket",
    ],
    head: ["Annaki Beret", "Annaki Beret & Glasses", "Annaki Mask"],
    shoes: ["Annaki Arachno Boots", "Annaki Habaneros", "Annaki Tigers"],
  },
  {
    brand: "Cuttlegear",
    clothes: [
      "Armor Jacket Replica",
      "Black Cuttlegear LS",
      "Fresh Octo Tee",
      "Hero Hoodie Replica",
      "Hero Jacket Replica",
      "Neo Octoling Armor",
      "Null Armor Replica",
      "Octarian Retro",
      "Octo Layered LS",
      "Octo Tee",
      "Old-Timey Clothes",
      "Red Cuttlegear LS",
      "Sennyu Suit",
    ],
    head: [
      "Armor Helmet Replica",
      "Conductor Cap",
      "Golden Toothpick",
      "Hero Headphones Replica",
      "Hero Headset Replica",
      "Null Visor Replica",
      "Octoling Shades",
      "Old-Timey Hat",
      "Studio Octophones",
    ],
    shoes: [
      "Armor Boot Replicas",
      "Hero Runner Replicas",
      "Hero Snowboots Replicas",
      "Neo Octoling Boots",
      "Null Boots Replica",
      "Old-Timey Shoes",
    ],
  },
  {
    brand: "Enperry",
    clothes: [
      "Black Velour Octoking Tee ",
      "Grape Hoodie",
      "Green Velour Octoking Tee",
      "King Jersey",
      "Milky Eminence Jacket",
      "N-Pacer Sweat",
      "Navy Eminence Jacket",
      "Navy King Tank",
      "Octoking HK Jersey",
      "Slash King Tank",
      "White King Tank",
    ],
    head: [
      "Eminence Cuff",
      "King Facemask",
      "King Flip Mesh",
      "Octoking Facemask",
    ],
    shoes: [
      "Black & Blue Squidkid V",
      "Blue & Black Squidkid IV",
      "Honey & Orange Squidkid V",
      "Milky Enperrials",
      "N-Pacer Ag",
      "N-Pacer Au",
      "N-Pacer CaO",
      "Navy Enperrials",
      "Online Squidkid V",
      "Pearlescent Squidkid IV",
      "Red & Black Squidkid IV",
      "Red & White Squidkid V",
      "Rina Squidkid IV",
      "Sun & Shade Squidkid IV",
    ],
  },
  {
    brand: "Firefin",
    clothes: [
      "Baseball Jersey",
      "Black 8-Bit FishFry",
      "Blue 16-Bit FishFry",
      "Camo Zip Hoodie",
      "Carnivore Tee",
      "Dark Urban Vest",
      "Firefin Navy Sweat",
      "Fugu Tee",
      "Gray 8-Bit FishFry",
      "Green Zip Hoodie",
      "Herbivore Tee",
      "Khaki 16-Bit FishFry",
      "White 8-Bit FishFry",
      "Yellow Urban Vest",
      "ω-3 Tee",
    ],
    head: [
      "Black FishFry Bandana",
      "Blowfish Bell Hat",
      "Blowfish Newsie",
      "Camo Mesh",
      "Firefin Facemask",
      "FishFry Biscuit Bandana",
      "FishFry Visor",
      "Fugu Bell Hat",
      "Jet Cap",
      "Jungle Hat",
      "Knitted Hat",
      "Octoglasses",
    ],
    shoes: ["Red FishFry Sandals", "Yellow FishFry Sandals"],
  },
  {
    brand: "Forge",
    clothes: [
      "Aloha Shirt",
      "Blue Sailor Suit",
      "Brown FA-11 Bomber",
      "Custom Painted F-3 ",
      "FA-01 Jacket",
      "FA-01 Reversed",
      "Forge Inkling Parka",
      "Forge Octarian Jacket",
      "Gray FA-11 Bomber",
      "Green Tee",
      "Moist Ghillie Suit",
      "White Leather F-3",
      "White Sailor Suit",
    ],
    head: [
      "Deca Tackle Visor Helmet",
      "Designer Headphones",
      "Digi-Camo Forge Mask",
      "Forge Mask",
      "Gas Mask",
      "Hockey Helmet",
      "Moist Ghillie Helmet",
      "Motocross Nose Guard",
      "Noise Cancelers",
      "Octo Tackle Helmet Deco",
      "Paintball Mask",
      "Pilot Goggles",
      "Safari Hat",
      "Sennyu Goggles",
      "Sennyu Headphones",
      "Skull Bandana",
      "Snorkel Mask",
      "Special Forces Beret",
      "Splash Goggles",
      "Squidfin Hook Cans",
      "Squidlife Headphones",
      "Stealth Goggles",
      "Studio Headphones",
      "Treasure Hunter",
    ],
    shoes: ["Moist Ghillie Boots"],
  },
  {
    brand: "Grizzco",
    clothes: [
      "Anchor Life Vest",
      "Crustwear XXL",
      "Dev Uniform",
      "Garden Gear",
      "Juice Parka",
      "North-Country Parka",
      "Octoleet Armor",
      "Office Attire",
      "Online Jersey",
      "Record Shop Look EP",
      "Squiddor Polo",
      "SRL Coat",
    ],
    head: [
      "Beekeeper Hat",
      "Cap of Legend",
      "Dust Blocker 2000",
      "Headlamp Helmet",
      "Oceanic Hard Hat",
      "Octoleet Goggles",
      "Sailor Cap",
      "Welding Mask",
      "Worker's Cap",
      "Worker's Head Towel",
    ],
    shoes: [
      "Angry Rain Boots",
      "Flipper Floppers",
      "Friendship Bracelet",
      "Non-slip Senseis",
      "Octoleet Boots",
      "Wooden Sandals",
    ],
  },
  {
    brand: "Inkline",
    clothes: [
      "Berry Ski Jacket",
      "Blue Peaks Tee",
      "Chili-Pepper Ski Jacket",
      "Chilly Mountain Coat",
      "Eggplant Mountain Coat",
      "Fishing Vest",
      "Forest Vest",
      "Green Striped LS",
      "Ivory Peaks Tee",
      "Matcha Down Jacket",
      "Mountain Vest",
      "Olive Ski Jacket",
      "Striped Peaks LS",
    ],
    head: [
      "Bamboo Hat",
      "Camping Hat",
      "Lightweight Cap",
      "Mountie Hat",
      "Seashell Bamboo Hat",
      "Short Beanie",
      "Tulip Parasol",
      "Yamagiri Beanie",
    ],
    shoes: [
      "Acerola Rain Boots",
      "Birch Climbing Shoes",
      "Bubble Rain Boots",
      "Custom Trail Boots",
      "Green Rain Boots",
      "Luminous Delta Straps",
      "Musselforge Flip-Flops",
      "Neon Delta Straps",
      "Pro Trail Boots",
      "Snow Delta Straps",
      "Sunny Climbing Shoes",
      "Trail Boots",
    ],
  },
  {
    brand: "Krak-On",
    clothes: [
      "Chili Octo Aloha",
      "Krak-On 528",
      "Missus Shrug Tee",
      "Mister Shrug Tee",
      "Octobowler Shirt",
      "Rainy-Day Tee",
      "Rodeo Shirt",
      "Squid-Pattern Waistcoat",
      "Squidstar Waistcoat",
      "Sunny-Day Tee",
    ],
    head: [
      "Full Moon Glasses",
      "Hickory Work Cap",
      "Long-Billed Cap",
      "Paisley Bandana",
      "Two-Stripe Mesh",
      "Woolly Urchins Classic",
    ],
    shoes: [
      "Banana Basics",
      "Blue Slip-Ons",
      "Blueberry Casuals",
      "Choco Clogs",
      "Clownfish Basics",
      "Cream Basics",
      "Cream Hi-Tops",
      "Hunter Hi-Tops",
      "Midnight Slip-Ons",
      "Oyster Clogs",
      "Plum Casuals",
      "Polka-dot Slip-Ons",
      "Red Hi-Tops",
      "Red Slip-Ons",
      "Squid-Stitch Slip-Ons",
      "Truffle Canvas Hi-Tops",
    ],
  },
  {
    brand: "Rockenberg",
    clothes: [
      "Black Baseball LS",
      "Black Inky Rider",
      "Black Urchin Rock Tee",
      "Chirpy Chips Band Tee",
      "Hightide Era Band Tee",
      "Lumberjack Shirt",
      "Rockenberg Black",
      "Rockenberg White",
      "Round-Collar Shirt",
      "Squid Squad Band Tee",
      "Vintage Check Shirt",
      "Wet Floor Band Tee",
      "White Baseball LS",
      "White Inky Rider",
      "White Urchin Rock Tee",
    ],
    head: ["18K Aviators", "SV925 Circle Shades"],
    shoes: [
      "Blue Moto Boots",
      "Cherry Kicks",
      "Deepsea Leather Boots",
      "Gray Yellow-Soled Wingtips",
      "Inky Kid Clams",
      "Kid Clams",
      "Moto Boots",
      "Navy Red-Soled Wingtips",
      "New-Leaf Leather Boots",
      "Pearl Punk Crowns",
      "Punk Blacks",
      "Punk Cherries",
      "Punk Whites",
      "Punk Yellows",
      "Red Work Boots",
      "Roasted Brogues",
      "Sennyu Inksoles",
      "Smoky Wingtips",
      "Squink Wingtips",
      "Tan Work Boots",
      "Turquoise Kicks",
      "White Kicks",
    ],
  },
  {
    brand: "Skalop",
    clothes: [
      "Black Hoodie",
      "Dots-On-Dots Shirt",
      "Firewave Tee",
      "Grape Tee",
      "Gray Hoodie",
      "Hothouse Hoodie",
      "Icewave Tee",
      "Mint Tee",
      "Pearl Tee",
      "Reggae Tee",
      "Squid-Stitch Tee",
    ],
    head: [
      "Bike Helmet",
      "Classic Straw Boater",
      "Do-Rag, Cap, & Glasses",
      "Hothouse Hat",
      "Jellyvader Cap",
      "Patched Hat",
      "Skate Helmet",
      "Sneaky Beanie",
      "Sporty Bobble Hat",
      "Squid Nordic",
      "Squid-Stitch Cap",
      "Squidvader Cap",
      "Straw Boater",
      "Streetstyle Cap",
      "Urchins Cap",
      "Visor Skate Helmet",
    ],
    shoes: [],
  },
  {
    brand: "Splash Mob",
    clothes: [
      "Baby-Jelly Shirt",
      "Baby-Jelly Shirt & Tie",
      "Gray College Sweat",
      "Green Cardigan",
      "Lime Easy-Stripe Shirt",
      "Linen Shirt",
      "Navy College Sweat",
      "Navy Striped LS",
      "Orange Cardigan",
      "Pink Easy-Stripe Shirt",
      "Pink Hoodie",
      "Pirate-Stripe Tee",
      "Sage Polo",
      "Sailor-Stripe Tee",
      "Shirt & Tie",
      "Shirt with Blue Hoodie",
      "Shrimp-Pink Polo",
      "Striped Shirt",
      "Varsity Baseball LS",
      "Whale-Knit Sweater",
      "White Shirt",
      "White Striped LS",
    ],
    head: [
      "Bobble Hat",
      "Half-Rim Glasses",
      "House-Tag Denim Cap",
      "Pilot Hat",
      "Retro Specs",
      "Sennyu Bon Bon Beanie",
      "Sennyu Specs",
      "Striped Beanie",
    ],
    shoes: [
      "Green Laceups",
      "Hunting Boots",
      "Mawcasins",
      "Piranha Moccasins",
      "Shark Moccasins",
      "Strapping Reds",
      "Strapping Whites",
      "Tea-Green Hunting Boots",
    ],
  },
  {
    brand: "SquidForce",
    clothes: [
      "Anchor Sweat",
      "Basic Tee",
      "Black Anchor Tee",
      "Black Layered LS",
      "Black Tee",
      "Black V-Neck Tee",
      "Camo Layered LS",
      "Friend Tee",
      "Green V-Neck Limited Tee",
      "Layered Anchor LS",
      "League Tee",
      "Mecha Body - AKM",
      "Octo Support Hoodie",
      "Red V-Neck Limited Tee",
      "Retro Sweat",
      "Splatfest Tee",
      "Squid Yellow Layered LS",
      "Squidmark LS",
      "Squidmark Sweat",
      "SWC Logo Tee",
      "White Anchor Tee",
      "White Layered LS",
      "White LS",
      "White Tee",
      "White V-Neck Tee",
      "Yellow Layered LS",
    ],
    head: [
      "Anglerfish Mask",
      "Bucket Hat",
      "Eel-Cake Hat",
      "Festive Party Cone",
      "Hockey Mask",
      "Koshien Bandana",
      "Kyonshi Hat",
      "Li'l Devil Horns",
      "Mecha Head - HTR",
      "New Year's Glasses DX",
      "Painter's Mask",
      "Squid Facemask",
      "Twisty Headband",
      "White Headband",
      "Jetflame Crest",
      "Fierce Fishskull",
      "Hivemind Antenna",
      "Eye of Justice",
    ],
    shoes: ["Mecha Legs - LBS"],
  },
  {
    brand: "Takoroka",
    clothes: [
      "Choco Layered LS",
      "FC Albacore",
      "Gray Vector Tee",
      "Layered Vector LS",
      "Purple Camo LS",
      "Red Vector Tee",
      "Slipstream United",
      "Striped Rugby",
      "Takoroka Crazy Baseball LS",
      "Takoroka Galactic Tie Dye",
      "Takoroka Jersey",
      "Takoroka Nylon Vintage",
      "Takoroka Rainbow Tie Dye",
      "Takoroka Windcrusher",
      "Tricolor Rugby",
    ],
    head: ["Takoroka Mesh", "Takoroka Visor"],
    shoes: [
      "Athletic Arrows",
      "Blue Power Stripes",
      "Crazy Arrows",
      "LE Soccer Shoes",
      "New-Day Arrows",
      "Orange Arrows",
      "Orca Hi-Tops",
      "Orca Passion Hi-Tops",
      "Orca Woven Hi-Tops",
      "Red Power Stripes",
      "Soccer Shoes",
      "Sunset Orca Hi-Tops",
      "Trooper Power Stripes",
      "White Arrows",
    ],
  },
  {
    brand: "Tentatek",
    clothes: [
      "Black Squideye",
      "Blue Tentatek Tee",
      "Cycle King Jersey",
      "Lob-Stars Jersey",
      "Part-Time Pirate",
      "Red Tentatek Tee",
      "Silver Tentatek Vest",
      "Sky-Blue Squideye",
      "Tentatek Slogan Tee",
    ],
    head: [
      "Cycle King Cap",
      "Fake Contacts",
      "Green Novelty Visor",
      "Orange Novelty Visor",
      "Pink Novelty Visor",
      "Purple Novelty Visor",
      "Soccer Headband",
      "Sun Visor",
      "Tennis Headband",
    ],
    shoes: [
      "Amber Sea Slug Hi-Tops",
      "Black Norimaki 750s",
      "Black Trainers",
      "Blue Iromaki 750s",
      "Blue Sea Slugs",
      "Canary Trainers",
      "Cyan Trainers",
      "Gray Sea-Slug Hi-Tops",
      "Green Iromaki 750s",
      "Icy Down Boots",
      "Neon Sea Slugs",
      "Orange Iromaki 750s",
      "Pink Trainers",
      "Purple Iromaki 750s",
      "Purple Sea Slugs",
      "Red Iromaki 750s",
      "Red Sea Slugs",
      "Red-Mesh Sneakers",
      "Sea Slug Volt 95s",
      "Sesame Salt 270s",
      "Snowy Down Boots",
      "Violet Trainers",
      "White Norimaki 750s",
      "Yellow Iromaki 750s",
      "Yellow-Mesh Sneakers",
    ],
  },
  {
    brand: "Toni Kensa",
    clothes: [
      "Dark Bomber Jacket",
      "Front Zip Vest",
      "Half-Sleeve Sweater",
      "Ink-Wash Shirt",
      "Inkfall Shirt",
      "Kensa Coat",
      "Kung-Fu Zip-Up",
      "Light Bomber Jacket",
      "Negative Longcuff Sweater",
      "Panda Kung-Fu Zip-Up",
      "Positive Longcuff Sweater",
      "Pullover Coat",
      "Short Knit Layers",
      "Toni K. Baseball Jersey",
    ],
    head: ["Face Visor", "Ink-Guard Goggles", "Toni Kensa Goggles"],
    shoes: [
      "Arrow Pull-Ons",
      "Toni Kensa Black Hi-Tops",
      "Toni Kensa Soccer Shoes",
    ],
  },
  {
    brand: "Zekko",
    clothes: [
      "Birded Corduroy Jacket",
      "Black LS",
      "Black Polo",
      "Deep-Octo Satin Jacket",
      "Gray Mixed Shirt",
      "Green-Check Shirt",
      "Logo Aloha Shirt",
      "Olive Zekko Parka",
      "Red-Check Shirt",
      "Reel Sweat",
      "Squid Satin Jacket",
      "Tumeric Zekko Coat",
      "Varsity Jacket",
      "Zapfish Satin Jacket",
      "Zekko Baseball LS",
      "Zekko Hoodie",
      "Zekko Jade Coat",
      "Zekko Long Carrot Tee",
      "Zekko Long Radish Tee",
      "Zekko Redleaf Coat",
    ],
    head: [
      "Backwards Cap",
      "Black Arrowbands",
      "Double Egg Shades",
      "Five-Panel Cap",
      "Jogging Headband",
      "Matte Bike Helmet",
      "MTB Helmet",
      "Tinted Shades",
      "White Arrowbands",
      "Zekko Cap",
      "Zekko Mesh",
    ],
    shoes: [
      "Black Flip-Flops",
      "Blue Lo-Tops",
      "LE Lo-Tops",
      "Marination Lace-Ups",
      "Orange Lo-Tops",
      "Pearl-Scout Lace-Ups",
      "Suede Gray Lace-Ups",
      "Suede Marine Lace-Ups",
      "Suede Nation Lace-Ups",
    ],
  },
  {
    brand: "Zink",
    clothes: [
      "B-ball Jersey (Away)",
      "B-ball Jersey (Home)",
      "Cycling Shirt",
      "Dakro Golden Tee",
      "Dakro Nana Tee",
      "Inkopolis Squaps Jersey",
      "Navy Deca Logo Tee",
      "Retro Gamer Jersey",
      "School Jersey",
      "Urchins Jersey",
      "White Deca Logo Tee",
      "Zink Layered LS",
      "Zink LS",
    ],
    head: [
      "B-ball Headband",
      "Cycling Cap",
      "Golf Visor",
      "Squash Headband",
      "Swim Goggles",
    ],
    shoes: [
      "Black Dakroniks",
      "Black Seahorses",
      "Blue Laceless Dakroniks",
      "Chocolate Dakroniks",
      "Gold Hi-Horses",
      "Mint Dakroniks",
      "Purple Hi-Horses",
      "Red Hi-Horses",
      "White Laceless Dakroniks",
      "White Seahorses",
      "Yellow Seahorses",
      "Zombie Hi-Horses",
    ],
  },
]

export const clothingGear = [
  "Clt_AMB000",
  "Clt_AMB001",
  "Clt_AMB002",
  "Clt_AMB003",
  "Clt_AMB004",
  "Clt_AMB005",
  "Clt_AMB006",
  "Clt_AMB007",
  "Clt_AMB008",
  "Clt_AMB009",
  "Clt_AMB010",
  "Clt_COP100",
  "Clt_COP101",
  "Clt_COP102",
  "Clt_COP103",
  "Clt_COP104",
  "Clt_COP105",
  "Clt_COP106",
  "Clt_COP107",
  "Clt_COP108",
  "Clt_COP109",
  "Clt_COP110",
  "Clt_CRC000",
  "Clt_FST001",
  "Clt_FST002",
  "Clt_HAP001",
  "Clt_JKT000",
  "Clt_JKT001",
  "Clt_JKT002",
  "Clt_JKT003",
  "Clt_JKT004",
  "Clt_JKT005",
  "Clt_JKT006",
  "Clt_JKT007",
  "Clt_JKT008",
  "Clt_JKT009",
  "Clt_JKT010",
  "Clt_JKT011",
  "Clt_JKT012",
  "Clt_JKT013",
  "Clt_JKT014",
  "Clt_JKT015",
  "Clt_JKT016",
  "Clt_JKT017",
  "Clt_JKT018",
  "Clt_JKT019",
  "Clt_JKT020",
  "Clt_JKT021",
  "Clt_JKT022",
  "Clt_JKT023",
  "Clt_JKT024",
  "Clt_JKT025",
  "Clt_JKT026",
  "Clt_JKT027",
  "Clt_JKT028",
  "Clt_JKT029",
  "Clt_JKT030",
  "Clt_JKT031",
  "Clt_JKT032",
  "Clt_JKT033",
  "Clt_JKT034",
  "Clt_JKT035",
  "Clt_JKT036",
  "Clt_JKT037",
  "Clt_JKT038",
  "Clt_JKT039",
  "Clt_JKT040",
  "Clt_JKT041",
  "Clt_JKT042",
  "Clt_JKT043",
  "Clt_JKT044",
  "Clt_MSN000",
  "Clt_MSN004",
  "Clt_MSN101",
  "Clt_MSN104",
  "Clt_MSN105",
  "Clt_MSN106",
  "Clt_PLO000",
  "Clt_PLO001",
  "Clt_PLO002",
  "Clt_PLO003",
  "Clt_PLO004",
  "Clt_PLO005",
  "Clt_PLO006",
  "Clt_PLO007",
  "Clt_PLO008",
  "Clt_PRK000",
  "Clt_PRK001",
  "Clt_PRK002",
  "Clt_PRK004",
  "Clt_PRK005",
  "Clt_PRK006",
  "Clt_PRK007",
  "Clt_PRK008",
  "Clt_PRK009",
  "Clt_PRK010",
  "Clt_PRK011",
  "Clt_RVL000",
  "Clt_RVL001",
  "Clt_SHT000",
  "Clt_SHT001",
  "Clt_SHT002",
  "Clt_SHT003",
  "Clt_SHT004",
  "Clt_SHT005",
  "Clt_SHT006",
  "Clt_SHT007",
  "Clt_SHT008",
  "Clt_SHT009",
  "Clt_SHT010",
  "Clt_SHT011",
  "Clt_SHT012",
  "Clt_SHT013",
  "Clt_SHT014",
  "Clt_SHT015",
  "Clt_SHT017",
  "Clt_SHT018",
  "Clt_SHT019",
  "Clt_SHT020",
  "Clt_SHT021",
  "Clt_SHT022",
  "Clt_SHT023",
  "Clt_SHT024",
  "Clt_SHT025",
  "Clt_SHT026",
  "Clt_SHT027",
  "Clt_SHT028",
  "Clt_SHT029",
  "Clt_SWT000",
  "Clt_SWT001",
  "Clt_SWT002",
  "Clt_SWT003",
  "Clt_SWT004",
  "Clt_SWT005",
  "Clt_SWT006",
  "Clt_SWT007",
  "Clt_SWT008",
  "Clt_SWT009",
  "Clt_SWT010",
  "Clt_SWT011",
  "Clt_SWT012",
  "Clt_SWT013",
  "Clt_SWT014",
  "Clt_SWT015",
  "Clt_TEL000",
  "Clt_TEL001",
  "Clt_TEL002",
  "Clt_TEL003",
  "Clt_TEL004",
  "Clt_TEL005",
  "Clt_TEL006",
  "Clt_TEL007",
  "Clt_TEL008",
  "Clt_TEL009",
  "Clt_TEL010",
  "Clt_TEL011",
  "Clt_TEL012",
  "Clt_TEL013",
  "Clt_TEL014",
  "Clt_TEL015",
  "Clt_TEL016",
  "Clt_TEL017",
  "Clt_TEL018",
  "Clt_TEL019",
  "Clt_TEL020",
  "Clt_TEL021",
  "Clt_TEL022",
  "Clt_TEL023",
  "Clt_TEL024",
  "Clt_TES000",
  "Clt_TES001",
  "Clt_TES002",
  "Clt_TES003",
  "Clt_TES004",
  "Clt_TES005",
  "Clt_TES006",
  "Clt_TES007",
  "Clt_TES008",
  "Clt_TES009",
  "Clt_TES010",
  "Clt_TES011",
  "Clt_TES012",
  "Clt_TES013",
  "Clt_TES014",
  "Clt_TES015",
  "Clt_TES016",
  "Clt_TES017",
  "Clt_TES018",
  "Clt_TES019",
  "Clt_TES020",
  "Clt_TES021",
  "Clt_TES022",
  "Clt_TES023",
  "Clt_TES026",
  "Clt_TES027",
  "Clt_TES028",
  "Clt_TES029",
  "Clt_TES030",
  "Clt_TES031",
  "Clt_TES032",
  "Clt_TES033",
  "Clt_TES034",
  "Clt_TES035",
  "Clt_TES036",
  "Clt_TES037",
  "Clt_TES038",
  "Clt_TES039",
  "Clt_TES040",
  "Clt_TES041",
  "Clt_TES042",
  "Clt_TES043",
  "Clt_TES044",
  "Clt_TES045",
  "Clt_TES046",
  "Clt_TES047",
  "Clt_TES048",
  "Clt_TES049",
  "Clt_TES050",
  "Clt_TES051",
  "Clt_TES052",
  "Clt_TES053",
  "Clt_TES054",
  "Clt_TES055",
  "Clt_TES056",
  "Clt_TES057",
  "Clt_TES058",
  "Clt_TES059",
  "Clt_TES060",
  "Clt_TES061",
  "Clt_TLY000",
  "Clt_TLY001",
  "Clt_TLY002",
  "Clt_TLY003",
  "Clt_TLY004",
  "Clt_TLY005",
  "Clt_TLY006",
  "Clt_TLY007",
  "Clt_TLY008",
  "Clt_TLY009",
  "Clt_TLY010",
  "Clt_TLY011",
  "Clt_TLY012",
  "Clt_TLY013",
  "Clt_TNK000",
  "Clt_TNK001",
  "Clt_TNK003",
  "Clt_TNK004",
  "Clt_TNK005",
  "Clt_TNK006",
  "Clt_VST000",
  "Clt_VST001",
  "Clt_VST002",
  "Clt_VST003",
  "Clt_VST004",
  "Clt_VST005",
  "Clt_VST007",
  "Clt_VST008",
  "Clt_VST009",
]

export const headGear = [
  "Hed_ACC001",
  "Hed_AMB000",
  "Hed_AMB001",
  "Hed_AMB002",
  "Hed_AMB003",
  "Hed_AMB004",
  "Hed_AMB005",
  "Hed_AMB006",
  "Hed_AMB007",
  "Hed_AMB008",
  "Hed_AMB009",
  "Hed_AMB010",
  "Hed_CAP000",
  "Hed_CAP001",
  "Hed_CAP002",
  "Hed_CAP003",
  "Hed_CAP004",
  "Hed_CAP005",
  "Hed_CAP006",
  "Hed_CAP007",
  "Hed_CAP008",
  "Hed_CAP009",
  "Hed_CAP010",
  "Hed_CAP011",
  "Hed_CAP012",
  "Hed_CAP014",
  "Hed_CAP018",
  "Hed_CAP019",
  "Hed_CAP020",
  "Hed_CAP021",
  "Hed_CAP023",
  "Hed_CAP024",
  "Hed_CAP025",
  "Hed_CAP026",
  "Hed_CAP027",
  "Hed_COP100",
  "Hed_COP101",
  "Hed_COP102",
  "Hed_COP103",
  "Hed_COP104",
  "Hed_COP105",
  "Hed_COP106",
  "Hed_COP107",
  "Hed_COP108",
  "Hed_COP109",
  "Hed_CRC000",
  "Hed_EYE000",
  "Hed_EYE001",
  "Hed_EYE002",
  "Hed_EYE003",
  "Hed_EYE004",
  "Hed_EYE005",
  "Hed_EYE006",
  "Hed_EYE007",
  "Hed_EYE008",
  "Hed_EYE009",
  "Hed_EYE010",
  "Hed_EYE011",
  "Hed_EYE012",
  "Hed_EYE013",
  "Hed_EYE014",
  "Hed_EYE015",
  "Hed_EYE016",
  "Hed_EYE017",
  "Hed_EYE018",
  "Hed_EYE019",
  "Hed_EYE020",
  "Hed_FST000",
  "Hed_HAP000",
  "Hed_HAP001",
  "Hed_HAP002",
  "Hed_HAP003",
  "Hed_HAP004",
  "Hed_HAP005",
  "Hed_HAP006",
  "Hed_HAP007",
  "Hed_HAP008",
  "Hed_HAP009",
  "Hed_HAP010",
  "Hed_HAP011",
  "Hed_HAP012",
  "Hed_HAP013",
  "Hed_HAP014",
  "Hed_HAP015",
  "Hed_HAT000",
  "Hed_HAT001",
  "Hed_HAT002",
  "Hed_HAT003",
  "Hed_HAT004",
  "Hed_HAT005",
  "Hed_HAT006",
  "Hed_HAT007",
  "Hed_HAT008",
  "Hed_HAT009",
  "Hed_HAT010",
  "Hed_HAT011",
  "Hed_HAT012",
  "Hed_HAT013",
  "Hed_HAT014",
  "Hed_HBD001",
  "Hed_HBD002",
  "Hed_HBD003",
  "Hed_HBD004",
  "Hed_HBD005",
  "Hed_HBD007",
  "Hed_HBD008",
  "Hed_HDP000",
  "Hed_HDP001",
  "Hed_HDP002",
  "Hed_HDP003",
  "Hed_HDP004",
  "Hed_HDP005",
  "Hed_HDP006",
  "Hed_MET000",
  "Hed_MET002",
  "Hed_MET004",
  "Hed_MET005",
  "Hed_MET006",
  "Hed_MET007",
  "Hed_MET008",
  "Hed_MET009",
  "Hed_MET010",
  "Hed_MET011",
  "Hed_MSK000",
  "Hed_MSK001",
  "Hed_MSK002",
  "Hed_MSK003",
  "Hed_MSK004",
  "Hed_MSK005",
  "Hed_MSK006",
  "Hed_MSK007",
  "Hed_MSK008",
  "Hed_MSK009",
  "Hed_MSK010",
  "Hed_MSK011",
  "Hed_MSK012",
  "Hed_MSK013",
  "Hed_MSN000",
  "Hed_MSN004",
  "Hed_MSN101",
  "Hed_MSN104",
  "Hed_MSN105",
  "Hed_MSN106",
  "Hed_MSN107",
  "Hed_MSN108",
  "Hed_NCP000",
  "Hed_NCP001",
  "Hed_NCP002",
  "Hed_NCP003",
  "Hed_NCP004",
  "Hed_NCP005",
  "Hed_NCP006",
  "Hed_NCP008",
  "Hed_NCP009",
  "Hed_NCP010",
  "Hed_NCP011",
  "Hed_RVL002",
  "Hed_RVL003",
  "Hed_VIS000",
  "Hed_VIS001",
  "Hed_VIS002",
  "Hed_VIS003",
  "Hed_VIS004",
]

export const shoesGear = [
  "Shs_AMB000",
  "Shs_AMB001",
  "Shs_AMB002",
  "Shs_AMB003",
  "Shs_AMB004",
  "Shs_AMB005",
  "Shs_AMB006",
  "Shs_AMB007",
  "Shs_AMB008",
  "Shs_AMB009",
  "Shs_AMB010",
  "Shs_BOT000",
  "Shs_BOT001",
  "Shs_BOT002",
  "Shs_BOT003",
  "Shs_BOT004",
  "Shs_BOT005",
  "Shs_BOT006",
  "Shs_BOT007",
  "Shs_BOT008",
  "Shs_BOT009",
  "Shs_BOT010",
  "Shs_BOT011",
  "Shs_BOT012",
  "Shs_BOT013",
  "Shs_BOT014",
  "Shs_BOT015",
  "Shs_BOT016",
  "Shs_BOT017",
  "Shs_BOT018",
  "Shs_CFS000",
  "Shs_CFS001",
  "Shs_COP101",
  "Shs_COP102",
  "Shs_COP103",
  "Shs_COP104",
  "Shs_COP105",
  "Shs_COP106",
  "Shs_CRC000",
  "Shs_FST000",
  "Shs_HAP000",
  "Shs_HAP001",
  "Shs_HAP002",
  "Shs_HAP003",
  "Shs_HAP004",
  "Shs_HAP005",
  "Shs_HAP006",
  "Shs_HAP007",
  "Shs_LTS000",
  "Shs_LTS001",
  "Shs_LTS002",
  "Shs_LTS003",
  "Shs_LTS004",
  "Shs_LTS005",
  "Shs_LTS006",
  "Shs_LTS007",
  "Shs_LTS008",
  "Shs_LTS009",
  "Shs_LTS010",
  "Shs_LTS011",
  "Shs_LTS012",
  "Shs_MSN000",
  "Shs_MSN004",
  "Shs_MSN101",
  "Shs_MSN104",
  "Shs_MSN105",
  "Shs_MSN106",
  "Shs_SDL000",
  "Shs_SDL001",
  "Shs_SDL003",
  "Shs_SDL004",
  "Shs_SDL005",
  "Shs_SDL006",
  "Shs_SDL007",
  "Shs_SDL008",
  "Shs_SDL009",
  "Shs_SHI000",
  "Shs_SHI001",
  "Shs_SHI002",
  "Shs_SHI003",
  "Shs_SHI004",
  "Shs_SHI005",
  "Shs_SHI006",
  "Shs_SHI008",
  "Shs_SHI009",
  "Shs_SHI010",
  "Shs_SHI011",
  "Shs_SHI012",
  "Shs_SHI013",
  "Shs_SHI014",
  "Shs_SHI015",
  "Shs_SHI016",
  "Shs_SHI017",
  "Shs_SHI018",
  "Shs_SHI019",
  "Shs_SHI020",
  "Shs_SHI021",
  "Shs_SHI022",
  "Shs_SHI023",
  "Shs_SHI024",
  "Shs_SHI025",
  "Shs_SHI026",
  "Shs_SHI027",
  "Shs_SHI028",
  "Shs_SHI029",
  "Shs_SHI030",
  "Shs_SHI031",
  "Shs_SHI032",
  "Shs_SHI033",
  "Shs_SHI034",
  "Shs_SHI035",
  "Shs_SHI036",
  "Shs_SHI037",
  "Shs_SHI038",
  "Shs_SHI039",
  "Shs_SHI040",
  "Shs_SHI041",
  "Shs_SHT000",
  "Shs_SHT001",
  "Shs_SHT002",
  "Shs_SHT003",
  "Shs_SHT004",
  "Shs_SHT005",
  "Shs_SHT006",
  "Shs_SHT007",
  "Shs_SHT008",
  "Shs_SHT009",
  "Shs_SHT010",
  "Shs_SHT011",
  "Shs_SHT012",
  "Shs_SHT013",
  "Shs_SHT014",
  "Shs_SHT015",
  "Shs_SHT016",
  "Shs_SHT017",
  "Shs_SHT018",
  "Shs_SHT019",
  "Shs_SLO000",
  "Shs_SLO001",
  "Shs_SLO002",
  "Shs_SLO003",
  "Shs_SLO004",
  "Shs_SLO005",
  "Shs_SLO006",
  "Shs_SLO007",
  "Shs_SLO008",
  "Shs_SLO009",
  "Shs_SLO010",
  "Shs_SLO011",
  "Shs_SLO012",
  "Shs_SLO013",
  "Shs_SLO014",
  "Shs_SLO015",
  "Shs_SLO016",
  "Shs_SLO017",
  "Shs_SLO018",
  "Shs_SLO019",
  "Shs_SLO020",
  "Shs_SLP000",
  "Shs_SLP001",
  "Shs_SLP002",
  "Shs_SLP003",
  "Shs_TRS000",
  "Shs_TRS001",
  "Shs_TRS002",
]
